### ISSUE TITLE
Controller not found (Gears 5 Kait Diaz Limited Edition ).

### ISSUE THREAD

**Issue by ritchy7** [360Controller/360Controller#1010]
### Type of Controller
Xbox One 

### OS Version
MacOS Catalina 10.15.3

### Driver Version
?

### Connection Method
Bluetooth

### Device Name and Info
>Device Name: Gears 5 Kait Diaz Limited Edition Controller.
<br/>Product ID:	0x02E0
<br/>Vendor ID:	0x045E

### Response of Controller
Connected in bluetooth.

### Response in Preference Pane
The software tell me "no device found"

### Detailed Explaination of Issue
I just bought the controller it connects well in bluetooth but in 360controller it's not detected.

**Comment by FranticRain** [comment]
This is a new device that needs to get added, and I'll get to it. But it is worth noting that the driver has nothing to do with the Bluetooth connection. So you confused me a bit with the way you filled out your form. Adding the item to the driver will only impact its ability to be used via a Wired connection.
