### ISSUE TITLE
Cannot Load Driver - error 603946986

### ISSUE THREAD

**Issue by thebigtomo** [360Controller/360Controller#1011]
### Type of Controller
Yush wired Xbox 360

### OS Version
El Capitan 10.11.6

### Driver Version
360Controller 1.0.0-alpha.5

### Connection Method
wired - usb

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID: 0x028e
<br/>Vendor ID: 0x045e  (Microsoft Corporation)

### Response of Controller
Lights up when first plugged in, then everything turns off

### Response in Preference Pane
No devices found in preferences pane

### Detailed Explaination of Issue
plugged controller in, it lights up but preferences pane cannot find it, uninstalled then reinstalled driver but still nothing. when I try clicking 'Enable Driver' the following message comes up
Cannot load driver
The driver has failed to load due to an unknown error, code: -603946986. Please report this error to the driver maintainer.
I'm no coder but can follow instructions, I'm also aware i'm running an oooold system so it might just be that.

**Comment by FranticRain** [comment]
This version of the driver should solve your problem. Let me know if you have any trouble with it.

[360ControllerInstall.dmg.zip](https://github.com/360Controller/360Controller/files/3993107/360ControllerInstall.dmg.zip)
