### ISSUE TITLE
Afterglow wired connected but button doesn't work

### ISSUE THREAD

**Issue by Emsyg** [360Controller/360Controller#1022]
### Type of Controller
Xbox One afterglow

### OS Version
Catalina 10.15.3

### Driver Version
latest - 5 

### Connection Method
wired

### Device Name and Info
>Device Name:
<br/>Product ID: 0x8233
<br/>Vendor ID:0x05ac (Apple Inc.)

### Response of Controller
the controller light's up

### Response in Preference Pane
The controller is recognised/connected but there is no response when I press the button on the controller

### Detailed Explaination of Issue
The controller is recognised in the panel, but the buttons doesn't work in the panel and/or in the games.

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
