### ISSUE TITLE
Change lettre 

### ISSUE THREAD

**Issue by stephscriptpag** [360Controller/360Controller#1025]
Hello,
I allow myself to contact you by mp because I see that you use mac os.
I would like to play fs 19 but I am tetraplegic.
I bought [XBOX ADAPTATIVE CONTOLLER](https://clk.tradedoubler.com/click?p=152407&a=403761&g=21425052&url=https://www.microsoft.com/fr-fr/p/manette-xbox-adaptive/8NSDBHZ1N3D8/0002?source=googleshopping&ef_id=EAIaIQobChMImN_7s-Wy6AIVA9reCh0uhA3FEAYYASABEgKedPD_BwE%3AG%3As&s_kwcid=AL!4249!3!264806855519!!!g!813353800240!&OCID=AID2000015_SEM_EAIaIQobChMImN_7s-Wy6AIVA9reCh0uhA3FEAYYASABEgKedPD_BwE%3AG%3As&activetab=pivot%3Aoverviewtab) in order to be able to [play with contactors](https://www.logitechg.fr/fr-fr/products/gamepads/adaptive-gaming-kit-accessories.943-000339.html?irclickid=36MRhG3ffxyOWRJ0WlXSvXJOUknS6qyNG3uMRI0&irgwc=1&utm_source=Impact&utm_medium=10078&utm_campaign=Online%20Tracking%20Link#943-000339) because I have mobility problems.
I installed [xbox 360 Controller](https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.5) on my Mac OS 10.14 computer
I plugged XBOX ADAPTATIVE CONTOLLER into USB on my computer and xbox 360 Controller detects it well

https://www.zupimages.net/viewer.php?id=20/13/8dit.png

I have connected contactors to ports A B Y X of the XBOX ADAPTATIVE CONTOLLER

Only I would like to change the letters A and B by Z and S

https://www.zupimages.net/viewer.php?id=20/13/vx0u.png

Is it possible ?

Thank you

**Comment by FranticRain** [comment]
Remapping buttons to letters is outside the scope of the driver. If you want to remap the buttons to other keys, check out tools like [Enjoyable](https://yukkurigames.com/enjoyable/).
