### ISSUE TITLE
No devices found - no Security & Privacy prompt

### ISSUE THREAD

**Issue by jackmrhughes** [360Controller/360Controller#1030]
### Type of Controller
Xbox One (bluetooth) controller x 2
Xbox One (non-bluetooth) controller x 1

### OS Version
macOS High Sierra 10.13.6

### Driver Version
360Controller 1.0.0-alpha.5

### Connection Method
Wired

### Device Name and Info
It isn't showing up as described in the readme (see attached) 
![Screen Shot 2020-03-29 at 20 03 34](https://user-images.githubusercontent.com/62852100/77857948-72cbac00-71f8-11ea-8de2-3c5b4a4c5189.png)

### Response of Controller
Hello! When connecting with cable only the newer controllers vibrate, the older (2015) controller doesn't vibrate. 

### Response in Preference Pane
The preference pane says 'No devices found' for all three controllers

### Detailed Explanation of Issue
I understand the way to revolve this issue is to go to Security & Privacy and allow "Drew Mills" but that isn't appearing for me. I've tried uninstalling, restarting, reinstalling, restarting multiple times and it still doesn't appear. It did appear once and I clicked allow but then nothing happened and since then it hasn't appeared. 
![Screen Shot 2020-03-29 at 19 58 40](https://user-images.githubusercontent.com/62852100/77857810-c1c51180-71f7-11ea-80f8-b20e141110aa.png)

**Comment by FranticRain** [comment]
The driver can't see the controller if the OS can't see the controller. Try a different cable or different path to the machine (if you're using a hub) to see if you can get your controller to show up in the system info.

**Comment by betik** [comment]
i am also having this problem?

**Comment by FranticRain** [comment]
@betik Is your problem identical? Are the controllers not found in the system info? I can't help you with this little information.

**Comment by jackmrhughes** [comment]
I tried the cable my flatmate uses to charge his PS controller and it immediately worked and recognised the controller, thanks for the suggestion! I guess the cable I was using wasn't good enough. The only issue I have now is the mapping isn't recognised in game (Left 4 Dead 2) but I realise that isn't your problem. Having more success with the Steam Big Picture Mode / Tattiebogle driver, but still needs a lot of tweaking in the controller configuration.

**Comment by FranticRain** [comment]
Yeah. Not all cables are created equal. Some only have the wires in them to charge things, You need the ones that send data, otherwise the device can't talk to the operating system.

Glad that you got it working. I'm going to go ahead and close this down.

**Comment by ElDuderino777** [comment]
i'm having the same issue with my 3rd party 360 controller not showing up in the systems report...it's wired, so there's no way just to use another cord
