### ISSUE TITLE
Controller not detected

### ISSUE THREAD

**Issue by 4nZwar3** [360Controller/360Controller#1033]
### Type of Controller
3rd Party Controller (supposedly compatible)

### OS Version
Mac OS High Sierra 10.13.6

### Driver Version
Version 1.0.0-alpha.5

### Connection Method
Wired

### Device Name and Info
>Device Name: PC/PS3/Android Gamepad
<br/>Product ID: 0x0575
<br/>Vendor ID: 0x2563

### Response of Controller
Controller turns on but does not connect properly, appears in system info app though.

### Response in Preference Panel
None

### Detailed Explaination of Issue
The controller has many ways to be turned on by means of commands since each one is specified for different devices (ex: HOME + X = Bluetooth for PC and Android), in this case the command is HOME + Y (Mac USB Wired Mode) and it is supposed to turn on the controller as a type of Xbox 360 controller because in the instruction manual indicates that this driver must be installed for use. Anyway, when you connect the controller and turn it on the right way (with the driver already installed, of course) the light stays blinking, as if still searching for the device.
Manual instructions picture:
![IMG_20200330_164938](https://user-images.githubusercontent.com/57868378/77969465-ffcd3e80-72a6-11ea-92bb-0750b88ba0d9.jpg)

**Comment by 4nZwar3** [comment]
**Note:**
I actually couldn’t find the Product ID and Vendor ID from the Mac USB wired mode, but using the Android+PC Wired mode did, and gave me different info from the same boot. If you hold the HOME button while connected it changes the led from the 2nd one to the 3rd one, changing its info in the process. Also I could found the Bluetooth info.

**Android+PC Wired mode (v2):**
	Product ID: 0x028e
	Vendor ID: 0x045e

**Bluetooth mode:**
	Product ID: 0x0402
	Vendor ID: 0x1949

**Comment by FranticRain** [comment]
Give this build a shot and let me know if that solves your problem: https://github.com/360Controller/360Controller/files/3812654/360ControllerInstall.dmg.zip

**Comment by 4nZwar3** [comment]
It works! Thank You
