### ISSUE TITLE
Will not work on future versions of MacOS

### ISSUE THREAD

**Issue by odysseywilson** [360Controller/360Controller#1035]
### Type of Controller
N/A

### OS Version
MacOS Catalina 10.15.4
### Driver Version
Version 1.0.0-alpha.5

### Connection Method
N/A

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: N/A
<br/>Product ID: N/A
<br/>Vendor ID: N/A

### Response of Controller
N/A
### Response in Preference Pane
N/A

### Detailed Explaination of Issue
I do not have an issue yet, but wanted to point out that when I updated to MacOS 10.15.4 from 10.15.3 I got a message that says that this software installed a legacy system extension that will not be compatible with future versions of MacOS. The exact message I got is shown at https://support.apple.com/en-us/HT210999 but instead of "DEVELOPER_NAME" it said "Drew Mills" which I googled and found to be one of the developers of this program. Just wanted to warn that some patches will likely be necessary for newer MacOS versions, I do not really have much more information to provide
![image](https://user-images.githubusercontent.com/43554175/78205275-9b4de300-7450-11ea-84af-70a0356c76ca.png)

**Comment by FranticRain** [comment]
I'm well aware and I'm working on the fix. Apple has not provided any documentation on the actual process of developing this next generation of drivers, and I am actively working with them to figure out how to get this done.
