### ISSUE TITLE
The driver has failed to load due to an unknown error, code: -603946986

### ISSUE THREAD

**Issue by Rosmia** [360Controller/360Controller#1039]
### Type of Controller
Xbox 360

### OS Version
10.11

### Driver Version
360Controller 1.0.0-alpha.5

### Connection Method
Wired

### Device Name and Infon
N/A

### Response in Preference Pane
No response

### Detailed Explanation of Issue
cannot enable driver from system setting, dialog shows
“The driver has failed to load due to an unknown error, code: -603946986” and ask me give this information to developer.

Tried uninstall with given script, reboot and reinstall, with the exactly same error code.

**Comment by toastedlightly** [comment]
same issue

**Comment by PGilbertSchmitt** [comment]
Same issue

**Comment by fabitorychter** [comment]
Same here!

**Comment by CreeperCry04** [comment]
yep, same here

**Comment by FranticRain** [comment]
Should be resolved with alpha 6.
