### ISSUE TITLE
Are Wirless XBox 360 controller supported with 1.x?

### ISSUE THREAD

**Issue by ajmas** [360Controller/360Controller#1045]
### Type of Controller
Xbox 360

### OS Version
10.15.4

### Driver Version
1.0.0-alpha.5

### Connection Method
Official Microsoft wireless adapter, that came with 360 controller

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: Xbox 360 Wireless Receiver for Windows
<br/>Product ID: 0x0719
<br/>Vendor ID: 0x045e

When cabled, using alpha 2:
> Device Name: Vendor-Specific Device
<br/>Product ID: 0x028f
<br/>Vendor ID: 0x045e

### Response of Controller
Having trouble syncing. 

### Response in Preference Pane
Preference pane shows not devices connected.

### Detailed Explanation of Issue
I am using a 16" MacBook Pro with a Anker adapter plugged in. Into that I have plugged in my Microsoft wireless adapter. I tried syncing with the steps in the following video:

https://www.youtube.com/watch?v=3o-RgAM_GUY

I just end up with a flashing green ring around the X-Box button. I have tried multiple controllers and did also look in /var/log/system.log, but see nothing of note.

I did try 1.0.0-alpha.2, based on a suggestion, but no luck there. I did then try a cabled XBox 360 controller, but it just flashes. When plugged in directly I do get to see the device in the system information, but nothing in the system preference pane.

I have not tried killing the 360Daemon, but when I do so a dialogue pops up stating:

> You have attached a Microsoft Play & Charge cable for your Xbox 360 Wireless Controller. While this cable will allow you to charge your wireless controller, you will require the Microsoft Wireless Gaming Receiver for Windows to use your wireless controller in Mac OS X!

I then see the daemon has resumed.

One last shot in the dark:

```
cd /Library/Extensions
sudo kextload /Library/Extensions/Wireless360Controller.kext
```

results in:

```
/Library/Extensions/Wireless360Controller.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
```

**Comment by FranticRain** [comment]
Nope.

**Comment by ajmas** [comment]
Is there anything on the roadmap for this and what are the challenges at this point?

**Comment by FranticRain** [comment]
> Is there anything on the roadmap...

Nope. Number one priority is getting the driver ported to DriverKit, since the current framework is being deprecated.

> ...what are the challenges at this point?

Lack of interest in working on this project.
