### ISSUE TITLE
Do the Bluetooth devices support planned?

### ISSUE THREAD

**Issue by Ignisor** [360Controller/360Controller#1046]
Hi!

I just wanted to know.
Do the Bluetooth devices support planned? E.g., Xbox One wireless controller (MODEL - 1708).

Tried with 360Controller 1.0.0-alpha.5 but "No devices found".

**Comment by FranticRain** [comment]
Since Bluetooth controllers are supported natively by macOS, they are outside the scope of the driver. Furthermore, there is no way for us to spoof a Bluetooth controller into the type of object that the driver makes, so it is impossible.

**Comment by Ignisor** [comment]
Thanks
