### ISSUE TITLE
NVIDIA SHIELD Third Party Controller Not Recognized

### ISSUE THREAD

**Issue by manHands** [360Controller/360Controller#1050]
### Type of Controller
NVIDIA SHIELD Controller

### OS Version
10.15.4

### Driver Version
0.6.11

### Connection Method
Wired

### Device Name and Info
>Device Name: NVIDIA SHIELD Controller
<br/>Product ID: 29204
<br/>Vendor ID: 2389

### Response of Controller
Not detected.

### Response in Preference Pane
Does not appear in Preference Pane

### Detailed Explaination of Issue
Followed the instructions to adding third party controllers in Readme. However, my controller is still not recognized. I've tried 1.0.0-alpha-5 as well, but no difference. Confirmed that updated kext is loaded.

![Screen Shot 2020-04-12 at 3 42 53 PM](https://user-images.githubusercontent.com/10609335/79079373-4887ed00-7cd4-11ea-8290-ad0ddc30bea8.png)

![Screen Shot 2020-04-12 at 3 43 55 PM](https://user-images.githubusercontent.com/10609335/79079399-6ce3c980-7cd4-11ea-806a-471da65260f5.png)

![Screen Shot 2020-04-12 at 3 44 19 PM](https://user-images.githubusercontent.com/10609335/79079407-7cfba900-7cd4-11ea-8e4c-af5d6f1fa581.png)

**Comment by FranticRain** [comment]
This controller is not supported by official Xbox hardware. As such, its support is outside the scope of this driver. We cannot and will not support this controller.
