### ISSUE TITLE
Third party Xbox one controller not found

### ISSUE THREAD

**Issue by katbard** [360Controller/360Controller#1053]
### Type of Controller
Xbox One Third Party

### OS Version
Catalina 10.15.4

### Driver Version
360Controller 1.0.0-alpha.5 and alpha 4

### Connection Method
Wired

### Device Name and Info
>Device Name: XB1 Classic Controller
<br/>Product ID: 0x581b
<br/>Vendor ID: 0x24c6

### Response of Controller
Controller does not respond, it does not light up or vibrate. 360controller shows “no devices found”

### Response in Preference Pane
The controller appears in the preference pane on Mac but does not connect. It says “no devices found” all of the buttons, joysticks, and triggers do not work.

### Detailed Explaination of Issue
Third party wired Xbox one controller connected through USB, appears under “hardware” in the system report window on Mac, but does not connect to 360controller driver. Under “controller test” it is not detected nor does it vibrate or light up when plugged in. Tried unsuccessfully in both USB slots and multiple cords on both alpha 4 and 5.

**Comment by katbard** [comment]
Thank you in advance, I am fairly new around here so I am not sure how to do it on my own.

**Comment by jjfattz** [comment]
I have the same controller.  Would be nice to have it added.

**Comment by saundemail** [comment]
I have the same controller.  Can it be added?

**Comment by FranticRain** [comment]
Added in alpha 6.

**Comment by jm2** [comment]
Why was a PowerA controller (according to the device ID) added as the Hyperkin Duke here (according to the key)?
