### ISSUE TITLE
GH Live 360 Controller sync problems on Mojave

### ISSUE THREAD

**Issue by LordSuicide** [360Controller/360Controller#1055]
### Type of Controller
Original Xbox 360 Guitar Hero Live Guitar Controller

### OS Version
10.14.6 Mojave

### Driver Version
I tried many drivers

### Connection Method
Wireless Bluetooth Adapter

### Device Name and Info
N/A

### Response of Controller
N/A

### Response in Preference Pane
It doesn't  appear in the preference pane

### Detailed Explaination of Issue
I bought an original Xbox 360 Guitar Hero Live guitar because I read that this is the only way to use Clone Hero on my Mac. After installing of some drivers I every time only have in my preference pane the option for wired controllers. Is there any option for me to run this guitar on my Mac? The dongle blinks but it won't connect to my guitar so I can't use it, that's the only problem I've got.

https://ibb.co/Fgj7nzx
https://ibb.co/3vdpNhm

**Comment by FranticRain** [comment]
We don't support wireless dongles of this type. If it conforms to the wireless dongle specification, it may work with the older versions of the driver that have wireless controller support. But it is outside the scope of support of the driver.
