### ISSUE TITLE
Third party controller not found

### ISSUE THREAD

**Issue by Khaur** [360Controller/360Controller#1056]
### Type of Controller
Third party Xbox 360

### OS Version
Mojave 10.14.6

### Driver Version
1.0.0 alpha 5

### Connection Method
Wired

### Device Name and Info
>Device Name: USB Gamepad (1 extra space before, 10 after)
<br/>Product ID: 0x0001
<br/>Vendor ID: 0x0810  (Personal Communication Systems, Inc.)

### Response of Controller
Guide button lights toggle on press.

### Response in Preference Pane
Controller does not appear on the preference Pane

### Detailed Explaination of Issue
The controller isn't recognised by the driver. I managed to find an old issue (#193) with the same vendor/product ID, which apparently was solved locally by the user with a manual build.
However, I did not manage to follow the build instructions in the README as XCode 6.4 won't run on my machine.

The controller responds on https://html5gamepad.com/, where it seems the guide button toggles between input modes.

**Comment by FranticRain** [comment]
Added in alpha 6.
