### ISSUE TITLE
xbox 1 FUSION Pro Controller not working

### ISSUE THREAD

**Issue by LaksheyHooda** [360Controller/360Controller#1059]
### Type of Controller
xbox 1 FUSION Pro Controller

### OS Version
Mojave

### Driver Version
Alpha-5.0

### Connection Method
Wired via USB

### Device Name and Info
<img width="1038" alt="Screen Shot 2020-04-30 at 11 20 27 PM" src="https://user-images.githubusercontent.com/21001029/80786787-82ad1780-8b39-11ea-8c71-6a303e5f29d7.png">

### Response of Controller
The driver does not recognize the controller and I cannot turn on the controller or use it.

### Response in Preference Pane
It does not appear, and I cant select it.

### Detailed Explanation of Issue
I bought a FUSION pro xbox 1 controller from amazon. https://www.amazon.com/PowerA-Fusion-Pro-Wired-Controller-Xbox/dp/B07XQXQMR9 and have been trying to connect it to my mac for the last couple hours. I know it must work because on this link, https://support.powera.com/hc/en-us/articles/360035586772-FUSION-Pro-Controller-2019-Release-Firmware-Update-v1-24-for-Mac, it give a firmware update which requires you to turn on the controller and press button to calibrate it. It recognizes all my button presses just fine when calibrating. If you have a solution that would be great!

**Comment by FranticRain** [comment]
Added in alpha 6.
