### ISSUE TITLE
Hori Tactical Commander Keypad

### ISSUE THREAD

**Issue by chabi777** [360Controller/360Controller#1065]
### Type of Controller
3rd Party

### OS Version
10.15.4 Catalina

### Driver Version
1.0.0-alpha.5

### Connection Method
Wired

### Device Name and Info
Device Name: HORI Keypad
Product ID: 315
Vendor ID: 3853

HORI KeyPad:

  Product ID:	0x013b
  Vendor ID:	0x0f0d  (HORI CO., LTD.)
  Version:	1.01
  Speed:	Up to 12 Mb/s
  Manufacturer:	HORI CO.,LTD.
  Location ID:	0x14422000 / 29
  Current Available (mA):	500
  Extra Operating Current (mA):	0

### Response of Controller
Controller keypad is active.  Thumb analog stick is not responding.

### Response in Preference Pane
No devices found in the dropdown.

### Detailed Explaination of Issue
Device isn't found in the dropdown menu; probably needs adding as a new device.

**Comment by FranticRain** [comment]
We only support devices that work with Xbox hardware. This device is not compatible with Xbox hardware, and is therefore not compatible with the driver.
