### ISSUE TITLE
Wired Controller Mac osx 10.12 is not recognized

### ISSUE THREAD

**Issue by malialis** [360Controller/360Controller#1067]
### Type of Controller
Xbox 360

### OS Version
Mac osx 10.12

### Driver Version
1.0 Alpha 5

### Connection Method
Wired
![Screen Shot 2020-05-13 at 2 06 23 PM](https://user-images.githubusercontent.com/13682996/81860648-4491f980-9524-11ea-951d-feb0facb8ac2.png)
![Screen Shot 2020-05-13 at 12 00 17 PM](https://user-images.githubusercontent.com/13682996/81860651-452a9000-9524-11ea-9224-acdf22ae1362.png)

### Device Name and Info
Batarang Wired Controller 
0x3f10 Product
0x15e4 Vendor

### Response of Controller
The Guide button flashes when I sign into the desktop and then nothing. I press the button no response. It is not read in the settings. 

### Response in Preference Pane
Does not appear in preference pane.

### Detailed Explaination of Issue
I have rebooted several times, tried plugging in the controller before and after powering on the system. Before and after signing into the desktop. No changes. When I try to enable the driver in the Preference pane I get an error.

The driver has failed to load due to an unknown error code -603946986

**Comment by FranticRain** [comment]
This should be resolved with alpha 6.
