### ISSUE TITLE
No device found with my xbox cyberpunk controller (wireless)

### ISSUE THREAD

**Issue by TESTVNULL** [360Controller/360Controller#1074]
### Type of Controller
 Xbox cyberpunk controller

### OS Version
10.15.4

### Driver Version
Alpha6

### Connection Method
Bluetooth

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: NA
<br/>Product ID: NA
<br/>Vendor ID: NA

### Response of Controller
Bluetooth connected

### Response in Preference Pane
No devices found

### Detailed Explaination of Issue
Bluetooth connected but no devices found on the system preferences. My controller is the new Xbox cyberpunk controller.

**Comment by FranticRain** [comment]
Bluetooth controllers are not supported by this driver. They will not show up in the preference pane of this driver. Bluetooth Xbox One controllers are supported by default in the operating system, and therefore do not need a driver to function. You only need the driver if you wish to connect your Xbox One controller via USB. If you would like to test if your Xbox One Bluetooth controller is properly connected to your computer, I recommend a HTML5 gamepad tester like [this one.](http://html5gamepad.com/)
