### ISSUE TITLE
Wrong version 5 and 6

### ISSUE THREAD

**Issue by mac4kent** [360Controller/360Controller#1075]
### Type of Controller
360 Controller wired

### OS Version
MacOS Catalina 10.15.5 beta

### Driver Version
N/A

### Connection Method
Wired USB

### Device Name and Info
N/A

### Response of Controller
N/A

### Response in Preference Pane
N/A

### Detailed Explaination of Issue
N/A

I found https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.6 but wrong version to be alpha 5 on my system preferences. Need to fix match version see picture
![image](https://user-images.githubusercontent.com/4253305/82755051-0e574400-9d86-11ea-9bd6-6ff2b208c866.png)

**Comment by bgruszka** [comment]
Agree, I have the same

**Comment by mac4kent** [comment]
True

**Comment by FranticRain** [comment]
Updated release to version that fixes this. Re-download the release to resolve the issue.

**Comment by mac4kent** [comment]
I check still 5 not 6. please send me link make sure match 6 not 5 on System Preferences @FranticRain

**Comment by FranticRain** [comment]
You're right. Xcode was being a jerk and didn't save my changes to the `.xib`. I've fixed it and re-uploaded it to the release page. Give it another shot.

**Comment by mac4kent** [comment]
@FranticRain  hehe ok. When you are finish everything update let me know.

**Comment by FranticRain** [comment]
It should be uploaded correctly now. I've tested it to confirm.

**Comment by mac4kent** [comment]
Good let me inspect.

**Comment by mac4kent** [comment]
it fixed congratulation good job.
Now I can see 6 there correct ya  ayayayayyyyy 

Now are you still work on left vibrate and right vibrate? @FranticRain

**Comment by FranticRain** [comment]
No. Apple broke the way we’re implementing force feedback. It will not work anymore with this driver.

**Comment by mac4kent** [comment]
Oh ok I got it understand. I can do force to Apple developers about xbox 360 controller USB connect wire.
