### ISSUE TITLE
360 Controller on MacOS 11 beta not work

### ISSUE THREAD

**Issue by mac4kent** [360Controller/360Controller#1086]
June 28, 2020
### Type of Controller
Xbox 360 Controller Driver

### OS Version
MacOS 11 Beta

### Driver Version
Version 1.0.0-alpha.6

### Connection Method
Wired USB

### Device Name and Info
N/A

### Response of Controller
Doesn't work

### Response in Preference Pane
N/A

### Detailed Explaination of Issue
MacOS 11 with 360 controller did not turn power on while USB plug

**Comment by FranticRain** [comment]
Duplicate of #1084
