### ISSUE TITLE
Can't uninstall (macOS Catalina)

### ISSUE THREAD

**Issue by julie-impuls** [360Controller/360Controller#1126]
### OS Version
macOS Catalina 10.15.7

### Driver Version
Version 1.0.0-alpha.3

### Detailed Explaination of Issue
If I click the 'uninstall' button under the 'advanced' tab, I get a popup to confirm. When I click on 'yes' and enter my password, I get a new popup with the following message: 'Error Uninstalling the Driver!'.
Is there any other way to uninstall?

**Comment by timtaylor4** [comment]
Hi, I'm having the same problem. I've tried to install the latest driver and am getting a 'Failed' message - I then tried to uninstall the one I have on system preferences and getting the error message.
The driver was working perfectly until I upgraded to Big Sur.

**Comment by erniep24** [comment]
im having the same issue after updating to big sur, any fixers?

**Comment by subirats345** [comment]
Same to my. I can't install on Big Sur

**Comment by FranticRain** [comment]
The latest releases include an `uninstall.command`. If you download that and double click it, it should manually uninstall the driver without the errors from the app. If that doesn't work, you can open up that file in your favorite text editor and see exactly what files you need to delete manually.
