### ISSUE TITLE
I cannot uninstall

### ISSUE THREAD

**Issue by JinKRJPEN** [360Controller/360Controller#1274]
### OS Version
14.1.1 (23B81)

### Driver Version
Version 1.0.0-alpha.6

### Detailed Explaination of Issue
I cannot uninstall.
When I input password, it shown error alert

![Screenshot 2023-12-08 at 10 24 53](https://github.com/360Controller/360Controller/assets/32891725/6284b96d-7701-403c-b5eb-c8a15c3a88a4)

**Comment by arturgola** [comment]
https://github.com/360Controller/360Controller/issues/1139
