### ISSUE TITLE
Unity mac joystick issues

### ISSUE THREAD

**Issue by erebuswolf** [360Controller/360Controller#132]
The xbox 360 joystick value in unity maxes out to 1 way faster than it should. On my windows machine it reaches a value of 1 or -1 at the edge of the joystick movement but using this driver on my mac it maxes out at less than half way through the motion of the joystick. Also, the vertical axis is inverted, though I don't have the inverted setting selected on the driver. This is with the latest version of the driver with unity 5.1.1f1 . The preferences window for the driver has 1 to 1 matchup with all joystick movement and seems to be fine. The hardware is also brand new and is a Microsoft brand 360 wired controller.

**Comment by FranticRain** [comment]
A note has been added to the Readme about this issue. As it is an issue with Unity, feel free to protest to them, but this isn't an actual issue with the driver, so I'm closing it.
