### ISSUE TITLE
Controller Doesn't Rumble Outside Of System Preferences

### ISSUE THREAD

**Issue by BakaNode** [360Controller/360Controller#136]
If I test the controller for rumble inside the system prefs pane it works. If I fire up a game like Borderlands 2 I get nothing during gameplay.

**Comment by RodrigoCard** [comment]
Does the game claim to be Rumble Compatible on Mac?

**Comment by FranticRain** [comment]
Aspyr ported games like Borderlands 2 subvert the driver. Therefore, rumble in Borderlands 2 is Aspyr's job, not a fault of the driver.
