### ISSUE TITLE
Logitech ChillStream gamepad not being recognized

### ISSUE THREAD

**Issue by Kombatologist** [360Controller/360Controller#145]
The gamepad was recognized using the 0.14 unofficial driver, but is no longer being recognized as of the 0.15 betas. After installing the 0.15 driver and restarting, all 4 green lights on the gamepad light up (as opposed to a single light when using the 0.14 driver) and the gamepad isn't recognized at all in System Preferences > Xbox 360 Controllers.

**Comment by Deph0** [comment]
Could you please provide the VendorID and productID from system repport?

**Comment by Kombatologist** [comment]
Product ID: 0xc242
Vendor ID: 0x046d  (Logitech Inc.)

**Comment by FranticRain** [comment]
This should be supported in the latest release. Let me know if you have any problems.

**Comment by monchote** [comment]
Confirmed that 0.15 (beta 4) now works with the Logitech ChillStream.
