### ISSUE TITLE
Microsoft Sidewinder Force Feedback 2 Wheel

### ISSUE THREAD

**Issue by donluca** [360Controller/360Controller#150]
Can you kindly add my wheel to the driver?

Product ID: 0x0034
Manufacter ID: 0x045e (Microsoft Corporation)

It has 3 analog Axis and it reports 15 buttons although only 8 are present on the wheel.

Thanks.

**Comment by RodrigoCard** [comment]
Is this a "Xinput" device?

**Comment by donluca** [comment]
It worked without drivers or issues in mac OS 10.6, so I guess it is. For some reasons it stopped working in 10.9 so now I need it to work through the x360 driver.

Il 27 settembre 2015 06:59:11 CEST, Rodrigo <notifications@github.com> ha scritto:

**Comment by RodrigoCard** [comment]
Xinput drivers never worked on OSX without additional driver, your device is not a Xinput-compatible device.

Unfortunately there is nothing much we can do for you. It is another unrelated problem :(
