### ISSUE TITLE
Hori Ex2 Fightstick not found

### ISSUE THREAD

**Issue by Copas27** [360Controller/360Controller#159]
This build is a lot better than the original 360 driver, however even though the plugin recognizes that there is a controller plugged in, my games don't respond or acknowledge its presence.
![screen shot 2015-10-27 at 9 34 20 pm](https://cloud.githubusercontent.com/assets/15354015/10778264/3662aaf2-7cf2-11e5-84b0-d21f436b1469.png)
![screen shot 2015-10-27 at 9 37 36 pm](https://cloud.githubusercontent.com/assets/15354015/10778296/9bce59a4-7cf2-11e5-9934-7fdf033754ce.png)
^ normally skullgirls displays a controller connected. 
![screen shot 2015-10-27 at 9 40 56 pm](https://cloud.githubusercontent.com/assets/15354015/10778340/09ec0abc-7cf3-11e5-8ed6-2c35ccf87aa1.png)
^my ps3 controller works but not my 360 controller.

**Comment by RodrigoCard** [comment]
This device's IDs are not on the list. It should be added in a future update, probably.

**Comment by FranticRain** [comment]
This device should be supported now. Let me know if you have any issues.
