### ISSUE TITLE
Where are the releases, builds?

### ISSUE THREAD

**Issue by rfay** [360Controller/360Controller#166]
Hi - Thanks for all the work on this.

The [README.md](https://github.com/360Controller/360Controller/blob/master/Readme.md) links to the [releases page from old d235j repo](https://github.com/d235j/360Controller/releases), which is empty.

Where are the releases, are there dmg files?

Thanks!

I'm happy to do a PR with doc change if I just know the magic :)

**Comment by d235j** [comment]
Fixed in https://github.com/360Controller/360Controller/commit/40de60b07620aa2c11b2c44f5d9392a151c045b5.

**Comment by rfay** [comment]
Wow, you really had me going. I forked, was going to edit (since I ended up finding the releases via google) and then wow, it was already right? How could that be? You're awesome. Thanks.
