### ISSUE TITLE
El capitan

### ISSUE THREAD

**Issue by akv12** [360Controller/360Controller#167]
I installed Beta 15 3 on my macbook and my mac mini.. my controller which is wireless works.. with the wireless receiver on my macbook. However, I have uninstalled all the drivers and everything and reinstalled the drivers and rebooted and it still won't work on el capitan on my mac mini.. Can someone please help me get this to work. I been looking for hours. Please help!

**Comment by akv12** [comment]
Please someone help me!

**Comment by akv12** [comment]
Also can someone make an UN-installation  script or app so Its easier to uninstall all the drivers! Please? I really want to play my game I just bought..now I feel like I wasted money!

**Comment by mazedlx** [comment]
Driver isn't working anymore with OS X El Capitan 10.11.2 Beta (15C27e)

**Comment by akv12** [comment]
Hi, how did u get to work before?

**Comment by mazedlx** [comment]
before 0.14 worked fine. upgraded recently to newest public beta, since then: nothing. upgraded the driver to 0.15b3 and still nothing

**Comment by akv12** [comment]
.14 works but .15 never worked you are saying?

**Comment by mazedlx** [comment]
no.
0.14 worked on the previous el capitan public beta (10.11.1) but not on 10.11.2 beta, as well as 0.15

**Comment by akv12** [comment]
I can't even get the controller to work. at all on my mac.. it works on my macbook but not my macmini and i am so annoyed

**Comment by akv12** [comment]
Have you tried to uninstall your drivers completely??

**Comment by mazedlx** [comment]
yes, to no avail.

**Comment by akv12** [comment]
how do I uninstall it?? I am having trouble doing it.. maybe i am doing something wrong.. can you help me?

**Comment by mazedlx** [comment]
i just removed the control panel icon with a right click

**Comment by akv12** [comment]
well that isn't enough... you aren't fully uninstalling... go to this link:http://forums.macrumors.com/threads/uninstall-xbox-360-controller-driver.447793/

**Comment by mazedlx** [comment]
thanks, will try that und reinstall 0.15b3

**Comment by akv12** [comment]
tell me if you have luck! I need help myself and I am annoyed!

**Comment by herrbischoff** [comment]
Please see https://github.com/360Controller/360Controller/issues/161

There is currently no way to get this to work. You need to revert back to 10.11.1, then the driver starts working again.

**Comment by mazedlx** [comment]
Happy to say that all issues went away with the current beta release (10.11.2 Beta (15C40a))

**Comment by akv12** [comment]
how I have it and i am having trouble!

**Comment by mazedlx** [comment]
uninstalled every trace of the driver. upgraded to the latest public beta, installe 0.15 beta 3 driver. done.

**Comment by daslicht** [comment]
Any news regarding 10.11.x ?

**Comment by RodrigoCard** [comment]
@daslicht : as @mazedlx it is working already

**Comment by daslicht** [comment]
thanks !
