### ISSUE TITLE
It's been 2 months and no release

### ISSUE THREAD

**Issue by TyanColte** [360Controller/360Controller#171]
Last release was September and we haven't heard a peep out of the dev since then. There are multiple issues. Elite controller not working yet, original XBone controller with the latest FW not working anymore, among others. What gives. At least let us know you're working on or planning on working on these issues. Or send us somewhere else that has these issues worked out. I'm not trying to be rude but I really miss my xbone controller on my mac. Thanks for all you've done so far.

**Comment by FranticRain** [comment]
Resolved.
