### ISSUE TITLE
XBox One controller recognized but test and binding not working.

### ISSUE THREAD

**Issue by StickerZombie** [360Controller/360Controller#176]
Hi, I've successfuly installed Beta3 on my MacBook Pro with Yosemite 10.10.2
My Xbox One controller is recognized by the system profiler and by the driver prefs panel as you can see on the screenshots:
![captura de pantalla 2015-12-01 a les 14 54 01](https://cloud.githubusercontent.com/assets/16101512/11502512/981c5572-983b-11e5-883a-f379f61f5f9f.png)
![captura de pantalla 2015-12-01 a les 14 53 25](https://cloud.githubusercontent.com/assets/16101512/11502515/99ee4efa-983b-11e5-9a6b-a8fab77b3a5d.png)
But I can't test or re-bind inputs.
The system is somehow detecting the controller as I can use it from Unity (with some weird input names) but the panel is not responding to any inputs.

Help! :_(

**Comment by FranticRain** [comment]
Okay first, make sure that you have fully uninstalled any other driver from your system. For example, if you previously had Xone-OSX installed, make sure to run the `uninstall.command` to fully remove it. If you have made sure to fully uninstall all other drivers, and the light on the controller still turns on, then it looks like the driver thinks it is connected, but the controller isn't properly communicating with the driver.

**Comment by StickerZombie** [comment]
I did have Xone-OSX previously installed. I don't know how to run the uninstall.command you talk about. Any hints? Thanks!

**Comment by FranticRain** [comment]
Download the latest version of the Xone-OSX driver. In the downloaded .dmg file, you will find the `uninstall.command`. Simply double click it and enter your password. It will remove the driver from your system. You may have to reboot before the controller will work properly again.

**Comment by StickerZombie** [comment]
OK, worked perfectly, now the test and binding utils are back. The problem is that now Unity has all the inputs messed up :(
Any help with that?
Thanks for all the patience :)

**Comment by FranticRain** [comment]
This driver's issues with Unity are fairly well documented in #129. You might also have the same problem as #132. Since I resolved the controller not working part of this, I'm going to close this issue. If you have any more questions about the Unity button mappings, you should probably continue the conversation on #129.
