### ISSUE TITLE
Tine/Trine 2

### ISSUE THREAD

**Issue by xdemonx** [360Controller/360Controller#177]
There are some problems in game Trine/Trine 2 since version 0.14
Version 0.13 works perfectly, but on version 0.14 and 0.15 seems like someone always press "left" on right stick.

**Comment by FranticRain** [comment]
Is it just a slight push to the left on the right stick? If so, have you tried setting a deadzone on your controller, because it may be to blame.

**Comment by FranticRain** [comment]
I just checked it out in game. You need to rebind ever character's look axis. Unfortunately, this is done in each character's specific menu. I don't know what that is.

I'll look into why these axes are currently 4 and 5 instead of 5 and 6. But remapping them should get you rolling for now.

**Comment by xdemonx** [comment]
Yes, I tried to remap, but not only a stick works wrong. Also some other buttons work incorrectly.
I tried to clear all buttons in settings and remap them. It helped, but remapping isn't comfortable.

Now I'm using driver 0.13.1 on El Capitan and it's working well.

Also, could you say where can I set a deadzone on my controller?

**Comment by FranticRain** [comment]
Closing out unfixable game specific issues.
