### ISSUE TITLE
Button Remapping is reset each time the controller is connected

### ISSUE THREAD

**Issue by lawnmowerlatte** [360Controller/360Controller#179]
Running OS X 10.10.5 and 0.15b3 and each time the controller is connected, the remapping is reset. It would be nice to save it across connections.

**Comment by FranticRain** [comment]
Using 10.11.2 and 0.15b3 on an Xbox One wired controller, remappings are saved, and are not reset. What controller are you using?

**Comment by lawnmowerlatte** [comment]
I'm using the Xbox One controller with a USB cable. It is the Master Chief version, maybe that has something to do with it?

**Comment by FranticRain** [comment]
I doubt it has anything to do with the paint job on the controller. Internally, its still the same.

**Comment by lawnmowerlatte** [comment]
Checked my console and the logs are the same as @jnicol reported in #181. Closing as a duplicate.
