### ISSUE TITLE
The Behemoth Games not working.

### ISSUE THREAD

**Issue by Zilch001** [360Controller/360Controller#187]
Every other game that I own that I have tried it on has worked except the Behemoth games. Battle block Theater and Castle Crashers, neither work. I have the .15 update for the drivers and I have OS X 10.11
Any ideas would be appreciated.

**Comment by Deph0** [comment]
Plausible that the game needs to fix their support for the controller on mac, maybe try contact them? It's usually not the drivers fault for some games not working correctly with the controller.

**Comment by FranticRain** [comment]
I just tested both an Xbox One and wireless Xbox 360 Controller with Castle Crashers. They both worked perfectly. I'm assuming the developers have fixed this issue.
