### ISSUE TITLE
Support for Xiaomi Gamepad?

### ISSUE THREAD

**Issue by Sp4rd4** [360Controller/360Controller#188]
Hi, thanks for the great work.
Is there any chances support for Xiami gamepad will be added?
Device info:
小米蓝牙手柄:
  Address:	1C-96-5A-FB-42-6B
  Major Type:	Peripheral
  Minor Type:	Peripheral
  Services:	XiaoMi Bluetooth Wireless GameController SDP Server, XiaoMi Bluetooth Wireless GameController, XiaoMi Bluetooth Wireless GameController PnP Server
  Paired:	Yes
  Configured:	Yes
  Connected:	No
  Manufacturer:	Broadcom (0x5, 0x2307)
  Firmware Version:	0x0129
  Vendor ID:	0x2717
  Product ID:	0x3144
  Class of Device:	0x05 0x02 0x0508
  Host Connectable:	No
  EDR Supported:	Yes
  eSCO Supported:	No
  SSP Supported:	Yes

Regards, Sp4rd4.

**Comment by FranticRain** [comment]
This looks like an Android gamepad, not an Xbox 360 one. I doubt we will be able to help you.
