### ISSUE TITLE
Strange Issue with Broforce on Steam

### ISSUE THREAD

**Issue by TillMatthis** [360Controller/360Controller#189]
Hi,
I'm running El Capitan with Version 0.15 Beta 3 and also tried 0.14 before.
I can map all the Buttons correctly in the setup and the controller works fine in the menu,
but in game the down D-PAD Button triggers another button (chat / enter) and makes the game unplayable. Everything else works fine. Just the down D-PAD doesn't work.
Game description says "full controller support".

Any ideas? Else just see this as a heads up. Thanks for the great work!

**Comment by Deph0** [comment]
sound like more of an game problem then driver issue, try contacting the developer about it?

**Comment by TillMatthis** [comment]
It works with a generic plug and play usb controller, that has a 360 layout, but doesn't  need a driver. 
This bug only occurs with the 360 controller, but I'll see what I can find out. Thanks.

**Comment by TyanColte** [comment]
@TillMatthis this happened to me also, i just remapped the buttons in game to what they're supposed to be and it's working fine now.

**Comment by FranticRain** [comment]
If you can remap the buttons in game, this isn't an issue with the driver.
