### ISSUE TITLE
Update the readme.md to include SIP

### ISSUE THREAD

**Issue by TyanColte** [360Controller/360Controller#191]
The readme.md needs to be updated in the signed kexts section to include instructions on how to disable System Integrity Protection (AKA. Rootless) on El Capitan by going into recovery 'CMD+R' on boot and opening the terminal and typing the following command: 'csrutil disable' and rebooting. This is the only way on El Cap to disable driver signing.

**Comment by FranticRain** [comment]
Added it, but boy that thing is due for a full rewrite.
