### ISSUE TITLE
Xbox One controller doesn't work in Counter-Strike: Global Offensive

### ISSUE THREAD

**Issue by RaymanDK** [360Controller/360Controller#195]
As the title says. The game expects a 360 controller. Reason why Microsoft on Windows made it so it pretends to be a 360 controller or shows up as one. You get the idea.

Continue with the amazing work. Really appreciate it, thank you.

**Comment by FranticRain** [comment]
Does the game work with 360 controllers on Mac? Do you have any way of testing that? I know on Windows, you need to load a config file using the console. Look into that and see if it helps.

**Comment by FranticRain** [comment]
CS:GO does work with this controller. Make sure you check your in-game controller settings.

**Comment by githubneal** [comment]
has anyone actually used it successfully on a MAC?? I haven't seen any evidence of this at all online. Not a single person.

**Comment by MaddTheSane** [comment]
You can try configuring the controller via Steam’s Big Picture Mode.
On Nov 18, 2016, at 6:59 PM, githubneal <notifications@github.com<mailto:notifications@github.com>> wrote:


has anyone actually used it successfully on a MAC?? I haven't seen any evidence of this at all online. Not a single person.
