### ISSUE TITLE
Unknown controller

### ISSUE THREAD

**Issue by andhie** [360Controller/360Controller#201]
I got a 360 controller that doesn't work with 0.15 Beta 4. Here are some details from the System Profiler

Info | Details
---------|----------
  Product ID: | 0x02a0
  Vendor ID: | 0x045e  (Microsoft Corporation)
  Version: | 1.00
  Serial Number: | 0694C614
  Speed: | Up to 12 Mb/sec
  Manufacturer: | Microsoft Corporation.
  Location ID: | 0xfa130000 / 5
  Current Available (mA):	| 1000
  Extra Operating Current (mA): | 0

**Comment by FranticRain** [comment]
Install this version of the driver and let me know if it fixes the problem. Is this the Microsoft Big Button controller? https://drive.google.com/file/d/0B5PLCKoMd4zGVmxUQlFvbXN2Z3M/view?usp=sharing

**Comment by andhie** [comment]
Tested with the given driver. it now works! thanks a lot!
i'm not too sure what do you mean by Big Button. I bought it off the internet, not too sure if its even genuine. but it looks like this. 
![360](http://compass.microsoft.com/assets/55/69/556932e3-5fb4-40e9-a868-450606fd1a8c.jpg?n=pop1.jpg)

**Comment by FranticRain** [comment]
Its definitely not genuine. Thats the product ID of the IR receiver for this thing. But I'm glad it works for you!

![](https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAb6AAAAJDNjZWQwZTQ0LTQ1YjktNGFkZS1iZTllLWIwYjFjNDE5N2E1YQ.jpg)
