### ISSUE TITLE
Xbox 360 wireless controller as MIDI controller for Logic ?

### ISSUE THREAD

**Issue by daslicht** [360Controller/360Controller#203]
Hi,
Is it possible to use the Xbox 360 wireless controller as MIDI controller for Logic ?
~Marc ?

**Comment by FranticRain** [comment]
The Xbox 360 controller returns HID data, not MIDI data. You would need to find a program capable of turning HID data into MIDI. Since this driver returns standard HID data, the program should easily support it, and this is not a problem with the driver.

**Comment by daslicht** [comment]
OK fine , do the xbox 360 Driver work under OSX 10.11.x ?

**Comment by FranticRain** [comment]
Yes, it does.
