### ISSUE TITLE
(Beta 5) Wrong DPAD mappings (both xbox one and xbox 360) + useless button

### ISSUE THREAD

**Issue by RodrigoCard** [360Controller/360Controller#212]
- There is an extra button that does nothing before the dpad button indexes, (residual from one's sync button? the sync buttons does nothing)
- This happens in both xbox 360 and xbox one controllers this time.
- The XBOX GUIDE (home?) button is 10 on xbox 360 and 11 on xbox one
- If you press any button AND home together, the useless button fires and gets stuck until you press another button.

In this pic I am holding the guide button on both controllers (I also pressed another one and released):
![pic](https://cloud.githubusercontent.com/assets/417968/12568302/eb0b6372-c3ab-11e5-9f9d-139c35510aba.png)

**Comment by FranticRain** [comment]
Oh yeah, I know what that is. Just got sloppy and forgot to get rid of the extra bit I added to the report descriptor. I'll fix it real quick.

**Comment by FranticRain** [comment]
Latest version of the release should fix this, check it out.

**Comment by FranticRain** [comment]
Going to go ahead and close this since it has been resolved.
