### ISSUE TITLE
Xbox One Pro Ex Controller support

### ISSUE THREAD

**Issue by konradzuse** [360Controller/360Controller#213]
Hi, Bought this Xbox one wired controller today, and it doesn't seem to be supported.

Product ID:	0x543a
  Vendor ID:	0x24c6
  Version:	1.01

**Comment by FranticRain** [comment]
This should solve your problem. Let me know how it works out. https://drive.google.com/file/d/0B5PLCKoMd4zGMUY4eTJSc2RUZ1E/view?usp=sharing

**Comment by konradzuse** [comment]
It works, awesome! 

Thanks
