### ISSUE TITLE
Something wrong with "Chinese Gamepad"

### ISSUE THREAD

**Issue by wuqiongYodo1** [360Controller/360Controller#214]
Many gamepads made in China are fake 360 controllers, they use Microsoft's Factory ID and Product ID to let system recognize it, But ... it's very powerful in PC(such as fake ps3 gamepad, analog gamepad or android gamepad in different mode).
  when in 360 controllers mode, it may let your diver crash on test stick or LT/RT buttons, like the test value dithering always, but in pc driver it does not like that.
This is my gamepad in Chinese website
http://www.xiaoji.com

**Comment by FranticRain** [comment]
Closing this because we do not support counterfeit controllers. Its not our job to fix someone else's fake.
