### ISSUE TITLE
No devices found: Rock Candy xbox one controller

### ISSUE THREAD

**Issue by AuroraDawn** [360Controller/360Controller#219]
When I open up the Xbox 360 controllers my device is not being found. I've done a bit of research and I'm guessing it's because of product and vendor ids or the fact that I'm using a Rock Candy controller, I could be wrong though. I've tried other drivers however they do not work either. 

My OS version: Yosemite 10.10.5
Controller: Rock Candy Wired Controller for Xbox One, product ID: 0x0346, vendor ID: 0x0e6f

**Comment by FranticRain** [comment]
This is the third VID and PID for this controller. I hate PDP so much. This should make the controller work. https://drive.google.com/file/d/0B5PLCKoMd4zGUFRwcFBHSlR6VTQ/view?usp=sharing
