### ISSUE TITLE
Not detecting Afterglow Gamepad with El Capitain 10.11.3

### ISSUE THREAD

**Issue by WizGnome** [360Controller/360Controller#228]
I installed 0.15 beta 5 and connected my controller but it was no detected.

Looking in Info.plist idVendor and idProduct were different to that shown in System Information - Product ID: 0xfafd Vendor ID: 0x24c6

I edited info.plist to change idProduct to 64253 and idVendor to 9414 but it is still not detected - did I miss something or is there another issue?

I see this in the console log:
11/02/2016 13:08:45.474 System Preferences[3063]: Failed to connect (xoneRumbleOptions) outlet from (Pref360ControlPref) to (NSPopUpButton): missing setter or instance variable
11/02/2016 13:08:45.479 System Preferences[3063]: Unable to simultaneously satisfy constraints:

    <NSLayoutConstraint:0x7f8d6be22020 H:[MyWhole360Controller:0x7f8d6be1ec80(465)]>,
    <NSLayoutConstraint:0x7f8d6be228c0 H:|-(NSSpace(20))-[MyWhole360Controller:0x7f8d6be1ec80]   (Names: '|':NSView:0x7f8d6b8df700 )>,
    <NSAutoresizingMaskLayoutConstraint:0x7f8d6bd1a260 h=-&- v=-&- H:|-(0)-[NSView:0x7f8d6b8df700]   (Names: '|':NSTabView:0x7f8d6b8dfa30 )>,
    <NSAutoresizingMaskLayoutConstraint:0x7f8d6bd1a930 h=-&- v=-&- H:[NSView:0x7f8d6b8df700]-(0)-|   (Names: '|':NSTabView:0x7f8d6b8dfa30 )>,
    <NSLayoutConstraint:0x7f8d6b8e5120 H:[NSTabView:0x7f8d6b8dfa30]-(0)-|   (Names: '|':NSView:0x7f8d6b8dfed0 )>,
    <NSLayoutConstraint:0x7f8d6b8e5170 H:|-(0)-[NSTabView:0x7f8d6b8dfa30]   (Names: '|':NSView:0x7f8d6b8dfed0 )>,
    <NSLayoutConstraint:0x7f8d6be223c0 H:[MyWhole360Controller:0x7f8d6be1ec80]-(NSSpace(8))-[NSBox:0x7f8d6be13ac0'Left Stick']>,
    <NSLayoutConstraint:0x7f8d6be16830 H:[NSBox:0x7f8d6be13ac0'Left Stick']-(NSSpace(20))-|   (Names: '|':NSView:0x7f8d6b8df700 )>,
    <NSLayoutConstraint:0x7f8d6b8f7a40 H:[NSBox:0x7f8d6be13ac0'Left Stick'(145)]>,
    <NSLayoutConstraint:0x7f8d6b88abf0 H:[NSBox:0x7f8d6b8e4790'Box']-(0)-|   (Names: '|':NSView:0x7f8d6b8dfed0 )>,
    <NSLayoutConstraint:0x7f8d6b8e3ff0 H:|-(0)-[NSBox:0x7f8d6b8e4790'Box']   (Names: '|':NSView:0x7f8d6b8dfed0 )>,
    <NSLayoutConstraint:0x7f8d6b8e3bc0 H:[NSBox:0x7f8d6b8e4790'Box'(668)]>

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7f8d6be22020 H:[MyWhole360Controller:0x7f8d6be1ec80(465)]>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.

**Comment by FranticRain** [comment]
You have to recompile and re-sign before changes to Info.plist take effect. This version of the driver should work for you: https://drive.google.com/file/d/0B5PLCKoMd4zGY19KN2NzN0pvUGc/view?usp=sharing

**Comment by WizGnome** [comment]
Thanks, but it did not work - the product and vendor id's were swapped - product id is 64253 and vendor id 9414 but in your info.plist they are swapped  :(

**Comment by FranticRain** [comment]
Whoops. I do that ever once in a while. here you go. https://drive.google.com/file/d/0B5PLCKoMd4zGQkExNU11RUNXRkk/view?usp=sharing

**Comment by WizGnome** [comment]
That fixed it - working now :)
