### ISSUE TITLE
Steam Big Picture

### ISSUE THREAD

**Issue by bmherold** [360Controller/360Controller#230]
Buttons do not map correctly. Pressing B is select/"A" and pressing X goes back/"B", just for two examples. Whatever steam expects is not what the driver is tossing out. Thanks!!

**Comment by FranticRain** [comment]
Big Picture has a binding menu in the settings. Please use it.

**Comment by bmherold** [comment]
If that was on the readme or linked under usage, that would probably help out a lot of other people. Either way, thanks, it worked perfectly!

**Comment by TyanColte** [comment]
That's odd, i don't have any problems with steam big picture with the default mappings. @bmherold make sure you have the default mappings in your driver settings pref pane.
