### ISSUE TITLE
Does not recognizes Xbox One Wireless Adapter

### ISSUE THREAD

**Issue by AashAgarwal** [360Controller/360Controller#232]
Hi,

The beta version 5, do recognizes my xbox one controller when connected through wired, but when I am trying to connect using xbox one wireless adapter for PC, it does not recognizes my adapter, and so I am not able to play wirelessly on my OS x (10.11.3). So, if you could fix it for us, it would be really appreciated. 
Thanks,

**Comment by FranticRain** [comment]
Duplicate #156 

Please check for existing issues before creating new ones.
