### ISSUE TITLE
Controller not recognized.

### ISSUE THREAD

**Issue by zero334** [360Controller/360Controller#234]
Hi, first of all great work!
I bought this wired controller, and it doesn't seem to be supported.

Vendor name: Trust
Product name: Predator

Product ID: 0x0003
Vendor ID: 0x0810
Version: 1.06

**Comment by FranticRain** [comment]
This driver is for controllers that work with Xbox consoles. I don't see any Xbox controllers from Trust. Are you sure this is an Xbox 360 or Xbox One controller?

**Comment by zero334** [comment]
Think so, you can switch between DirectInput and XInput with a switch.
It is an older controller not listed on their site.

**Comment by FranticRain** [comment]
Okay, give this a shot then: https://drive.google.com/file/d/0B5PLCKoMd4zGbHFwb25kQ0JkQ1U/view?usp=sharing

**Comment by zero334** [comment]
Works great :dancer:

**Comment by FranticRain** [comment]
Awesome.
