### ISSUE TITLE
Device not supported

### ISSUE THREAD

**Issue by Schaughwne** [360Controller/360Controller#235]
When you have time, I'd love to have support for the PowerA ProEx wired controller.

idVendor:                        0x24C6 = Xbox 3rd Party Partners
idProduct:                       0x543A

Happy to provide any additional info.

**Comment by FranticRain** [comment]
Here you go: https://drive.google.com/file/d/0B5PLCKoMd4zGaGZCNHpReUJzRFk/view?usp=sharing

Let me know how it works out.

**Comment by Schaughwne** [comment]
That did the trick, Thank you!
