### ISSUE TITLE
Where to find the ACTUAL PROGRAM.

### ISSUE THREAD

**Issue by superskyman64** [360Controller/360Controller#238]
I can't find where to actually find the program itself. Do I just connect and go, or do I have to open a program?

**Comment by FranticRain** [comment]
You download the installer from https://github.com/360Controller/360Controller/releases
After tha, you can edit settings from your System Preferences.
A driver is loaded into the operating system and is not an application that runs. Once you install it, it will keep loading into the system every time your computer starts. No need to do anything else.
