### ISSUE TITLE
Xbox One Controller Not Working with Bioshock

### ISSUE THREAD

**Issue by ryanleichty** [360Controller/360Controller#240]
Under the control settings for Bioshock (Mac app store version), the Xbox 360 controller appears greyed out and does not allow you to enable it.

The controller is recognized within the Xbox 360 windowpane within system preferences, so I'm not sure what's going on. It might be the game, not the driver.

**Comment by FranticRain** [comment]
Have you tried going into the preference pane and checking the checkbox "Pretend to be 360 controller" under the "Advanced" tab?

**Comment by ryanleichty** [comment]
Oh my gosh, you're a life saver. I thought I just wasted $60...

That worked, thank you so much!

**Comment by FranticRain** [comment]
No problem.
