### ISSUE TITLE
FantasticRain twitter

### ISSUE THREAD

**Issue by cystbear** [360Controller/360Controller#244]
I have installed this driver last night and everything works fine, thank you guys. I decided to write thanks tweet to core developers, but did not found @FranticRain's at twitter, please point me.

(thank)[https://twitter.com/1cdecoder/status/711320057285091330] (you)[https://twitter.com/1cdecoder/status/711320730223378433]

**Comment by FranticRain** [comment]
Sorry. I've been doing some rebranding lately. You can find me at: https://twitter.com/VestiglDrew

**Comment by cystbear** [comment]
:+1:
