### ISSUE TITLE
Battery Level

### ISSUE THREAD

**Issue by metatrevor** [360Controller/360Controller#245]
Is there a way to get the wireless joystick battery level as a percentage (not bars) from the preferences pane ?

**Comment by TyanColte** [comment]
I'm sure it'd be possible, but I don't know if that's something the devs would implement. Maybe as a configurable option. What do you think @FranticRain @RodrigoCard ? Seems promising.

**Comment by FranticRain** [comment]
Its theoretically possible. It looks like the controller reports 0-255 as the battery level. Thats all minor changes to the preference pane though, and I'm not the one you want to talk to about preference pane stuff.

**Comment by tomlube** [comment]
Hey FranticRain, not to be a dick but I saw you got a Wireless adapter just before the break recently. How is progress using the controller wirelessly? :)

**Comment by FranticRain** [comment]
@tomlube We have a whole thread for that: https://github.com/360Controller/360Controller/issues/156#issuecomment-207828002

**Comment by FranticRain** [comment]
Got a little prototype of this I finally put together. What do you guys think?

<img width="780" alt="screenshot 2016-08-10 14 24 32" src="https://cloud.githubusercontent.com/assets/4530595/17567750/4a7e52b0-5f06-11e6-8a3c-a5499cb9092c.png">

**Comment by RodrigoCard** [comment]
looks good :)

**Comment by FranticRain** [comment]
Just pushed this feature. Will be in the next release.
