### ISSUE TITLE
LED blinks after computer goes to sleep

### ISSUE THREAD

**Issue by fedxc** [360Controller/360Controller#248]
The LED turns off (as expected) when my iMac goes to sleep. When it wakes up, the LED on the controller starts blinking.

It doesn't resume it's function until I either, restart the computer or unplug and plug back again the controller.

Please let me know if there is any other information I can provide.

**Comment by csauve** [comment]
I have the same issue with wireless controllers. After waking up from sleep, any controller that I connect to the dongle has a blinking LED instead of showing a solid 1 of 4 LEDs. The controllers still provide input as confirmed by Controller Test.
