### ISSUE TITLE
Xbox One Controller not Working on OS X 10.11.4

### ISSUE THREAD

**Issue by wizcreations** [360Controller/360Controller#249]
I've been using this driver (release 0.15 beta 5) for an Xbox 360 controller without issues.  I attempted to use an Xbox One controller but iMac does not even recognize the controller.  Is there something I need to do to enable support for the Xbox One controller?

**Comment by FranticRain** [comment]
Can you get your controller's vendor and product ID from: Apple Button -> About This Mac -> System Report -> USB?

**Comment by wizcreations** [comment]
My computer does not recognize the XB One controller.  It does not appear in the list of USB hardware.

The 360 controller does appear (although I'd guess that is not what you're asking for).  Product ID: 0x028e.  Vendor ID: 0x045e  (Microsoft Corporation)

**Comment by FranticRain** [comment]
Find a different USB cable and connect your Xbox One controller with that. It looks like you are using a micro USB charge cable, not a data cable.

**Comment by wizcreations** [comment]
Oh man, I'm dumb!  Thanks for reminding me of that.  Works perfectly when I grab the right cable.

**Comment by FranticRain** [comment]
No problem.
