### ISSUE TITLE
Problem with The Walking Dead: Michonne

### ISSUE THREAD

**Issue by chicochaleur29** [360Controller/360Controller#254]
Hello
I have a problem witch my xbox one controler for play "The Walking Dead Michone" for mac
When i start the game, the start bouton don't work, it's the LS Click work.
In game, when i push the LS control on the left, at the screen, i go on the right....
I have this problem only this game
I tired to re-mapping the bouton of my controler, but i have still problem
I have the last upadate of your software (0.15 beta 6) and OSx 10.11.5.
Can you help me?
Thanks

**Comment by FranticRain** [comment]
In your "Xbox 360 Controller" Preference Pane, go to the "Advanced" tab and check the "Pretend to be an Xbox 360 Controller" box.

**Comment by chicochaleur29** [comment]
Yes, i have test to, but don't work... :(

**Comment by FranticRain** [comment]
Then we can't do anything for you. This is a problem with the game, not with the driver. Sorry.

**Comment by FranticRain** [comment]
Closing out unfixable game specific issues.
