### ISSUE TITLE
README.md could mention Xbox One support

### ISSUE THREAD

**Issue by calvinjuarez** [360Controller/360Controller#255]
The issues seem to indicate that the Xbox One controller is supported.  It'd be nice to have up-front, official confirmation in the README, perhaps with some mention of the intended scope of this project in supporting the Xbox One pad (e.g. is it incidental or intentional, and are issues requesting One support welcome).

**Comment by FranticRain** [comment]
Working on the README is definitely on my todo list. There's a lot to rewrite. For your own edification, its on purpose and it works pretty much perfectly in any situation in which an Xbox 360 controller works.

**Comment by FranticRain** [comment]
It's in there now!

**Comment by calvinjuarez** [comment]
Thanks!
