### ISSUE TITLE
Adding support for 3rd party clone/ripoff controller?

### ISSUE THREAD

**Issue by unclelag** [360Controller/360Controller#262]
I've got a Xiaomi Bluetooth gamepad controller, which, in all honesty, is a ripoff of the XBox360 controller. Although I can't say if it works same way, it is definitely recognised by the system and I can remap its controls with apps like Joystick Mapper. It is a pain really, so I tried to add it to the 360Controller kext with DriverTool but it still won't show up in PrefPane. I guess maybe it's because it is wireless?

Anyway, I don't want to be _that guy_, but I couldn't find any kind of forum to share my thoughts so I created this. I really want to make work and I might be able to dig in, but so far I have no idea if it's even doable. And if it is, what I can do to investigate further.

Cheers!

**Comment by FranticRain** [comment]
At this time, we only support controllers that work with Microsoft's Xbox brand of consoles. Sorry.
