### ISSUE TITLE
How to use driver?

### ISSUE THREAD

**Issue by ubernex** [360Controller/360Controller#268]
I installed the program and restarted my mac, plugged in my controller, but nothing is happening. I am incredibly stupid. Help please!

**Comment by FranticRain** [comment]
What type of controller are you using? Is it a wireless Xbox 360 controller? If you are plugging it in using a "Play and Charge Kit" cable, that only provides power. It does not turn a wireless controller into a wired one. You will still need a wireless adapter to make it work.

If it isn't that, I'm going to need your controller's product and vendor ID. You can find those in: Apple Menu -> About This Mac -> Overview Tab -> System Report... -> Hardware Section -> USB. There should be a device in there listed as "Controller". Click on it, and then vendor and product IDs should be listed there.

**Comment by ubernex** [comment]
I was trying an xbox one controller – does the driver work with it?

**Comment by FranticRain** [comment]
It does. There are a couple things you have to be careful of though. Make sure you are using a "data" USB cable. Some USB cables are only wired to charge devices. This will allow the controller to turn on, but it will not send data to the computer. If your controller is listed in that menu I mentioned, then it is connected with a "data" cable. Secondly, is this a third party controller? If so, I'm definitely going to need that vendor and product ID. Third, have you recently updated the firmware? You'll have to use a pre-release build to fix certain issues with the latest firmware on the Xbox One controller.

**Comment by ubernex** [comment]
The controller is listed in the menu, it's a controller straight from the console box with product ID 0x02dd and vendor ID 0x045e. I think I used the release firmware, which version do you recommend?

Also thanks for helping!

**Comment by FranticRain** [comment]
Try this version of the driver and let me know if it fixes the problem: https://drive.google.com/file/d/0B5PLCKoMd4zGc3lySUhiaE04S3c/view?usp=sharing

**Comment by ubernex** [comment]
What should I do once it's installed and my computer is restarted?

**Comment by FranticRain** [comment]
All you have to do is plug in the controller. That will start the controller up and then it should work in games. You can check for sure by checking the preference pane in your System Preferences.

**Comment by ubernex** [comment]
Oh awesome thank you!

**Comment by FranticRain** [comment]
Make sure to let me know if it does or doesn't work so I can close this issue.

**Comment by ubernex** [comment]
It's responding the the system preference page but not on CS:GO or Super Meat Boy

**Comment by FranticRain** [comment]
Go into the preference pane, click on the "Advanced" tab, and enable "Pretend to be an Xbox 360 controller." That should fix your problem.

**Comment by ubernex** [comment]
Still not functioning :(

**Comment by FranticRain** [comment]
Glad to hear it!
