### ISSUE TITLE
Rock Candy 360 Controller not working on mac

### ISSUE THREAD

**Issue by porldolphin** [360Controller/360Controller#274]
My mac fails to register the controller at all. I've installed the driver from tattieboogie, the 0.08 version. 
I used KextBeast to install 360controller.kext in the system -> library -> extensions, but that didn't get my computer to register it. Any thing that helps would be greatly appreciated!
Here's info that appears to be useful.
OS: Yosemite 10.10.5.
Product ID: 0x011f
Vendor ID: 0x0e6f

**Comment by FranticRain** [comment]
That 0.08 version of Tattiebogle is NOT our driver. Please download the latest version of THIS driver here: https://github.com/360Controller/360Controller/releases. If you have any trouble with the driver this repository is devoted to, feel free to ask questions. We DO NOT support old versions of other drivers.
