### ISSUE TITLE
Afterglow 360 Controller from BestBuy Not Recognized

### ISSUE THREAD

**Issue by margic** [360Controller/360Controller#276]
The Afterglow Gamepad for Xbox 360 is not recognized.

Product ID: 0xfafc
Vendor ID: 0x24c6
Manufacturer: Performance Designed Products

**Comment by margic** [comment]
Updated the config file. Hope I did that correctly.

**Comment by FranticRain** [comment]
Here you go https://drive.google.com/file/d/0B5PLCKoMd4zGLWtjb25Nd2lXejA/view?usp=sharing

**Comment by margic** [comment]
Tested the build. It worked. Thanks.
