### ISSUE TITLE
Afterglow Controller

### ISSUE THREAD

**Issue by blacklizardint** [360Controller/360Controller#278]
I see that someone has added support for the Afterglow controller.  Can you build an install package?  i just bought one of these to use on my mac.  Greatly Appreciate it.

**Comment by FranticRain** [comment]
Its in the issue that asked for it. https://drive.google.com/file/d/0B5PLCKoMd4zGLWtjb25Nd2lXejA/view?usp=sharing

**Comment by blacklizardint** [comment]
Thanks so much!!!!  It works.  Made my day.
