### ISSUE TITLE
Drifting analog

### ISSUE THREAD

**Issue by spirouzi** [360Controller/360Controller#279]
I'm using Enjoyable to remap my Xbox One joystick but when I remap the analog stick to do mouse gesture the cursor keep drifting. There's a topic about using deadzone option in this driver to control that but the topic isn't detailed. 

How to use deadzone properly?

**Comment by FranticRain** [comment]
A deadzone is a minimum value for a joystick. If the value of the joystick is less than the deadzone value, the controller will output 0. If the value is higher than the deadzone, the controller will output the location of the stick. In the preference pane, set your deadzones with the included sliders. You will have to experiment to see what works for you.
