### ISSUE TITLE
Controller not working

### ISSUE THREAD

**Issue by SirSteven2005** [360Controller/360Controller#286]
I am using a afterglow Xbox 360 controller, Product ID:0x0213,   Vendor ID:	0x0e6f

**Comment by SirSteven2005** [comment]
Afterglow Gamepad for Xbox 360:

  Product ID:	0x0213
  Vendor ID:	0x0e6f
  Version:	1.00
  Serial Number:	0693BCBB
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0x14400000 / 2
  Current Available (mA):	500
  Current Required (mA):	500
 some other stuff

**Comment by SirSteven2005** [comment]
Please help

**Comment by SirSteven2005** [comment]
It is glowing and everything but when I try to play games with it, it does not work!

**Comment by SirSteven2005** [comment]
I am trying to play Castle crashers, Terraria ,and Battle Block Theater

**Comment by SirSteven2005** [comment]
but it never works

**Comment by FranticRain** [comment]
Check the controller in the preference pane. You can find this in the Apple Menu -> System Preferences -> Xbox 360 Controllers. Can you see movements and button presses in the preference pane?

**Comment by SirSteven2005** [comment]
yeah
i can

**Comment by SirSteven2005** [comment]
yes

**Comment by FranticRain** [comment]
Well, that means that the controller is working. We cannot fix issues with games, you have to discuss that with the developer of the game. Terraria doesn't support controllers on Mac. For games made by "The Behemoth" such as Castle Crashers and Battleblock Theater, check this steam forum thread for support: https://steamcommunity.com/app/238460/discussions/1/523890046864680624/

**Comment by FranticRain** [comment]
Duplicate of #187

**Comment by SirSteven2005** [comment]
but i don't see the preference pane area this is what i see [
![screen shot 2016-05-30 at 1 37 37 pm](https://cloud.githubusercontent.com/assets/19655098/15658221/9f155182-266e-11e6-9f60-af24c32f672e.png)
](url)

**Comment by SirSteven2005** [comment]
by the way it is not just three games it is everysingle game I own on steam

**Comment by SirSteven2005** [comment]
and Terraria does support controllers with mac due to the 1.3.1 update

**Comment by FranticRain** [comment]
If you see the movements in the preference pane, which is what that screenshot is, the driver is working. One easy way to test the driver outside of that is to open "Steam Big Picture." Once Big Picture is open, navigate to the settings and set up your controller. Then it should work to navigate Big Picture. This will prove that the driver is working properly. Once again, we CANNOT fix issues with games. You have to work that out yourself.
