### ISSUE TITLE
Driver works but games do not

### ISSUE THREAD

**Issue by krp312** [360Controller/360Controller#295]
Hello,

Using 360 wireless controllers with the USB dongle. Controllers connect successfully and I can even see the buttons light up when I press them when viewing the PrefPane. But I can't get it to work with games like Samurai Gunn, or SNES emulators.

Thoughts?

Thanks,
Kris

**Comment by FranticRain** [comment]
Unfortunately, not all games on OS X support controllers like they do on Windows. It looks like Samuri Gunn does not support controllers properly on OS X. You will need to use a tool to map controller inputs to keyboard buttons, such as Joystick Mapper or Enjoyable. As for the SNES emulator, I can't say for certain, but it is likely to have the same problem. If you are looking for a good set of emulators with impeccable controller support, I would highly recommend OpenEMU. It has a fantastic front end and works very well.

**Comment by krp312** [comment]
Thanks very much!

**Comment by krp312** [comment]
So after thinking about it, it seems that I'd favor running everything on Windows. I was wondering if you had any recommendations on virtualization software, and an all-in-one emulator for Windows, because OpenEMU is rad and I had never heard of it.

**Comment by FranticRain** [comment]
Unfortunately, there isn't anything as cool as OpenEMU for Windows. Its a real shame. You'll just have to download individual emulators on Windows. Other than that, I don't virtualize anything. I've got a good PC that I do most Windows work on, and if I need OS X, my Macbook is good enough for the job.
