### ISSUE TITLE
Rock Candy 360 controller not detected

### ISSUE THREAD

**Issue by cantillon1** [360Controller/360Controller#301]
Sorry for **yet another** Rock Candy related issue, but the wired 360 controller I have isn't detected, presumably because the productID/vendorID combination aren't defined. The values I have are: 

productID = 64254 (0xfafe)
vendorID = 9414 (0x24c6)

**Comment by FranticRain** [comment]
I'm pretty certain PDP just throws random VIDs and PIDs on their controllers at this point just to mess with me. Don't worry about it though, this should fix you up: https://drive.google.com/file/d/0B5PLCKoMd4zGQkQyU180aXJaUFE/view?usp=sharing
