### ISSUE TITLE
HORI PAD EX2 TURBO does not connect

### ISSUE THREAD

**Issue by supersayin** [360Controller/360Controller#304]
Hello, 

Can you please help with this controller?

 Product ID:	0x5500
 Vendor ID:	0x24c6

Thank you!

**Comment by FranticRain** [comment]
Here you go: https://drive.google.com/file/d/0B5PLCKoMd4zGbWlUSFd4MmtYWDA/view?usp=sharing

**Comment by supersayin** [comment]
It works like a charm!! I really appreciate it!!

THANK YOU!! THANK YOU!! THANK YOU!! THANK YOU!!
