### ISSUE TITLE
'Normalize' checkbox does not remain selected once system preferences pane is closed. 

### ISSUE THREAD

**Issue by rowanfeely** [360Controller/360Controller#305]
running El Capitan 10.11.5 and version 0.16, using wired xbox one controller.

All other options (invert x+y, deadzone selection, etc) will save, only normalize will uncheck once pane is closed.

**Comment by FranticRain** [comment]
I just added a fix for this in the latest release, 0.16.1. Check it out and make sure it works for you too. You can grab it here: https://github.com/360Controller/360Controller/releases/tag/v0.16.1
