### ISSUE TITLE
MadCatz Micro CTRL

### ISSUE THREAD

**Issue by bookatechie** [360Controller/360Controller#308]
Software is not seeing the controller.
It is connected by BlueTooth.
Vendor ID: 0x0738
Product ID: 0x5262
Firmware Version: 0x0109

Please help in getting this to work.

**Comment by FranticRain** [comment]
This driver is only for controllers that work with Microsoft's Xbox brand of consoles. This controller is not compatible with those consoles and therefore not compatible with our driver. Sorry.
