### ISSUE TITLE
Afterglow wired controller for Xbox 360 not found

### ISSUE THREAD

**Issue by Dovahkiin90** [360Controller/360Controller#314]
I installed the latest release package but El Capitan 10.11.5 doesn't find my Afterglow wired controller for Xbox 360.

Prod id: 0x0301
Vendor id: 0x12ab
Version: 1.02

**Comment by FranticRain** [comment]
Here you go: https://drive.google.com/file/d/0B5PLCKoMd4zGS0E1TEJWRGV0MnM/view?usp=sharing
