### ISSUE TITLE
New device: Madcatz Arcade fightstick TES+

### ISSUE THREAD

**Issue by LunatickDuck** [360Controller/360Controller#318]
So apparently this device isn't recognized, it flashes for 1 second on connection, then stop, the drivers says "no device found"...
About the device:
idProduct: 61506 (0xf042)
idVendor: 7085 (0x1bad)
Version: 4.90
I have the latest release with OsX El Capitan.
The device is made to work with XBox 360, not One.

I searched in the Info.plist and indeed the device isn't there, it should work just like the existing Madcatz TE2, line 1074 of Info.plist

**Comment by FranticRain** [comment]
Here you go: https://drive.google.com/file/d/0B5PLCKoMd4zGV0t0T29pRy02OWs/view?usp=sharing
