### ISSUE TITLE
Controller not recognized 

### ISSUE THREAD

**Issue by w1der** [360Controller/360Controller#320]
I am on 10.11.6 using the original xbox360 controller, the one that is wireless, with built in charger, connected to the iMac with the USB cable that is used to charge the batteries. 

This wont be recognized within the control panel for this "app". 
I did get a "prompt" when I first connected it (I can not remember what it said). 

Am i missing something ... did some one else try this type of controller and get it to work?

**Comment by FranticRain** [comment]
This doesn't work.

https://github.com/360Controller/360Controller#wireless-xbox-360-controllers

**Comment by w1der** [comment]
OK ... thank you for clearing that out swiftly for me ... :)
