### ISSUE TITLE
MadCatz 360 controller working but with non-standard mappings

### ISSUE THREAD

**Issue by chrismylingo** [360Controller/360Controller#330]
I am using version 0.16.3 (latest) on El Capitan (10.11.5) and all input is coming in and appears correct on Controller Test, but I'm comparing to the W3C standard and it does not match up: https://www.w3.org/TR/gamepad/#remapping
Buttons 0-5 comply with the standard, but after that they do not.  Triggers show up as axes instead of analog buttons.  Select and Start are swapped.  All other buttons (stick buttons, D-pad, Home) do not match the standard.  I expect various software to assume this standard, including a program that I am currently working on, so it would be great to have this mapping corrected.

**Comment by FranticRain** [comment]
Not going to happen. The mapping is the way it is, and if we change it, we will break countless games that have previously been supported. We will not change this driver to match some new standard.
