### ISSUE TITLE
New Wireless(Bluetooth) Xbox One Controller

### ISSUE THREAD

**Issue by xXH4tchXx** [360Controller/360Controller#331]
Could you look into checking bluetooth connections as well in order to find active controllers? Currently it will connect to the computer but, some buttons do not work. The driver doesn't see it at all and I believe that is part of the problem. 

Thank you in advance for looking into this when you get a chance.

**Comment by MaddTheSane** [comment]
We are looking into it: #291

**Comment by xXH4tchXx** [comment]
Awesome. Thank you!
