### ISSUE TITLE
PowerA Wired Controller not working or being recognized. Product ID: 0x5397 Vendor ID:0x24c6

### ISSUE THREAD

**Issue by siracu55** [360Controller/360Controller#335]

**Comment by FranticRain** [comment]
Duplicate #312

**Comment by FranticRain** [comment]
Is this an Xbox One or Xbox 360 controller? Also, what is the official name of this controller?

**Comment by siracu55** [comment]
This is an Xbox 360 wired controller. The official name is PowerA FUS1ON Tournament Controller.

**Comment by FranticRain** [comment]
Okay sorry. I misinterpreted this based on the old name of this issue, and then realized it later. This should fix your problem: https://drive.google.com/file/d/0B5PLCKoMd4zGaGF1Y0NVSEtCMnc/view?usp=sharing

**Comment by siracu55** [comment]
That worked! Thanks a ton! Now to just figure out how to get Dolphin to recognize it...

**Comment by FranticRain** [comment]
This might be of help: http://wpguru.co.uk/2016/01/how-to-connect-your-xbox-360-controller-to-dolphin-for-mac/

**Comment by siracu55** [comment]
I'm all set. Thanks again for your help.
