### ISSUE TITLE
Thrustmaster Ferrari 458 Racing Wheel

### ISSUE THREAD

**Issue by yency01** [360Controller/360Controller#336]
Hello,
first of all, thanks for the great work on this controller.

The issue comes with my new controller, which is recognized by your driver, but not in the game, F1 2013 and DIRT3.
Controller Thrustmaster Ferrari 458 Racing Wheel for XBox360
ProductID 0x5600
VendorID 0x24c6
Version 1.01

All possible options already tried ... any ideas?

BTW, original XBox360 gamepad works

Thanks

**Comment by FranticRain** [comment]
I just hacked this together and have ABSOLUTELY no way to test it whatsoever, so who knows what will happen. But I've modified the "Pretend to be an Xbox 360 Controller" checkbox in the "Advanced" tab to work with Xbox 360 controllers. Basically, your wheel should pretend to be Microsoft Xbox 360 controller when that checkbox is activated. Hopefully this will work and I didn't forget anything critical. https://drive.google.com/file/d/0B5PLCKoMd4zGQnB2V3M5MXN3N2M/view?usp=sharing

**Comment by yency01** [comment]
Hi Drew ... great job and so fast ... it works perfectly now, thanks a lot ...

 

Greetings, Jens

 

 

Von: Drew Mills <notifications@github.com>
Antworten an: 360Controller/360Controller <reply@reply.github.com>
Datum: Dienstag, 9. August 2016 um 16:31
An: 360Controller/360Controller <360Controller@noreply.github.com>
Cc: Jens <jens.bergold@icloud.com>, Author <author@noreply.github.com>
Betreff: Re: [360Controller/360Controller] Thrustmaster Ferrari 458 Racing Wheel (#336)

 

I just hacked this together and have ABSOLUTELY no way to test it whatsoever, so who knows what will happen. But I've modified the "Pretend to be an Xbox 360 Controller" checkbox in the "Advanced" tab to work with Xbox 360 controllers. Basically, your wheel should pretend to be Microsoft Xbox 360 controller when that checkbox is activated. Hopefully this will work and I didn't forget anything critical. https://drive.google.com/file/d/0B5PLCKoMd4zGQnB2V3M5MXN3N2M/view?usp=sharing

**Comment by FranticRain** [comment]
Glad to hear it.

**Comment by jimbobgaming** [comment]
I need this file but it's now gone :(

**Comment by Daitcher** [comment]
yep a reupload of the file would be great if possible @FranticRain
