### ISSUE TITLE
Horipad Xbox One Controller no longer works...

### ISSUE THREAD

**Issue by creativexp** [360Controller/360Controller#348]
Hi,

I have been using this driver along with this library https://github.com/ThemsAllTook/libstem_gamepad to use my horipad xbox one controller on mac. Everything worked fine.

Just recently the controller no longer works. I was using v0.15 beta 4 i think. I have Yosemite 10.10.5. The controller is recognised in the system preferences but not in the program that i use it in.

I have tried using 0.16.4(thumb sticks don't work in system preferences), 0.16.2 and 0.16.1(thumb sticks don't work in system preferences) but no luck.

Anything i could try? I read somewhere that Apple had changed their USB code, could that be it?

**Comment by FranticRain** [comment]
The changes in the USB code only apply to macOS 10.11 and later. You should be fine.

If the controller works in the system preferences, and you can see button presses there, it is a bug with the program you are using, not with this driver. For better compatibility, try checking the "Pretend to be a 360 Controller" option in the advanced tab of the preference pane.
