### ISSUE TITLE
Support for MK Klassic Fight Stick Xbox 360

### ISSUE THREAD

**Issue by trigun539** [360Controller/360Controller#349]
MK Klassic Fight Stick Xbox 360:

  Product ID:	0x0303
  Vendor ID:	0x12ab  (Honey Bee Electronic International Ltd.)
  Version:	1.00
  Serial Number:	94E15B4
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0x14200000 / 5
  Current Available (mA):	1000
  Extra Operating Current (mA):	0

**Comment by FranticRain** [comment]
Here you go: https://drive.google.com/file/d/0B5PLCKoMd4zGRjZIWEpXTkJoUVk/view?usp=sharing

**Comment by trigun539** [comment]
Works great, thanks!
