### ISSUE TITLE
Games run slow after driver installation 

### ISSUE THREAD

**Issue by RammiZayn** [360Controller/360Controller#355]
Since installing the driver and trying to use an afterglow xbox 3rd party controller (which the driver recognises), now when i launch some games, they run super slow with or without the controller plugged in. Was really hoping that I'd be able to use the controller with some of the games from steam, however now i can't play games neither with nor without the controller due to the lagginess, which wasn't an issue before.

**Comment by FranticRain** [comment]
If the driver is causing you performance problems, uninstall it. The cycle count this driver adds is monumentally negligible compared to the cycle counts required to run a video game.
