### ISSUE TITLE
[Third Party Controller] Razer, stick L+R dysfunction

### ISSUE THREAD

**Issue by SaumonFume** [360Controller/360Controller#364]
Hi,
I have a gamepad razer ONZA XBOX 360 : 
- Product id: 0xfd01 
- Vendor ID: 0x1689 
- Version: 1.24

And I have some issues with left and right sticks:
- Left: up and left axis do not work
- Right: stick are blocked on the bottom axis

(These problems are observed in the preference panel XBOX360Controller but also in games [Steam > SpeedRunner and RocketLeague])

Others buttons function well.  

Thanks,
(i've an imac late 2012 with X.11.6)

**Comment by FranticRain** [comment]
Sorry, we can't fix controller specific issues. If a controller doesn't follow the protocol, we can't fix it.
