### ISSUE TITLE
Xbox One Bluetooth Controller Issues

### ISSUE THREAD

**Issue by ccfman2004** [360Controller/360Controller#367]
I know it says that the Xbox One Controllers with Bluetooth work by default without this driver.  I have to say they don't.  Buttons and sticks are not mapped correctly at all.  Ex: A Button doesn't behave as A it behaves as RT.  With the Right Stick, the Axis are all wrong.  Up and down go left and right instead and the Left Stick does nothing.

All works as is via USB.

**Comment by FranticRain** [comment]
Mapping issues are not issues with the driver, they are game specific. Especially for a controller that we don't even control from the driver. Even if we did add a driver for this controller, it would not solve binding issues. Binding issues are game specific and not an issue with this driver.
