### ISSUE TITLE
Logitech Drive Fx steering wheel

### ISSUE THREAD

**Issue by mgoras** [360Controller/360Controller#371]
Hello
I know that the topic is for almost archaic equipment, but...
I have a steering wheel from Logitech, Drive FX model
Unfortunately, the driver does not detect the device at all. Is there any chance that the steering will work with my computer? (imac mid 2011)
btw. I know that Logitech has released the driver to this steering wheel, but on  PC.

DriveFX Racing Wheel:

  Product ID:	0xcaa3
  Vendor ID:	0x046d  (Logitech Inc.)
  Version:	22.31
  Serial Number:	7676167
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Logitech Corporation
  Location ID:	0xfd141000 / 7
  Current Available (mA):	500
  Current Required (mA):	Unknown (Device has not been configured)
  Extra Operating Current (mA):	400

**Comment by FranticRain** [comment]
Does this solve your problem? https://drive.google.com/file/d/0B5PLCKoMd4zGblczQnZOMFpJV2M/view?usp=sharing

**Comment by mgoras** [comment]
Yes, 
I do not know what to say, Thank You

**Comment by daberghini** [comment]
Does anyone have the file for pc?

**Comment by Kayum72** [comment]
Can someone send the link to the file for Mac
