### ISSUE TITLE
Rock band 1 drums not recognized 

### ISSUE THREAD

**Issue by oneally** [360Controller/360Controller#374]
Hey all,

After searching for a solution for what seemed like days i'm thankful i found this driver update! Thanks so much!

I just installed the latest build 16.4 and everything went well with the installation. The preference pane see's the drum kit, But as an xbox 360 controller not the harmonix drum kit previously in the much older build. When i try to click on the dropdown menu to see if its there nothing happens. I'm trying to use the drum kit as a midi controller with gamepad companion in ableton. The system does recognize the device and here is the info. This is 1st version of rockband drum kit wired usb. 

OSX Yosemite10.10.5

Harmonix Drum Kit for Xbox 360:

  Product ID:   0x0003
  Vendor ID:    0x1bad
  Version:  1.02
  Serial Number:    00193F3C
  Speed:    Up to 12 Mb/sec
  Manufacturer: Harmonix Music
  Location ID:  0xfa131000 / 7
  Current Available (mA):   500
  Current Required (mA):    500

**Comment by RodrigoCard** [comment]
Did you close this issue accidentally? Or did you still want this to be added?

**Comment by oneally** [comment]
Hi Rodrigo,

I found a workaround, But if there is a current fix that would be great! Thanks for the quick reply!

**Comment by FranticRain** [comment]
This isn't a new device. It is in the plist with the key "RockBandDrums"

**Comment by RodrigoCard** [comment]
Oh, sorry about that

**Comment by rwreay** [comment]
@oneally, what's your workaround? I'm apparently having a simliar issue and would like to know what you did.
