### ISSUE TITLE
Nice work everyone

### ISSUE THREAD

**Issue by Pysis868** [360Controller/360Controller#376]
Was just reviewing the README and thought that was pretty well laid out.  Didn't think my controller would ever work on a Mac, but found the more applicable Google search results were the older ones at first, that didn't work.  Then I found this one and had great success!

**Comment by FranticRain** [comment]
Thank you for reading the README. I do my best to keep that thing up to date, but the number of issues that we get that could have been solved by reading the README is astounding.
