### ISSUE TITLE
No Devices Found

### ISSUE THREAD

**Issue by rlyons21** [360Controller/360Controller#378]
![screen shot 2016-11-01 at 1 41 58 pm](https://cloud.githubusercontent.com/assets/19532771/19902559/48200c9c-a039-11e6-8e3e-6cd25b6b27d1.png)

**Comment by FranticRain** [comment]
This should work with your controller: https://drive.google.com/file/d/0B5PLCKoMd4zGME1TMGRxbmFDcEE/view?usp=sharing
