### ISSUE TITLE
XBOX ONE Wireless connect through bluetooth not found

### ISSUE THREAD

**Issue by xg-wang** [360Controller/360Controller#379]
I can connect my xbox one controller through USB, but it couldn't be found if paired with bluetooth.
It seemed the controller would be recognized as a sound device. Just wonder how can I connect using bluetooth?

**Comment by MaddTheSane** [comment]
As it stands, the Bluetooth One controller does not show up in System Preferences (if connected via Bluetooth), but should still be usable by the system (sans vibration).
On Nov 5, 2016, at 1:45 PM, Xingan Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


I can connect my xbox one controller through USB, but it couldn't be found if paired with bluetooth.
It seemed the controller would be recognized as a sound device. Just wonder how can I connect using bluetooth?

**Comment by xg-wang** [comment]
It is game specific issue. It is weird that FEZ recognize my previous controller but could not the XBOX ONE controller.
