### ISSUE TITLE
Enable Driver Toggle bug

### ISSUE THREAD

**Issue by BrianMcElwain** [360Controller/360Controller#383]
XBox 360 Controller Driver
Version 0.16.4
 
OSX Sierra 10.12.1

Macbook Pro Retina 13" 2015

It seems that clicking the toggle to enable the driver asks for my OSX system password, but appears to toggle on/of anyway even if I simply cancel the authentication prompt without typing any password. Typing this out, I realised I should check if the also still controller enables/disables according to this toggle as such, but I am not on that machine right now anyway.

**Comment by FranticRain** [comment]
From what I know, its hard to tell if the applescript that disables the driver knows if it has completed successfully or not. Definitely something someone should look into at some point.

**Comment by BrianMcElwain** [comment]
Ah I have since sold my MacBookPro so I must abscond on this end.

**Comment by FranticRain** [comment]
This should be fixed in alpha 4.
