### ISSUE TITLE
3rd party controller not being powered

### ISSUE THREAD

**Issue by Robotex** [360Controller/360Controller#384]
I'm not sure if it's related to other already posted issues
I just got a 360 compatible wired gamepad that works fine on Windows 10.
On OSX El Capitan the controller once plugged appears in the dropdown list but the led on the device is not lit and no input is detected.
```
Controller:

  ID prodotto:	0x028e
  ID fornitore:	0x045e  (Microsoft Corporation)
  Versione:	1.10
  Velocità:	Fino a 12 Mb/sec
  Produttore:	SHANWAN
  ID posizione:	0x14200000 / 13
  Corrente disponibile (mA):	1000
  Corrente necessaria (mA):	500
  Operazione extra della corrente (mA):	0
```

**Comment by FranticRain** [comment]
That is a counterfeit controller. It is using the VID and PID of the official Xbox 360 controller. If it doesn't work automatically, then we won't support it because there is nothing further we can do.
