### ISSUE TITLE
How to increase controller sensitivity?

### ISSUE THREAD

**Issue by nimblebejack** [360Controller/360Controller#387]
I have been having trouble using the xbox controller with an emulator I've been using. It seems that when I push the stick to "right" and "left" it doesn't register it as going as far as when I push the stick "up" and "down". I was wondering if there was a way to increase the x axis sensitivity on the controller. Is this a problem with the 360Controller driver or the emulator I am using?

**Comment by FranticRain** [comment]
This is an issue related to the emulator you are using. The driver provides a value directly from the controller to the game. We do not impact "sensitivity" in any way. In fact, sensitivity is a concept exclusive to the program itself. Every program implements its own joystick curve that results in the "feel" of each game. If I may recommend an emulator, [OpenEmu](http://openemu.org/) is an excellent package with a great GUI frontend that provides an incredibly large variety of emulators that you can use.
