### ISSUE TITLE
360 controller

### ISSUE THREAD

**Issue by Dje1980** [360Controller/360Controller#388]
Hi, 
I have a PDP xbox one wired controller and I'm not able to use it because you're driver doesn't recognize it. I don't see it in the preference pane xbox 360 controllers, said no devices found. 
Product ID:	0x0162
  Vendor ID:	0x0e6f
Can you help me please?
Thanks for your time.

**Comment by FranticRain** [comment]
This build includes this controller. Please aware of the existing issues with third party Xbox One controllers, especially those from PDP. #333 #325 #312 #300

https://drive.google.com/file/d/0B5PLCKoMd4zGRmFaMVVjaVNOQ2s/view?usp=sharing
