### ISSUE TITLE
Signing into xcconfig

### ISSUE THREAD

**Issue by zaius** [360Controller/360Controller#39]
Maybe a nitpick, but are you open to the idea of using a DeveloperSettings.xcconfig which is added to .gitignore (as described here: http://stackoverflow.com/a/333177/114132) to store the `CODE_SIGN_IDENTITY` variable?

It would make my working tree a bit cleaner, and would also help with initial error messages for people trying to build.

**Comment by FranticRain** [comment]
Implemented in latest release and documented in the README.
