### ISSUE TITLE
Readme's Description of Wireless Xbox One Controller is confusing

### ISSUE THREAD

**Issue by nkronlage** [360Controller/360Controller#391]
Last month I tried to find a way to use my Xbox One controller with my mac and lots of websites pointed me to this project.  But the description said:

    Xbox 360 controllers work both wired and wirelessly, while Xbox One controllers
    only work wired for now. 

and

    Wireless Xbox One Controllers

    Wireless Xbox One controllers are currently not supported. Please be patient as 
    we figure out this complicated protocol.

And given this comment about the Xbox 360 controller:

    Plugging a "Play and Charge" kit into a wireless controller does not make it a wired controller.

I thought I would need a controller with a wire built in.  But it turns out the wireless controller with the USB cable connected works great! 

It would be nice if that was clearer in the description that the wireless controllers work as long as you connect them via USB.  It's a great project and I just was turned away from using it because it didn't sound like it worked with my controller.

**Comment by juriostegui** [comment]
have the same problem, it only works with usb cable. I'm not a developer but I can help with something here.
