### ISSUE TITLE
Xon-OSX

### ISSUE THREAD

**Issue by Oddworld7** [360Controller/360Controller#396]
Hi, i'm using the old xbox one driver but, it works fine with Mac OS Sierra, the thing is that i have two xbox controllers one i recently use with the xbox and the other one that i haven't played with it for a while, the one i haven't played with connects fine oto my mac and i can play with it, the other one desn't is there a way to reset the controller from the xbox set up or bluetooth setup just to make it able to use in the mac?

**Comment by FranticRain** [comment]
Xone-OSX is deprecated. It is not supported. Do not ask questions about it here. Use 360Controller.

**Comment by Oddworld7** [comment]
Ok, but i'm not going to use something it half works in Sierra for something already works fine, the question was about the xbox controller after all, but thanks, and thanks for both of the driver.
(Sorry if i sound a bit rude).
