### ISSUE TITLE
Xbox One S Bluetooth Driver For headphone jack and rumble support?

### ISSUE THREAD

**Issue by Cruplezone** [360Controller/360Controller#397]
Will either of these features ever be implemented into this driver? I think i read no for headphone jack which made me pretty sad since I play far away from my macbook hooked up to my tv to plug earbuds into my mac, but what what about rumble?

**Comment by FranticRain** [comment]
There is no intention to implement bluetooth audio at this time. Rumble capability is currently under development in #291
