### ISSUE TITLE
Still not recognized xbox 1 wired controller

### ISSUE THREAD

**Issue by cpaling** [360Controller/360Controller#398]
PDP Camo Wired Controller for Xbox One:

  Product ID:	0x0161
  Vendor ID:	0x0e6f
  Version:	4.60
  Serial Number:	000002C5AD7FDDE4
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0xfd130000 / 4
  Current Available (mA):	500
  Extra Operating Current (mA):	0

I've tried a couple drivers from other topics and maybe I haven't tried the right one or this is a newer controller that isn't supported? Help please?

**Comment by FranticRain** [comment]
This controller hadn't been added yet. Now it has been: https://drive.google.com/file/d/0B5PLCKoMd4zGc3ExOGUxS0RScXc/view?usp=sharing
