### ISSUE TITLE
Thumbstick movement not working on Xbox One Wired Controller

### ISSUE THREAD

**Issue by creativexp** [360Controller/360Controller#399]
Hi,

Thumbstick movement not working using Xbox One Wired Controller with 0.16, 0.16.1, 0.16.2, 0.16.3 or 0.16.4. Using OSX 10.12 Sierra.
Thumbstick buttons are working though (meaning pressing down on the thumbstick)

Anyone else had this problem? Any fix?

**Comment by FranticRain** [comment]
Do you see this issue in just games? Or do you also see it in the preference pane associated with this driver?
