### ISSUE TITLE
Xbox 360 (Wired) On El Capitan 10.11.6 Not Recognized in System Preferences

### ISSUE THREAD

**Issue by Albatross4** [360Controller/360Controller#400]
Xbox 360 (Wired) On El Capitan 10.11.6 Not Recognized in System Preferences

To be honest, not sure how to provide better/more detailed info, happy to do so with instructions.

**Comment by FranticRain** [comment]
[Please read the README, specifically the section that says "My Controller Doesn't Work!](https://github.com/360Controller/360Controller#my-controller-doesnt-work) and provide your product ID and vendor ID as specified there.
