### ISSUE TITLE
Xbox One Controller turns on XBox when unplugged

### ISSUE THREAD

**Issue by ghost** [360Controller/360Controller#402]
Whenever I unplug from my iMac to put the controller away it searches and turns on the local XBox. Any way to prevent this without using my XBox in energy saving mode?

**Comment by TrizzaElemental** [comment]
Found a solution by taking out the battery pack I had in it. Easiest solution.

**Comment by FranticRain** [comment]
Yes. We always recommend that you remove your battery pack when using the controller wired. This helps reduce extra cycles and strain on your battery. When you disconnect the controller and it enters a wireless pairing mode, that is just basic functionality of the controller and there isn't anything we can do about that. It happens on Windows too.
