### ISSUE TITLE
Unrecognized Xbox One Controller

### ISSUE THREAD

**Issue by EliasAthey** [360Controller/360Controller#404]
Xbox ONE liquid metal controller:

Product ID: 0x543a
Vendor ID: 0x24c6
Version: 1.01
Serial Number: 0000000000000000
Speed: Up to 12 Mb/sec
Manufacturer: PowerA
Location ID: 0x14200000 / 2
Current Available (mA): 1000
Current Required (mA): 500
Extra Operating Current (mA): 0

**Comment by FranticRain** [comment]
Sorry, but this device is already added to the Info.plist. Unfortunately, macOS has an incompatibility with PDP and PowerA controllers that cause these devices to never appear to the driver. There have been some reports that a firmware update for the controller can solve the problem, but there is nothing we can do on the driver end, sorry.
