### ISSUE TITLE
Gamesir G4s thumbsticks wobble

### ISSUE THREAD

**Issue by jerdionda** [360Controller/360Controller#405]
I am using a Gamesir G4s controller that essentially acts as a xbox 360 controller. It comes with a 2.4 GHz USB dungle. The latest driver 0.16.4 recognizes the controller as a wired XBOX 360 one. All the buttons seem to work perfectly except for both sticks. When I moved them, it shows that the sticks don't settle and seem to wobble. When I play games the sticks work, but they are a little bit unresponsive and I think its due to the wobbling. All the other buttons seem to be working fine including the rumbling. Let me know if there is something I can do to fix it. 

Here is a link to the controller website: https://www.gamesir.hk/?p=1&a=view&r=10

I am new to github, so I apologize for any mistakes I make.

Best,
Catherine

**Comment by FranticRain** [comment]
Unfortunately, there is nothing we can do about this. We simply transmit the data that we receive. If the sticks wobble, that's just the data we are getting from the controller. Additionally, we don't support devices that don't work with a Xbox-series game console. If you got this to work, congratulations, but we don't support this kind of device, sorry.
