### ISSUE TITLE
Pretend to be an Xbox 360 Controller Option - Not Saving

### ISSUE THREAD

**Issue by grpace** [360Controller/360Controller#406]
I am using an Xbox One S controller via USB and each time I plug it in I have to reselect "Pretend to be an Xbox 360 Controller" from settings. Other than that it works great!

Would love it it if I could get it to detect this controller from Bluetooth.

**Comment by PizzaPino** [comment]
same issue

**Comment by aguynamedryan** [comment]
First off, thanks for this awesome project!

Same issue that "Pretend to be an Xbox 360 Controller" does not save with a wired POWER A - Mini Controller for Microsoft Xbox One under Mac OS X 10.11.6

**Comment by FranticRain** [comment]
This is the same issue as #451 and #280. There was supposed to be a fix for this, but it was never submitted. If someone could look into this further, that'd be fantastic.

**Comment by FranticRain** [comment]
Settings bugs should be fixed in the latest release.
