### ISSUE TITLE
Xbox One Fusion Pro Controller support

### ISSUE THREAD

**Issue by nandogip** [360Controller/360Controller#407]
FAQ said for me to drop the ID's in here to possibly get support:

 Product ID:	0x551a
 Vendor ID:	0x24c6

**Comment by jhnsntmthy** [comment]
Ditto on this but the non-pro version

Controller:

  Product ID:	0x561a
  Vendor ID:	0x24c6
  Version:	1.01
  Serial Number:	0000E39A7CED558E
  Speed:	Up to 12 Mb/sec
  Manufacturer:	PowerA
  Location ID:	0x14610000 / 12
  Current Available (mA):	500
  Extra Operating Current (mA):	0

**Comment by FranticRain** [comment]
I've added both of these devices to the Info.plist. They will be added in an update in the next few days.
