### ISSUE TITLE
Wired Xbox 360 Controller ot Recognized

### ISSUE THREAD

**Issue by dahadaller** [360Controller/360Controller#410]
Product ID:	0x0213
  Vendor ID:	0x0e6f

  So my wired afterglow controller for xbox 360 worked in the driver pane yesterday, but today it's not being recognized at all. I tried reinstalling and uninstalling the driver, but that doesn't seem to work. 

The weird thing is, if I restart the computer (with the driver already installed), the controller will work (in the preferences pane) for a couple of minutes after my mac has started up, but then it just stops working after a period of time.

**Comment by Vasir1** [comment]
Have you had any luck? My device has the same product ID and vendor ID as you. Bump?

**Comment by dahadaller** [comment]
no I haven't had any luck :( still won't work

**Comment by FranticRain** [comment]
This device has already been added to the device list. If it does not currently work with the latest release, then this is another example of the issues PDP controllers have with macOS. We do not see these controllers from the driver, therefore we can do nothing to resolve issues with these controllers. It is unfortunately a bug with macOS and there is nothing we can do to solve it. Sorry.

**Comment by dahadaller** [comment]
Ok thank's for the heads up :)
