### ISSUE TITLE
Xbox one controller not working 

### ISSUE THREAD

**Issue by notwithabang** [360Controller/360Controller#414]
I Have El Capitan 10.11.6. Here is info from system preferences:

Product ID:	0x8289
  Vendor ID:	0x05ac  (Apple Inc.)
  Version:	1.18
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Apple Inc.
  Location ID:	0x14330000 / 6
  Current Available (mA):	1000
  Current Required (mA):	0
  Extra Operating Current (mA):	0
  Built-In:	Yes

Can't turn controller on, light will flash for a bit then turn off. Says 'No Devices Found' in system preferences. I have tried 2 different versions of the xbox one controller. Help please?

**Comment by dominiquecharlebois** [comment]
I'm having the same issue.

**Comment by FranticRain** [comment]
Apple doesn't make an Xbox One controller. This is the VID/PID combination of your Bluetooth USB Host Controller on your Mac. If the device does not appear in your system report, try using a different micro USB cable and try again. If you do manage to find the correct vendor and product IDs, create a new issue.
