### ISSUE TITLE
Controller not supported

### ISSUE THREAD

**Issue by Zoeoeh** [360Controller/360Controller#419]
Running El Capitan 10.11.6
Driver installed, controller shows up as connected but no response in Controller test window. Light is on as if were connected.

  Product ID:	0x542a
  Vendor ID:	0x24c6
  Version:	1.01
  Serial Number:	00005CA69347EFDD
  Speed:	Up to 12 Mb/sec
  Manufacturer:	PowerA
  Location ID:	0x14400000 / 2
  Current Available (mA):	1000
  Current Required (mA):	500
  Extra Operating Current (mA):	0

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
