### ISSUE TITLE
Controller will not connect

### ISSUE THREAD

**Issue by audett2** [360Controller/360Controller#420]
I can see the controller in the System Report, but the driver says No device found.  Mac is running El Capitan 10.11.6

Product ID:	0x0501
  Vendor ID:	0x0e6f
  Version:	1.00
  Serial Number:	06C937C9
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0xfa130000 / 5
  Current Available (mA):	1000
  Extra Operating Current (mA):	0

**Comment by FranticRain** [comment]
Unfortunately, this controller has already been added to the Info.plist. If it doesn't work with the driver, then it is a bug with macOS. If we can't see it with the driver in the first place, then we can't even begin to fix it. This matching process is handled by macOS and we don't have control over it. Sorry.
