### ISSUE TITLE
Remap stick and trigger axis

### ISSUE THREAD

**Issue by xythobuz** [360Controller/360Controller#421]
I'm still trying to get this controller diver to properly work with the GTA:SA version available on Steam for Mac. It basically seems to work, but the axis mapping is wrong: the right-stick X and Y axes are swapped with the LT and RT axis, respectively.

I saw swapping the two sticks is already implemented, so I think it should be more or less straight-forward to implement swapping the triggers and a stick.

Thanks!

**Comment by FranticRain** [comment]
It actually isn't trivial to swap the two because of how they are implemented in the backend with the HID spec. You'll need to consider a user-space remapping tool to resolve this issue.

**Comment by FranticRain** [comment]
This may possibly be resolved if someone implements the proposal in #455
