### ISSUE TITLE
Controller Unsupported

### ISSUE THREAD

**Issue by liamsmithuk** [360Controller/360Controller#424]
Controller:

  Product ID:	0xf501
  Vendor ID:	0x0e6f
  Version:	1.10
  Serial Number:	100FE0B
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Microsoft Inc.
  Location ID:	0x1a110000 / 2
  Current Available (mA):	1000
  Extra Operating Current (mA):	0

it's this
https://www.amazon.co.uk/gp/product/B006GT36D2/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1

Thanks

**Comment by FranticRain** [comment]
I've added this device to the Info.plist. It should be included in a new release of the driver that comes out in the next few days.
