### ISSUE TITLE
3rd party XBox 360 controller

### ISSUE THREAD

**Issue by Oxenfox** [360Controller/360Controller#428]
@Play brand from gamestop. Only see "No devices found". Would love to have it work on my mac.
 Product ID:	0x0501
  Vendor ID:	0x0e6f

**Comment by FranticRain** [comment]
Unfortunately, this device has already been added to the driver. If it doesn't work now, then there is an issue with macOS and there is nothing we can do about it. If macOS doesn't give the driver a chance to do anything, we can't fix it. Sorry.
