### ISSUE TITLE
Enhancement request about remapping

### ISSUE THREAD

**Issue by noxx09** [360Controller/360Controller#429]
I manualy remap keys controller for using it with a Wine version of Dark Souls : playing it with joypad, it's a little graal for a lot of people, it's a good game but the joypad keys are inverted. 
Well, it's works with buttons, but there are also problems with the triggers that can't be remapped now. I'ts promising...
Have you planned to complete the remapping possibility ? And can we expect a saving mechanism of a specific remapping for using it with a particular game ?
Regards,
Noxx.

**Comment by FranticRain** [comment]
We can't remap the triggers, sorry. That's simply not possible based on how the backend of the driver works, sorry.
