### ISSUE TITLE
My controller isn't supported

### ISSUE THREAD

**Issue by samuelbriole** [360Controller/360Controller#431]
Hello, My controller is not supported by the driver : 
name : **Battlefield 1 Official Wired Controller for Xbox One**

I'm running OS X 10.11.2

  Product ID :	0x0164
  Vendor ID :	0x0e6f
  Version :	1.01
  Serial Number :	0000ED9BDE8860BA
  Speed :	Up to 12 Mb/s
  Manufacturer :	Performance Designed Products
  Location ID:	0x14200000 / 11
  Current Available (mA) :	1000
  Extra Operating Current (mA) :	0

Can you please add it to the list of devices in the code ?
Thank you very much

**Comment by FranticRain** [comment]
I've added this device to the Info.plist. A new build should be out in a couple of days that adds this controller. Just hold tight.
