### ISSUE TITLE
3rd party controller

### ISSUE THREAD

**Issue by VashTheGun** [360Controller/360Controller#432]
@Play brand from gamestop. 
Product ID:	0x0501
Vendor ID:	0x0e6f

**Comment by gkrieg** [comment]
I have the same problem with the same controller.

It looks like it was added in #350 but I tried that build and it still doesn't recognize the controller.

**Comment by FranticRain** [comment]
Unfortunately, if the device is added to the info.plist, but doesn't work with the driver, there is nothing we can do about it. We provide these values to macOS to match us with devices. If macOS doesn't give the driver a chance to match with the device, then there is nothing we can do, sorry.
