### ISSUE TITLE
Xbox 360 Wired Controller not Supported

### ISSUE THREAD

**Issue by Ryan784** [360Controller/360Controller#435]
I am running OS X El Capitan, Version: 10.11.6

My Xbox 360 (wired) controller does not appear to be supported, or at the very least isn't being recognized by the driver.

Here is the controller information:
  Product ID:	0x0133
  Vendor ID:	0x0e6f
  Version:	1.00
  Serial Number:	0000C758
  Speed:	Up to 12 Mb/sec
  Manufacturer:	©Microsoft Corporation
  Location ID:	0x14100000 / 6
  Current Available (mA):	1000
  Extra Operating Current (mA):	0

When I connect the controller, the driver does not recognize it (no devices found). The controller flashes initially upon being plugged in, and then nothing. Under Hardware and USB it does show up as "Controller", however. 

I apologize if it's simply an error with my hardware, but in the case that this specific controller/product ID simply needs to be added, I'm posting the issue.

Thank you in advance.

**Comment by FranticRain** [comment]
I've added this device to the list. It should be supported in the next release that comes out in a couple days.
