### ISSUE TITLE
Xbox 360 third party controller not found OSX SIERRA

### ISSUE THREAD

**Issue by Lucasirwing** [360Controller/360Controller#436]
I have downloaded the drivers, restarted my computer x couple of times, still not found

I'm using OSX Sierra 10.12

Product-ID:	0xfafb
Vendor-ID:	0x24c6
Version:	1.00
Serialnumber:	068FFE9C

PLEASE HELP ME GUYS :(

**Comment by FranticRain** [comment]
This is the same controller as #445, it should work in a new release that will come out in a couple of days.
