### ISSUE TITLE
xbox 360 controllers not strumming inside logic pro x 10.3.1

### ISSUE THREAD

**Issue by GASTOD** [360Controller/360Controller#437]
hi, i use with music lab real guitar 4 and in standalone the controller is perfect... but inside logic pro x the plug in not strumming the rest is perfect the tilt the botto etc etc.... i think is a prob of the plug in? this a lot

**Comment by FranticRain** [comment]
This is a software level issue. Unfortunately, we cannot provide software specific hacks in the driver to fix issues. This would break compatibility with other pieces of software. There is nothing we can do. Sorry.
