### ISSUE TITLE
xbox controller constantly vibrates when holding down the right trigger

### ISSUE THREAD

**Issue by abepetrillo** [360Controller/360Controller#443]
Not sure if this is game specific, but when playing rocket league on El Capitan, the controller constantly vibrates while the right trigger is down (accelerate).

Not sure if this is specific to me but thought I'd share. Using 0.16.4 release.

**Comment by pepitito0** [comment]
go to System preferences go to Click Xbox 360 controller and press rumble options then click none

**Comment by andreasherbig** [comment]
you also need to close the Driver window after you are done

**Comment by FranticRain** [comment]
This is either a bug with the game, or you've left the preference pane open while playing the game. Closing the preference pane may help, but this is a game level issue, we can't fix it.
