### ISSUE TITLE
Aplay Controller

### ISSUE THREAD

**Issue by dylanmorshead** [360Controller/360Controller#445]
This third party controller doesn't work

Aplay product ID 0xfafb
Vendor ID 0x24c6

**Comment by 1byte2bytes** [comment]
I also have one of these controllers and would enjoy using it with macOS. :D

**Comment by FranticRain** [comment]
I've added this device and it will be in the latest release. I make absolutely NO guarantees that it'll work. If it doesn't, then there is nothing we can do to make it work. The new release should come on in the next few days.

**Comment by 1byte2bytes** [comment]
@FranticRain I can confirm this has worked for my Aplay controller, thank you! 😃
