### ISSUE TITLE
Please help with Xbox One Titanfall driver

### ISSUE THREAD

**Issue by Sigillight** [360Controller/360Controller#446]
Hi All, 

Can you please help me with drivers for my Titanfall 2 Official Wired Controller for Xbox One?

Product ID: 0x0165
Vendor ID: 0x0e6f

I have tried to do it myself, changed the 360Controller/360Controller/Info.plist file with aforementioned info, opened Driver.xcodeproj with Xcode and 360 Controller in Navigator, but not sure where to pick target in Xcode and what to do next in general.

Thank you very much for your help!

**Comment by FranticRain** [comment]
This should be in the next release that comes out either today or in a few days. Hold tight.
