### ISSUE TITLE
Support HoriPad Ultimate 

### ISSUE THREAD

**Issue by PeyloW** [360Controller/360Controller#448]
Product ID: 144
Vendor ID: 3853

Building the project using current Xcode is not possible. Downgrading and setting up developer ID is quite cumbersome would be nice if it worked out of the box.

Even nicer If there was an option to dynamically select vendor and product id with our recompiling the drivers.

**Comment by FranticRain** [comment]
Changing VID and PID combinations without recompiling the driver simply isn't possible. The matching system happens in macOS, and we simply provide a set of values for macOS to attempt to match. We cannot change that dynamically. This device will be in an upcoming release. Hold tight.
