### ISSUE TITLE
Wireless connection to MacBook Pro 2016 with touchbar

### ISSUE THREAD

**Issue by Akshshr** [360Controller/360Controller#450]
The controller doesn't respond or detect with the Mac book pro, I connect it with the bluetooth to the mac which works just fine, But I dont see anything reflect in the driver

Anything I am missing?

**Comment by FranticRain** [comment]
The driver is not needed for Bluetooth connections. You only need the driver for wired connections. To see if your controller is working or not, consider something like http://html5gamepad.com/
