### ISSUE TITLE
Steam Interface.

### ISSUE THREAD

**Issue by Darkreign08** [360Controller/360Controller#456]
Ive realized that Steam in big picture mode recognizes the controller, but games run through steam don't recognize the controller or driver as a gamepad extension.

**Comment by Cruplezone** [comment]
Yes they do/should. You have something not properly configured in steam most likely

**Comment by FranticRain** [comment]
Games use a different interface than Steam to discover controllers. If the controller works in Big Picture, but not in a game, then it is a game specific issue that we cannot fix.
