### ISSUE TITLE
Question: Able to "Lock" Input to Certain Applications?

### ISSUE THREAD

**Issue by jnovack** [360Controller/360Controller#461]
I hope this is the right place to ask, if not, please close with prejudice.

Is it possible to "lock" my controller input to certain applications, especially if they are not the foreground most application?

I would LOVE to use my keyboard and mouse on my browser, but my controller in the Rocket League app... at the same time.

I believe I would accomplish this by using my foreground application for my keyboard and mouse input, but all controller input would ONLY be sent to Rocket League, via magic(?).

The background application (in this case Rocket League.app), would ideally NOT move to the foreground, as my keyboard and mouse input would be interrupted within my previous foreground application (Chrome, or whatever).

Thank you, all.

**Comment by FranticRain** [comment]
Unfortunately, this is not something the driver can do. We simply provide an interface through which applications can discover the device. We don't have any ability to govern the device once it enters user space, sorry.
