### ISSUE TITLE
Xbox One Wireless Controller with Bluetooth

### ISSUE THREAD

**Issue by DeadEye88** [360Controller/360Controller#462]
Hey,

Installed your driver an wired my controller works. In your readme youve written that the bluetooth controller with bluetooth connects automatically. but if i turned the controller on, pressed the bluetooth button and then se xbox sign is fast blinking, my mac doesnt find the controller. i searched a lot everywhere and cant find anything which helps me.

Edit: 
Product-ID:	0x02dd
Vendor-ID:	0x045e  (Microsoft Corporation)

Greets DeadEye

**Comment by FranticRain** [comment]
Go to System Preferences -> Bluetooth. Ensure that Bluetooth is turned on. When you put the controller into pairing mode, connect to it through this menu. The driver is not needed to use an Xbox One controller through Bluetooth. This is all handled at the OS level.
