### ISSUE TITLE
Request for add support for BETOP BTP-C033

### ISSUE THREAD

**Issue by justicegmn** [360Controller/360Controller#464]
Please help to add support for below joystick, here is the info:

USB Joystick

Product ID:	0x0003
Vendor ID:	0x0e8f
Version:	1.07
Serial Number:	0691C5AA
Speed:	Up to 1.5 Mb/sec
Manufacturer:	GreenAsia Inc.
Location ID:	0xfa130000 / 5
Current Available (mA):	1000
Extra Operating Current (mA):	0

Thank you!

**Comment by FranticRain** [comment]
This controller is not supported by official Xbox hardware. As such, it's support is outside the scope of this driver. We cannot and will not support this driver.
