### ISSUE TITLE
Please support XiaoMi Game pad :)

### ISSUE THREAD

**Issue by lechchut** [360Controller/360Controller#466]
Major Type:	Peripheral
  Minor Type:	Peripheral
  Services:	XiaoMi Bluetooth Wireless GameController SDP Server, XiaoMi Bluetooth Wireless GameController, XiaoMi Bluetooth Wireless GameController PnP Server
  Paired:	Yes
  Configured:	Yes
  Connected:	No
  Manufacturer:	Broadcom (0x5, 0x2307)
  Firmware Version:	0x0129
  Vendor ID:	0x2717
  Product ID:	0x3144
  Class of Device:	0x05 0x02 0x0508
  Host Connectable:	No
  EDR Supported:	Yes
  eSCO Supported:	No
  SSP Supported:	Yes
  

Thank you

**Comment by MaddTheSane** [comment]
Bluetooth devices should already be supported by the OS. Other non-Xbox controllers probably won't be supported, either.
