### ISSUE TITLE
Xbox 360 wired controller not recognized (OSX 10.12.5)

### ISSUE THREAD

**Issue by aquova** [360Controller/360Controller#472]
Hello,

I'm trying to use a 3rd party "Play Gaming Accessories" Xbox 360 wired controller, yet it isn't being recognized in the System Preferences menu. I'm running Sierra 12.5, and the most recent release of the software, although I've never gotten this controller to work properly with older versions either.

> Wired Controller for Xbox 360:

>  Product ID:	0xfafa
>  Vendor ID:	0x24c6
>  Version:	1.00
>  Serial Number:	043297C1
>  Speed:	Up to 12 Mb/sec
>  Manufacturer:	Performance Designed Products
>  Location ID:	0x14100000 / 2
>  Current Available (mA):	500
>  Extra Operating Current (mA):	0

Thanks!

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
