### ISSUE TITLE
Third party wired controller

### ISSUE THREAD

**Issue by t11m77** [360Controller/360Controller#473]
The following third party wired xb360 controller is unrecognized
```

  Product ID:	0xfafa
  Vendor ID:	0x24c6
  Version:	1.00
  Serial Number:	042DDF85
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0x14200000 / 11
  Current Available (mA):	1000
  Extra Operating Current (mA):	0

```

**Comment by yixuanL** [comment]
This one is recognised as device but not in the test

PDP Camo Wired Controller for Xbox One：

Product ID：	0x0161
Vendor ID：	0x0e6f
Version：	4.60
Serial Number：	0000077160299853
Speed：	Up to 12 Mb/sec
Manufacturer：	Performance Designed Products
Location ID：	0x14200000 / 4
Current Available (mA)：	500
Extra Operating Current (mA)：	0

Thanks!

**Comment by dankoB** [comment]
I have recently purchased a Hyperkin x91 XBox One wired controller. I was under the assumption that this driver supported all XBox One controllers so I never looked into it further before purchasing. I have gone through all possible steps aside from trying to build under unsigned certificates which I would certainly prefer not to do.

[![Screen Shot 2017-06-05 at 11.38.47 PM.png](https://s17.postimg.org/7069ghghr/Screen_Shot_2017-06-05_at_11.38.47_PM.png)](https://postimg.org/image/g7yhx6njv/)

If adding this is at all possible it would be greatly appreciated.

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
