### ISSUE TITLE
Xbox one controller registers but how do I use?

### ISSUE THREAD

**Issue by tacomn** [360Controller/360Controller#475]
I have a mac and the xbox controller registers and shows up within the app test screen, but how do I actually use it? I want to play some flash games but it will not work as a mouse nor any inputs.

**Comment by Mirageofmage** [comment]
The driver actually doesn't work as a mouse or keyboard input, but actually as a gamepad which is supported by various games. If you want to use your controller as a mouse you'll have to set it up in [an application called ControllerMate](https://www.orderedbytes.com/controllermate/). There are many tutorials online explaining how to set this up.
