### ISSUE TITLE
PDP Rock Candy Xbox One Controller

### ISSUE THREAD

**Issue by ElielEgo** [360Controller/360Controller#483]
I installed the most recent version (0.16.5), and my Macbook detects the controller but it will not respond to input. The controller data is

![screen shot 2017-06-15 at 10 55 21 pm](https://user-images.githubusercontent.com/7798710/27211271-c60f6260-521d-11e7-9c31-2b86741d9908.png)

Can you please help me to make it work?

Thanks

**Comment by TGabrielTPOI** [comment]
I have exactly the same problem. I've tried downloading all the updates since 15 beta 3 and none of them worked. Would be extremely nice if would be fixed.

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
