### ISSUE TITLE
What the linked function for?

### ISSUE THREAD

**Issue by zyyedi** [360Controller/360Controller#491]
I am very confused about that and hope someone can help me figure out.

**Comment by Mirageofmage** [comment]
The linked function changes how deadzones work (if you have them set) on the thumbsticks.

**Unlinked:** 
![screen shot 2017-07-05 at 4 26 08 pm](https://user-images.githubusercontent.com/9158405/27883521-b9205c22-619e-11e7-8310-b72ce3505a81.png)
![screen shot 2017-07-05 at 4 26 15 pm](https://user-images.githubusercontent.com/9158405/27883522-b92376fa-619e-11e7-825b-c6ee81d12dd4.png)

**Linked:**
![screen shot 2017-07-05 at 4 26 22 pm](https://user-images.githubusercontent.com/9158405/27883525-bfb59a02-619e-11e7-8cfc-cb987e01efab.png)
![screen shot 2017-07-05 at 4 26 28 pm](https://user-images.githubusercontent.com/9158405/27883526-bfb6bd38-619e-11e7-81d9-4f626bcc0254.png)

With an unlinked deadzone, it extends throughout the whole X and Y axis, with a linked deadzone, it sets the deadzone to the rectangular area where they intersect
