### ISSUE TITLE
Not showing up after installation

### ISSUE THREAD

**Issue by lukeey0000** [360Controller/360Controller#502]
I was using an xbox one controller, but I wanted to be able to connect through usb instead of bluetooth so I downloaded this driver and completed the installation but I can’t find the program anywhere.  I have looked everywhere and now the controller won’t work with my game anymore.

**Comment by FranticRain** [comment]
This is a driver, not a program. There is a preference pane installed in your System Preferences that provides an uninstall feature. 

You can uninstall the driver by following the instructions found here: https://github.com/360Controller/360Controller#uninstallation
