### ISSUE TITLE
PDP xbox one controller not working

### ISSUE THREAD

**Issue by mollywhopped** [360Controller/360Controller#505]
So I have tried to download every last driver and nothing will work, I downloaded 360Controller 0.16.5 and what do you know it.. it worked! I played rocket league for about an hour and logged off. When I came back (about 2 hours later) it wasn't working again. What I mean by not working is the driver said I had a controller connected but no buttons were working. I have OS Sierra 10.12.3    I was just thinking about returning the controller and getting a new one. The controller that I want to get is made by "Power A" will this controller be compatible with the current drivers that are out?

**Comment by nightdr3am** [comment]
nope.....

**Comment by lynchy901** [comment]
https://github.com/360Controller/360Controller/issues/469 Try this.

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
