### ISSUE TITLE
Controller not working

### ISSUE THREAD

**Issue by oli1220** [360Controller/360Controller#509]
So when I go into the driver the controller is detected but wont respond to any of my inputs of the controller and in games it won't listen to any of my inputs either.
![screen shot 2017-08-12 at 3 33 41 pm](https://user-images.githubusercontent.com/30759055/29241540-c24291ba-7f73-11e7-838a-7d054b12cd2d.png)

Help please
Mac Version 10.12.6
13 Inch Macbook air

Controller
Power A Spectra Illuminated Controller

**Comment by wmaness** [comment]
I have this  problem as well, Power A, wired USB controller:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  System Version:	OS X 10.11.6 (15G1611)
  Kernel Version:	Darwin 15.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	        Normal

**Comment by pulkitag** [comment]
I have the same issue, with the same controller. Any suggestions on what to do? @oli1220 did you find a solution?

**Comment by PokeCaptain** [comment]
What works for me is to plug in the controller, then disable and reenable the driver. Seems to work, but it's a bad solution long-term.

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
