### ISSUE TITLE
HELP iMac Wont Boot after installing this Driver!

### ISSUE THREAD

**Issue by Zucarini** [360Controller/360Controller#510]
Please help me, my iMac running Mac OS Sirra won't boot after installing this driver, its stuck in the apple logo and white loading bar, im trying to remove the KEXT from the single user mode but i cannot find it! please help

**Comment by FranticRain** [comment]
Installing kexts is dangerous and can potentially harm your machine. 360Controller is provided without warranty and is installed at your own risk. You can reinstall your operating system using the recovery mode, but we cannot help you with issues like that.
