### ISSUE TITLE
Request: PowerA/Liquid Metal Controllers

### ISSUE THREAD

**Issue by ghost** [360Controller/360Controller#514]
Hi,

Some 3rd-party PowerA/Liquid Metal xbox 1 controllers need to be sent a rumble packet at init before they'll send input. 

See here:
[https://github.com/paroj/xpad/issues/48#issuecomment-284171968](https://github.com/paroj/xpad/issues/48#issuecomment-284171968)

and here:
[https://github.com/cgutman/xpad/blob/for_upstream/xpad.c#L380](https://github.com/cgutman/xpad/blob/for_upstream/xpad.c#L380)

for what had to be done to get these to work on linux.

Any way you can implement that in this driver?

Thanks!

**Comment by nightdr3am** [comment]
hi i have a PowerA/Liquid Metal Controller. But i was wondering if theres any development toward this i would like to use my third party xbox controller. i am struggling to to get it run on the latest Mac OS at the current time.

**Comment by blakekl** [comment]
I'd also like to see this. Newegg just had a sale for these things at $10 a pop, so I bought a few. They work fine on my windows box, but not on my linux/mac boxes.

**Comment by FranticRain** [comment]
Here's a build with the proposed fix. Let me know if it works. 
[360ControllerInstall.dmg.zip](https://github.com/360Controller/360Controller/files/1869818/360ControllerInstall.dmg.zip)

**Comment by blakekl** [comment]
I just tried the proposed fix. There is no difference in behavior. The controller shows up in the dropdown list as Xbox One Wired Controller (Wired), and the light on the controller is on, but none of the buttons or axes show any input when used.

**Comment by blakekl** [comment]
For what it's worth, I cannot get these to work on linux either. They work just fine on my windows machine though.

**Comment by FranticRain** [comment]
Okay, then the assumption that this is an IOUSBHost issue holds. I pushed the fix anyway. Closing this.
