### ISSUE TITLE
Request: Hyperkin X91

### ISSUE THREAD

**Issue by joshuataylor89** [360Controller/360Controller#515]
Hi, I have the Hyperkin X91 I wanted to know if there is a work around to get it to work on my mac. The info I have is below. thank you
Product ID:	0x1688
Vendor ID:	0x2e24

**Comment by dankoB** [comment]
I second this request. It's recognized by system profiler but not with the driver installed. Big fan of the controller design. Old school but sleek...been meaning to pick up a cheap ps3 controller in the meantime.
