### ISSUE TITLE
having trouble running this program

### ISSUE THREAD

**Issue by nightdr3am** [360Controller/360Controller#518]
i am currently using a third party Xbox one by Liquid metal controller. i was able to get the system preference to detect the controller, but theres not indication of me pressing the buttons on the controller. this is the system report on latest OS for mac 10.12.6.
https://drive.google.com/open?id=0B2I1Twjb3ckTM1oxN29uMWdNLWc

**Comment by dankoB** [comment]
I may be wrong, but I feel like your particular controller was supported at one time but changes to MacOS 10.12 changed things up a bit and developers are more focused on making things work with MacOS 10.13. Development documents were just updated a couple months back on the Apple website so I'm sure we'll see some new compatibility late fall early winter perhaps?

https://developer.apple.com/library/content/releasenotes/MacOSX/WhatsNewInOSX/RevisionHistory.html#//apple_ref/doc/uid/TP40001817-SW1

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
