### ISSUE TITLE
Mapping keys?

### ISSUE THREAD

**Issue by AlexRT737** [360Controller/360Controller#520]
This is probably stupid to ask but I can't figure it out and I can't find instructions anywhere in the readme. How do you map keys in the binding section? Can someone explain how or link me to instructions? Thanks.

**Comment by FranticRain** [comment]
When you go into the binding menu, there will be a "Start Binding" button. Then you press the button that you want to be the highlighted button. So if you wanted the B button to appear as the A button, when the A button was highlighted, you would press the B button.
