### ISSUE TITLE
Xbox 360 Controller not recognized by driver

### ISSUE THREAD

**Issue by hferrone** [360Controller/360Controller#529]
Hello,

I thought I bought an Xbox 360 controller, not a third party, but I'm not sure. Here is a screenshot of my device ID etc. Can someone please let me know why the driver isn't recognizing the controller?

Cheers!
![screen shot 2017-10-02 at 20 05 27](https://user-images.githubusercontent.com/8218795/31092043-66ddcac6-a7ad-11e7-9c55-08286c350b92.png)

**Comment by hferrone** [comment]
System specs
![screen shot 2017-10-02 at 20 08 57](https://user-images.githubusercontent.com/8218795/31092083-9008441c-a7ad-11e7-86bf-f7cf87dbf51c.png)

**Comment by PokeCaptain** [comment]
Performance Designed Products is third party. Seems to be one of [these](http://pdp.com/en/shop/xbox_360/).

**Comment by kargq** [comment]
same prob, and my controller is totally originaly brand new x box one s controller
![screen shot 2017-10-11 at 8 07 44 pm](https://user-images.githubusercontent.com/32722218/31472990-e3d12df2-aebf-11e7-81e8-34ffd5e29a50.png)

**Comment by Carsonsmuts** [comment]
Ditto


![untitled 2](https://user-images.githubusercontent.com/7245909/32470496-2316e05e-c326-11e7-94de-0b51974e55ba.jpeg)

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.

Please open new issues for different controllers.
