### ISSUE TITLE
Question about XB1 interrupt protocol

### ISSUE THREAD

**Issue by timmeh87** [360Controller/360Controller#530]
Sorry for making a ticket for this, as it is not an issue with this project at all. I am looking for some help interfacing with an XB1 controller and this looks like the most active/knowledgeable forum to get such help. 

I have connected an XB1 controller to an embedded microcontroller through USB. I am trying to get the controller to output button reports so that I can use the controller with my project.

This controller is the new type, the one that has bluetooth. I am not trying to use the bluetooth though.

I reasoned that I should be able to capture the communication between the controller and my Win10 PC and then just mimic it in order to read the button reports.

After enumerating and selecting the first interface, I have endpoints 0x82 and 0x02 open. the XB1 controller sends me a packet with a payload of

02 20 02 1c 73 ed ... (64 bytes)

I (the host) then reply with the packet

04 20 01 00

And the controller replies 

04 f0 02 3a da 01 10 00 01 00 ... (64 bytes)

These first 3 messages appear to progress the same way as my capture, but that's when I get stuck. I believe the next thing i should send is 

01 20 02 09 00 04 20 3a 00 00 00 a0 00

and the controller should reply with several more messages that start with 04 a0. However it just gets stuck repeating the 04 f0 message forever. I have noticed that the 3rd byte is variable and always matches the 3rd byte of the first 02 report, but I still cannot get past 04 f0

If i press the center X button, the message turns into an 07 type

I dont know why it is getting stuck at 04 f0, i have been pulling my hair out. I can successfully send some other messages from my capture that start with 05 and cause the LED on the controller to turn on, but in response to any further messages I just keep getting 04 f0. Maybe there is some special thing my code has to do to ACK the message? In my capture it looks like the controller is trying to send a Zero Length Packet after the 64 byte 04 f0 packet when it talks to Win10, but I never seem to receive a ZLP. Maybe this is a clue?

I would like to know if there is anything special I should be doing to get the controller to go into "normal mode" and start outputting 20 reports when I press the buttons. I can see that the series of 04 messages I am stuck on is just reading some data from the controller which I probably dont even care about. Is there some magic thing I can send to just get the 20 reports with minimal effort?

**Comment by FranticRain** [comment]
https://franticrain.github.io/packetformat/packetformat.html

The only packets that we send are these two, and they get *most* Xbox One controllers into a normal interaction mode.
https://github.com/360Controller/360Controller/blob/master/360Controller/_60Controller.cpp#L527
