### ISSUE TITLE
Rock Candy Gamepad Not Working.

### ISSUE THREAD

**Issue by slytherclawgamer** [360Controller/360Controller#535]
At the time of writing, my Rock Candy gamepad (controller) is not working. Its ProductID is 0xfafe, and its VendorID is 0x24c6.

**Comment by FranticRain** [comment]
PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
