### ISSUE TITLE
Logitech Chillstream (similar to xbox 360 gp) not recognising in Parallels Desktop

### ISSUE THREAD

**Issue by InterStena** [360Controller/360Controller#543]
I have a windows 7 installed on my parallels desktop VM, I play a lot of games with it.

Controller exists in Mac (works in Super Meat Boy when "Pretend to be xbox 360 controller" enabled). But absolutely doesn't work in virtual machine. Logitech says it should work in windows without any drivers.
It sounds more like question but idk where to ask it. So hope developers/community/anybody will help me to fix this.

**Comment by InterStena** [comment]
(some info about parallels)
All my usb devices should appear in this section:
![2017-10-28 21 10 34](https://user-images.githubusercontent.com/7333912/32137250-d41a80b2-bc24-11e7-8874-0e4fcd5eaced.png)
But I don't see my controller there.

**Comment by FranticRain** [comment]
This controller is not supported by official Xbox hardware. As such, it's support is outside the scope of this driver. We cannot and will not support this driver.
