### ISSUE TITLE
Xbox One S controller

### ISSUE THREAD

**Issue by Pompomgalli** [360Controller/360Controller#544]
Hi,

My setup:
- IMac 2010 with MacOS Sierra
- Steam in big picture mode with local multiplayer games
- 4 Xbox One S controllers (all same model)

My issue:
- When wired the controllers work perfectly fine
- When wireless (bluetooth) the controllers are working in big picture menu but not in games :(

My question:
Is there a way to use this driver when connected via bluetooth ? For information Vivid Controllers application shows:
- when wired: "Microsoft / Xbox One Wired Controller"
----> everything is ok in big picture and in games
- when wireless: "Unknown / Xbox Wireless Controller"
----> LT/RT are not recognized and no rumble in big picture
----> nothing works in games

Thank you

**Comment by RodrigoCard** [comment]
The wireless mode is currently NOT handled by this driver and works natively.
LT/RT not working in these controllers is probably a bug on SDL game controller library used by most games that was patched a few months ago (check for updates on your games and get the latest Steam client beta)
