### ISSUE TITLE
Xbox one S controller not recognised

### ISSUE THREAD

**Issue by hussain3450** [360Controller/360Controller#549]
I had an older build of the driver installed on my system but it wouldn't recognise the xbox one s controller that I recently bought. I downloaded the latest driver but still no difference. The controller connects through bluetooth without problems it just doesn't show up in the driver preferences.

**Comment by FranticRain** [comment]
Bluetooth controllers are not supported by the driver. They are natively supported by the operating system, and therefore not part of the scope of 360Controller. 360Controller is only needed if you connect the controller to your system via a wire. The preference pane for 360Controller only checks for controllers supported by 360Controller. If the controller makes a successful Bluetooth connection with macOS, then it is working. No need to check it in the preference pane.
