### ISSUE TITLE
xbox one controller not detected on the driver

### ISSUE THREAD

**Issue by emperorm2** [360Controller/360Controller#551]
The xbox controller driver does not recognize the controller

My set up is
・MacBook Air 2017 with osSierra Version 10.12.6
・Wired controller for Xbox one by pdp
・xbox controller driver -> 360Controller 0.16.5
My issue is
・driver does not detect any device
・Mac does recognize the controller in the system profiler
・light does not come on even if plugged in
・firmware updated to the newest version
My question
・What is the problem(s)?

**Comment by Melechim** [comment]
I'm have a MacBook Pro 2017. I can get my controller to light up but I can't get the driver to recognize
either controller I try to plug in.

**Comment by johnflan** [comment]
Similar issue here running high sierra 

<img width="662" alt="screen shot 2017-11-25 at 19 28 04" src="https://user-images.githubusercontent.com/410657/33233971-d8e371fa-d216-11e7-9b59-364156be6fda.png">

**Comment by Melechim** [comment]
I got it to work but it only worked until I turned my comp off. I tried to go into my security preferences and turn it back to allow but its not working anymore

**Comment by CryingMagma** [comment]
Have you tried using a different usb cable to plug it in, sometimes the USB cable won't work and the solution is to just use a different one.

**Comment by Melechim** [comment]
It worked for a couple of days I was using the data cable I got with my charger pack for the xbox 1 I don’t understans why it just quit working

**Comment by reteps** [comment]
go to advanced and check "enable driver". This fixed it for me.

**Comment by emperorm2** [comment]
Enabling the driver in the advanced section did not work for me.

**Comment by Melechim** [comment]
Yeah I’ve done all of that I don’t know what happened

**Comment by FranticRain** [comment]
Before we can help you, please consult the README and provide all necessary information so that we can help you with your issue. https://github.com/360Controller/360Controller#xbox-one-controllers-connected-with-usb

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
