### ISSUE TITLE
Is this just a rebuilding from the original version?

### ISSUE THREAD

**Issue by lethelimited** [360Controller/360Controller#554]

**Comment by Cruplezone** [comment]
no

**Comment by Deph0** [comment]
From the [Readme](https://github.com/360Controller/360Controller/blob/master/Readme.md#im-using-a-driver-from-the-tattiebogle-website)
>###  I'm using a driver from the Tattiebogle website
> 
> The Tattiebogle driver is NOT the same driver as this Github project. We do NOT support that driver. Under NO circumstances will we support that driver. If you download the latest version of this driver from the releases page we will do our best to help you out. This driver will install over the Tattiebogle driver. You don't have to worry about uninstalling the Tattiebogle driver first.

**Comment by FranticRain** [comment]
Don't make issues without even reading the README. Come on, dude.
