### ISSUE TITLE
play gaming accessories xbox 360 game pad "no devices found"

### ISSUE THREAD

**Issue by srosin** [360Controller/360Controller#564]
play gaming accessories xbox 360 game pad "no devices found"

Wired Controller for Xbox 360:

  Product ID:	0xfafa
  Vendor ID:	0x24c6
  Version:	1.00
  Serial Number:	06EA09D4
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0x14423000 / 14
  Current Available (mA):	500
  Extra Operating Current (mA):	0

**Comment by KorvinSzanto** [comment]
Try the steps listed in this comment: https://github.com/360Controller/360Controller/issues/566#issuecomment-349858763

**Comment by srosin** [comment]
there was no dialog in "System Preferences/Security & Privacy/General" @KorvinSzanto

**Comment by Nastrella** [comment]
Same as serosin, no dialogue showed up.

![capture d ecran 2017-12-07 a 08 07 52](https://user-images.githubusercontent.com/34196804/33704861-09438c5a-db26-11e7-87a5-5bf42ec80162.png)

**Comment by xboxjoey** [comment]
I seem to be having issues with the same model of controller. Curious if it is High Sierra or the model of controller?

https://github.com/360Controller/360Controller/issues/567#issuecomment-350401738
