### ISSUE TITLE
how to uninstall on mac

### ISSUE THREAD

**Issue by Enchman69** [360Controller/360Controller#569]
hi im wondering if you have any directions on how to uninstall this program from my mac? its just not working correctly

**Comment by xboxjoey** [comment]
Go to System Preferences and click on the 'Xbox 360 Controllers' Preference Pane and then click 'Advanced' and you will see the button to uninstall. It's not working for me either, but I'm thinking it might be the model of my controller...

**Comment by Enchman69** [comment]
i did so, however when installing it left a drive called "VM" thats completely messing up my system
...
![screen shot 2017-12-12 at 6 30 58 pm](https://user-images.githubusercontent.com/34487216/33915763-9f8eb692-df6a-11e7-9716-b5feeacc1a50.png)

**Comment by Enchman69** [comment]
i did so but its not removing this drive called "VM" which is messing with my mac pretty badly 
...
![screen shot 2017-12-12 at 6 30 58 pm](https://user-images.githubusercontent.com/34487216/33915807-f1305492-df6a-11e7-9750-4bfeba62b810.png)

**Comment by xboxjoey** [comment]
Weird. I don't have that. I'm on macOS 10.13.1 with the software still installed. 

Does VM stand for virtual machine? Are you running another OS on your computer? I'm not very knowledgable, just making guesses...

**Comment by Adansix** [comment]
@Enchman69 
VM stands for Virtual Machine. I'm guessing you emulate Windows on your Mac or whatever...

**Comment by FranticRain** [comment]
https://github.com/360Controller/360Controller#uninstallation

The VM drive isn't created by the driver.
