### ISSUE TITLE
3rd Party Wired Xbox One Controller Not Recognized 

### ISSUE THREAD

**Issue by H10Maxwell** [360Controller/360Controller#574]
Product ID:	0x0160
  Vendor ID:	0x0e6f

I have PDP wired Xbox One controller that shows in the About This Mac > System Report screen, but isn't found in the System Preferences > Xbox 360 Controller screen. I'm very inexperienced with coding so I hesitated to go further without help. I am running OSX Capitan 10.11.6

**Comment by sterpe** [comment]
See https://github.com/360Controller/360Controller/issues/571#issuecomment-353518154 for how to improve this report for greater visibility and higher probability that someone can eventually address it.

**Comment by sterpe** [comment]
Possibly see https://github.com/360Controller/360Controller#adding-third-party-controllers

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.

This device will still be added, as it should still work with El Capitan.
