### ISSUE TITLE
PDP Wired Controller for Xbox One - Stealth Series | Phantom Black - Not Recognized

### ISSUE THREAD

**Issue by mstarkman** [360Controller/360Controller#578]
Our `PDP Wired Controller for Xbox One - Stealth Series | Phantom Black controller` isn't recognized by our Mac.  Here are the specifics.  Can anyone help?

```
PDP Wired Controller for Xbox One - Stealth Series | Phantom Black:

  Product ID: 0x02ad
  Vendor ID: 0x0e6f
  Version: 1.0e
  Serial Number: 000033E2FC80CE58
  Speed: Up to 12 Mb/sec
  Manufacturer: Performance Designed Products
  Location ID: 0x14200000 / 7
  Current Available (mA): 500
  Current Required (mA): Unknown (Device has not been configured)
```

![image](https://user-images.githubusercontent.com/43868/34457442-4360f12e-ed7e-11e7-9904-c62712a1c25d.png)

![image](https://user-images.githubusercontent.com/43868/34457444-48fa72fe-ed7e-11e7-9712-a110af43260d.png)

**Comment by mfwhatever** [comment]
Same for PDP Wired Controller for Xbox One - Stealth Series | Revenant Blue

  Product ID:	0x02a6
  Vendor ID:	0x0e6f
  Version:	1.0f
  Serial Number:	0000941BC7B48D1D
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0x14100000 / 23
  Current Available (mA):	1000
  Extra Operating Current (mA):	0


I've check the Info.plist of the latest build and these models don't seem to be listed. I realise that having them listed is no guarantee that they will work, but would it be possible to have them added to the next build anyway?

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
