### ISSUE TITLE
Unrecognized controller with USB hub on new macbook pro

### ISSUE THREAD

**Issue by fguerin** [360Controller/360Controller#581]
Hi guys,

Few months ago I bought the new mac bookpro (with only 2 USB-C ports) and i'm trying to connect my Xbox 360 controller. As there are only USB-C ports, I bought the apple official hub (with 1 USB, 1 HDMI and 1 USB-C ports). I installed the 0.16.5 driver version and when I connect the controller, there are green lights for less then 1 second and nothing. 
I checked in my Hardware and there are only HUBs.

Does someone had the same issue? Thanks.
Florian

<img width="863" alt="capture d ecran 2018-01-02 a 13 15 07" src="https://user-images.githubusercontent.com/842912/34483499-2398d56c-efbf-11e7-8187-a6c83486693a.png">

**Comment by lordzsolt** [comment]
Trying to do the same thing as well, can't seem to make it work :(

**Comment by FranticRain** [comment]
Sorry. We only work within the parameters of what the operating system provides to us. If the operating system doesn't show us the USB devices, we can't do anything about it. I can recommend you try a different cable to see if the cable you are using is a charge cable and not a data cable, but it is impossible for us to provide a fix for this issue.
