### ISSUE TITLE
PDP Wired Controller for Xbox One - Raven Black (not recognised)

### ISSUE THREAD

**Issue by toyyystory** [360Controller/360Controller#583]
Recently bought a new controller but it's not recognised on system preferences

PDP Wired Controller for Xbox One - Raven Black:

  Product ID:	0x02a7
  Vendor ID:	0x0e6f
  Version:	1.0f
  Serial Number:	00006D1D60217C1B
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0x14310000 / 4
  Current Available (mA):	500
  Extra Operating Current (mA):	0

Is there a thread that I've missed? Or anyone aware of how to fix this?
Thanks :)

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
