### ISSUE TITLE
Controller Not Connecting

### ISSUE THREAD

**Issue by coolkide7750** [360Controller/360Controller#585]
When i plug in the controller the light blinks once and doesn't blink again. It doesn't show up as a device in the driver and if i look at my security and privacy settings there is not "alloy" button or anything like that. 
![screen shot 2018-01-07 at 9 50 51 am](https://user-images.githubusercontent.com/13584457/34645266-66c4c27c-f390-11e7-92a7-8d76f36ebb16.png)
![screen shot 2018-01-07 at 9 51 03 am](https://user-images.githubusercontent.com/13584457/34645268-6707e7d2-f390-11e7-9c4d-e4261ebe4623.png)
![screen shot 2018-01-07 at 9 51 19 am](https://user-images.githubusercontent.com/13584457/34645269-67468dfc-f390-11e7-9b8c-a2ab7ef35ecf.png)
![screen shot 2018-01-07 at 9 51 27 am](https://user-images.githubusercontent.com/13584457/34645270-6785713e-f390-11e7-97ca-dfcf984f7921.png)

**Comment by nour-s** [comment]
Same here, but looks like you are using an old version 0.12 of the driver. the latest is 0.16.5

**Comment by FranticRain** [comment]
https://github.com/360Controller/360Controller#im-using-a-driver-from-the-tattiebogle-website
