### ISSUE TITLE
Can't find after installation 

### ISSUE THREAD

**Issue by 13345bob** [360Controller/360Controller#586]
I downloaded the newest version to the Macintosh HD disk drive thing and I can't find it to access. Is there anyway to install it somewhere else, such as the desktop, or is it not downloading for some reason?

**Comment by FranticRain** [comment]
The driver is installed within your operating system. It is not a program that you run.

**Comment by mcfly224** [comment]
But how do you access it? I don't understand how to connect my controller still.

**Comment by FranticRain** [comment]
A driver works by plugging in your controller. That's it. There are settings in your System Preferences.
