### ISSUE TITLE
Issues with PowerA wired controller.

### ISSUE THREAD

**Issue by brandonator365** [360Controller/360Controller#588]
Product ID:	0x542a
  Vendor ID:	0x24c6
  Version:	1.01
  Serial Number:	0000260C25A99FEE
  Speed:	Up to 12 Mb/sec
  Manufacturer:	PowerA
  Location ID:	0x14640000 / 43
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

This controller isn't working on the Preferences tab, nor in game.

**Comment by FranticRain** [comment]
PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
