### ISSUE TITLE
Won't recognize Wireless Xbox One Controller.

### ISSUE THREAD

**Issue by wantondevious** [360Controller/360Controller#591]
Installed the latest  0.16.5 on El Capitan.

Xbox One S Controller (https://www.amazon.com/gp/product/B01LPZM7VI/) September 2016?

Connects to bluetooth fine. On Elder Scrolls, the joysticks work (without this driver in fact), but the ABXY buttons and 3 of the DPads dont work. Which is why I tried this, but the device just doesn't show up at all on the control panel.

W

**Comment by MaddTheSane** [comment]
Contact Bethesda support: the Bluetooth controller, when connected via Bluetooth, is not handled by the driver at all. As such, nothing done by the driver would have any effect on the game.

**Comment by wantondevious** [comment]
ok! Thanks MaddTheSane!

W
