### ISSUE TITLE
Pretend to be Xbox 360 Controller only works to register 1 controller

### ISSUE THREAD

**Issue by RSid** [360Controller/360Controller#593]
Hey, thanks for maintaining this, it's super helpful! I was able to get one xbox 360 wired controller working with big picture mode and all my games by checking 'pretend to be an xbox 360 controller', but I haven't been able to get a second one recognized for multiplayer. 

If I plug the second controller into a different USB port than the one I was plugged into when I registered the first controller, it'll show up as 'unknown controller', but work fine. If I plug it into the first USB port, it'll show up as if it is the first controller, and if I plug either controller into the different USB port while the other is also plugged in, only the one in the first USB port will work or show up.

Is there a known workaround for this?

**Comment by FranticRain** [comment]
This should be fixed in alpha 4.
