### ISSUE TITLE
Xbox one controller not working

### ISSUE THREAD

**Issue by ViscousOx** [360Controller/360Controller#594]
When using the driver steam can see the controller however no button pushes are registered. The controller is an xbox one power A controller and here is the product ID and vendor ID...

Product ID:	0x543a
  Vendor ID:	0x24c6

Any help is greatly appreciated

**Comment by FranticRain** [comment]
PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
