### ISSUE TITLE
Not working with high sierra

### ISSUE THREAD

**Issue by jldav** [360Controller/360Controller#602]
Xbox 360 Controller won't connect to wireless adapter. Adapter shows up under systems in Mac, just updated to high sierra and the xbox360 controller just blinks and won't connect.

**Comment by jldav** [comment]
Just tested this on my work laptop. Running Yosemite, same controller and same wireless adapter. It works in Yosemite. So this driver does not support high sierra, at least not for me.

**Comment by StTheo** [comment]
I had issues after restarting until I checked "Security & Privacy" and allowed the "Drew Millis" app manually. Then the light turned on and the preference pane knew about it.

**Comment by jldav** [comment]
Thanks for the tip, I allowed the Drew Millis app but it still won't connect :(. If anyone has had any luck with High Sierra let me know! Some of my Steam stuff won't play on Yosemite, but I can't get the controller to work with High Sierra still.

**Comment by Cruplezone** [comment]
You really shouldn't be using the wireless adapter with this driver, it is known to reliably cause kernel panics on sleep.

**Comment by FranticRain** [comment]
Wireless adapters not working in Sierra is a known issue caused by a rewrite of the macOS USB kernel introduced in 10.11. Discussion consolidated in #605
