### ISSUE TITLE
Wired Xbox One controller not connecting

### ISSUE THREAD

**Issue by SupremeSalamander** [360Controller/360Controller#603]
I dont know if this is a problem with the software, my computer, or my controller. I have plugged in my controller to my iMac, but the controller's light keeps flashing, signaling that it isn't connected. When I open 360Controller, the program doesn't recognize it either. Please give me some tips.

**Comment by MaddTheSane** [comment]
Is the cable a charging cable? If so, you need a cable that can also transmit data.

**Comment by SupremeSalamander** [comment]
It's not a charging cable. When i plug it into my xbox it works fine, but it doesn't work on my computer.

**Comment by arthas994** [comment]
Check if under "Security & Privacy" in system preferences "Drew Milis" App is allowed.

**Comment by nalancer08** [comment]
@arthas994 Thank you so much!!! This step its necessary in intilling guide.

**Comment by lilphil123** [comment]
@MaddTheSane  do u have a link to these cables?
