### ISSUE TITLE
Recognise but joystick not working.

### ISSUE THREAD

**Issue by Zadmath** [360Controller/360Controller#612]
I installed the app, restarted my computer, connected my USB Xbox One Controller : https://www.amazon.fr/dp/B01GKXEWPY/ref=asc_df_B01GKXEWPY50600450/?tag=googshopfr-21&creative=22722&creativeASIN=B01GKXEWPY&linkCode=df0&hvdev=c&hvnetw=g&hvqmt=
, the app recognised my controller.
But in game it still not working, I tried on GTA San Andreas and also on the remapping which don’t works.
I don’t have any animations while moving the joystick.
Do you have any idea how to fix it ?

Screen : https://www.noelshack.com/2018-10-1-1520273587-capture-d-ecran-2018-03-05-a-19-12-44.png

Sorry for my bad english I’m French :p

**Comment by FranticRain** [comment]
Go into the advanced tab and check "Pretend to be an Xbox 360 Controller." That's the best we can do.
