### ISSUE TITLE
'No devices found' Xbox Wireless controller 

### ISSUE THREAD

**Issue by DanB91** [360Controller/360Controller#620]
I recently got a new Xbox (One) controller and was able to connect it via bluetooth to my mac.  However, the controller does not show up in the preference pane.  I am running High Sierra, the driver is enabled and not blocked in "Security and Privacy".   The controller works on Steam big picture (but broken on Fortnite, with buttons swapped with each other among other problems).

Please advise on how I can get 360Controller to recognize it.  Thank you!

**Comment by fantomraviolis** [comment]
I have been having this exact same problem and would greatly appreciate some help with troubleshooting.

**Comment by Miheegz** [comment]
Yes, anybody find a fix for this? I think in the readme it says that xbox one s controllers wont be recognized by the driver thru bluetooth bc they don't support it currently since it connects through bluetooth already. However, the button mapping is completely off making Fortnite unplayable!!

**Comment by MaddTheSane** [comment]
If Fortnite has a way to remap buttons, use that. Otherwise, plug in the controller using a USB micro connector and the wired XBO driver can be used instead.
