### ISSUE TITLE
360 Wireless Adapter - No device found

### ISSUE THREAD

**Issue by nour-s** [360Controller/360Controller#627]
I'm using 360 Wireless Adapter on MacBook Pro laptop. 
I really tried so hard every solution mentioned before but I still couldn't fix the issue:

![image](https://user-images.githubusercontent.com/1418564/38111664-ab1c3bac-33b0-11e8-9c4c-b37e0349cc90.png)

I disabled the system integrity protection:

![image](https://user-images.githubusercontent.com/1418564/38111795-1501bfe2-33b1-11e8-98ee-1851e7c60543.png)

I checked that the driver is loaded:

![image](https://user-images.githubusercontent.com/1418564/38111894-57326c68-33b1-11e8-81b1-d1d1388b6d5b.png)

I checked the vendor and product id:

![image](https://user-images.githubusercontent.com/1418564/38112031-c3359908-33b1-11e8-987d-b09b778b583a.png)

I added the new settings to Info.plist file:
`		<key>NourControllers</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.mice.driver.Xbox360Controller</string>
			<key>IOCFPlugInTypes</key>
			<dict>
				<key>F4545CE5-BF5B-11D6-A4BB-0003933E3E3E</key>
				<string>360Controller.kext/Contents/PlugIns/Feedback360.plugin</string>
			</dict>
			<key>IOClass</key>
			<string>Xbox360Peripheral</string>
			<key>IOKitDebug</key>
			<integer>65535</integer>
			<key>IOProviderClass</key>
			<string>IOUSBDevice</string>
			<key>idProduct</key>
			<integer>681</integer>
			<key>idVendor</key>
			<integer>1118</integer>
		</dict>
`
restarted the laptop, yet still doesn't work.

The driver is enabled in the advanced menu, I even tried to do it manually using
`
sudo kextunload /Library/Extensions/360Controller.kext
`
`
sudo kextload /Library/Extensions/360Controller.kext
`

My laptop specs:

![image](https://user-images.githubusercontent.com/1418564/38112267-732c6e22-33b2-11e8-89e0-d83b1a8dd5c4.png)

Note that I tried to connect XBOX One Controller using USB cable, and it worked perfectly.
Also, I think it worth mentioning that the **/Library/Extensions** contains multiple kext files related to the controller driver which I find wierd! : 

- 360Controller.kext (only this is loaded)
- Wireless360Controller.kext
- WirelessGamingReceiver.kext

Is this normal?

**Comment by Cybershoot** [comment]
Driver is enable in advanced menu?

**Comment by nour-s** [comment]
@Cybershoot Yes, I even tried to do it manually using
`
sudo kextload /Library/Extensions/360Controller.kext
sudo kextunload /Library/Extensions/360Controller.kext
`

**Comment by Cybershoot** [comment]
@nour-s  I have almost similar laptop. The OS system is the same (10.12.6), as a wireless controller I've "Microsoft 9Z2-00002 Wireless Windows PC Adapter" with this specific.


<img width="482" alt="schermata 2018-03-30 alle 11 43 09" src="https://user-images.githubusercontent.com/37883234/38133729-c4215c94-3410-11e8-95db-5d90415c9905.png">

**Comment by nour-s** [comment]
@Cybershoot I think mine is not original. However, it works on Windows, AND it used to work on the exact same laptop. but at some point, it stopped working, and I couldn't tell what exactly made this issue.

**Comment by pekapa** [comment]
Same here,
My controller is the same that @Cybershoot 
I had the 0.16 version installed (that used to work back on Yosemite and I believe on El Capitan as well) and tried updating to the 0.16.5 with no success.

I'm currently running High Sierra, I'm guessing something between El Capitan and Sierra broke the wireless support...

**Comment by nour-s** [comment]
I upgraded to mac Hight Sierra, but the driver still doesn't work. However, I downloaded the latest release of the driver 0.16.6. Magically, it worked 😃.
It's only annoying that I need to enable the driver every time, but hey, at least it works.

Thanks, @FranticRain for the support. You can close the ticket I think.
