### ISSUE TITLE
Rock Candy Xbox 360 wired controller

### ISSUE THREAD

**Issue by h224h** [360Controller/360Controller#628]
Hi, so I just bought a rock candy 360 wired controller and downloaded 0.16.5

I have a MacBook Pro on version 10.13.3 

The Product ID is: 0x011f
And Vendor ID is: 0x0e6f

When I plug it into my laptop and run the program, the circle flases green once and then shuts off. The program doesnt recgonize the controller at all. 

Any suggestions on what I should do?

**Comment by h224h** [comment]
@FranticRain

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
