### ISSUE TITLE
Xbox One Controller Bindings are not correct

### ISSUE THREAD

**Issue by afanning21** [360Controller/360Controller#630]
I downloaded the 360controller and when I plugged it in and tried to play Fortnite on my mac with the controller, A was B, B was X and X was A. Along with that, Right Stick was RT and Left Stick was LT. I fixed the key bindings for A, B, and X but there is no RT or LT binding in system preferences which makes the game unplayable. Can anyone help?

**Comment by FranticRain** [comment]
https://github.com/360Controller/360Controller#my-controller-doesnt-work-with-a-game
