### ISSUE TITLE
Switch Pro Controller

### ISSUE THREAD

**Issue by Erid** [360Controller/360Controller#632]
Hi, not sure if I'm doing this the right way, but I was trying to use the Switch Pro Controller as an Xbox 360 in order to play Rocket League.

Here is the information required according to the Readme:
```
Product ID: 0x2009
Vendor ID: 0x057E
```

Just in case, all the information provided from the System Report:
```
 Pro Controller:
  Address:	7C-BB-8A-FC-02-8C
  Major Type:	Peripheral
  Minor Type:	Peripheral
  Services:	Wireless Gamepad, Wireless Gamepad, Wireless Gamepad PnP Server
  Paired:	Yes
  Configured:	Yes
  Connected:	Yes
  Manufacturer:	Broadcom (0x7, 0x2105)
  Firmware Version:	0x0001
  Vendor ID:	0x057E
  Product ID:	0x2009
  Class of Device:	0x05 0x02 0x0508
  AFH:	On
  AFH Map:	F899700000807F
  RSSI:	-39
  Role:	Master
  Connection Mode:	Sniff Mode
  Interval:	15 ms
  Host Connectable:	No
  EDR Supported:	Yes
  eSCO Supported:	Yes
  SSP Supported:	Yes
```

**Comment by FranticRain** [comment]
This driver is for controllers that are supported by Xbox consoles only. You may have seen that Switch fight stick that got accepted and gotten the wrong idea. That fight stick supported Xinput and worked with Xbox consoles. This, unfortunately, does not. That means that it will not be supported by this project. Sorry.
