### ISSUE TITLE
Xbox One S (White) controller guide button gets stuck

### ISSUE THREAD

**Issue by pbhogan** [360Controller/360Controller#642]
This just seems to have started with the latest driver release. When the guide button is pressed it gives an input of 1, but then never stops until the controller is reconnected.

This is the Xbox One S (white, bluetooth) controller running the latest firmware. I have confirmed it does not happen with the regular black Xbox One controller or the Xbox One Elite controller.

**Comment by FranticRain** [comment]
This should be fixed in the latest release.
