### ISSUE TITLE
Controller is recognized in the menu but when I press buttons there is no response

### ISSUE THREAD

**Issue by azianboi94** [360Controller/360Controller#645]
Product ID: 0x543a
Vendor ID: 0x24c6

Using 360Controller 0.16.6
macOS High Sierra Version 10.13.4

Let me know if there's anything I'm missing. Thanks a bunch!

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.

Sorry. :(
