### ISSUE TITLE
360Controller 0.16.6 no force feedback 

### ISSUE THREAD

**Issue by Gcenx** [360Controller/360Controller#646]
After updating to the new driver on High Sierra 10.13.4, force feedback no longer works in any game that it worked in before the upgrade.

The Controller is the official Xbox One S controller, once I downgraded back to 0.16.5 force feedback is working again.

The controller has the latest firmware installed after the driver upgrade to ensure that was not an issue, but it still did not work only downgrading the driver would bring back force feedback

**Comment by Jackylv1981** [comment]
the same issue on Xbox one controller on macOS 10.13.4 :(

**Comment by FranticRain** [comment]
This should be fixed in the latest release.
