### ISSUE TITLE
0.16.6 Speedlink Torid vibration no longer works

### ISSUE THREAD

**Issue by Diamondog36** [360Controller/360Controller#647]
After updating to 0.16.6, vibration no longer woks in games, at least with this gamepad. While testing it in the driver preferences, I noticed than it doesn't vibrate when pressing RT and LT, as it should. Emulators don't even recognize the rumble feature of the gamepad. At first I thought it was a hardware issue, but I tested it on Windows (and even on PS3!) and it works fine there. I don't have another gamepad to test, so, I don't know if a change broke some gamepads, or all of them. It is USB-wireless gamepad, so, it shouldn't have been affected by the removal of wireless gamepads support, I think.
I'm on macOS 10.13.4 and I won't risk downgrading to 0.16.5 after reading what happened to other people trying to install 0.16.5 on macOS 10.13.3!

**Comment by FranticRain** [comment]
Hmm. Probably happened because of my lazy build to get 0.16.6 out the door, but I don't know why that would have happened. Sorry. I'll look into it if I get some time.

**Comment by FranticRain** [comment]
This should be fixed in the latest release.

**Comment by joobei** [comment]
My torid gamepad isn't even recognized. @Diamondog36 can you please confirm if Speedlink Torid works?

**Comment by Diamondog36** [comment]
Yes, it works for me. I'm using 0.16.10. This is an old thread by the way it was closed months ago, I was asking about an older version. You should create a new issue about this, not resurrect older issues.

> My torid gamepad isn't even recognized. @Diamondog36 can you please confirm if Speedlink Torid works? It's not listed under supported devices in the wiki.

**Comment by joobei** [comment]
> This is an old thread by the way, it was closed months ago, I was asking about an older version. You should create a new issue about this, not resurrect older issues.

I cannot open a new issue for a controller that is not in the list of officially supported controllers. That is why I asked you here.
