### ISSUE TITLE
FORTNITE

### ISSUE THREAD

**Issue by hazardh7** [360Controller/360Controller#650]
when playing footnote the LT button doesn't work and I can't play any games as it spins me round in circles someone please help

**Comment by hazardh7** [comment]
Thankyou

**Comment by givanse** [comment]
I'm seeing the same behavior with Fortnite. The inputs work correctly on system preferences, but not with Fortnite.

 - MacOS High Sierra 10.13.6
 - Xbox One Elite

> we can recommend that you use the "Pretend to be an Xbox 360 Controller" option in the "Advanced" menu for better game compatibility

That worked.
