### ISSUE TITLE
PDP Wired controller for Xbox one - no device found 

### ISSUE THREAD

**Issue by bitfinity** [360Controller/360Controller#652]
Installed twice - privacy and security settings etc. I'm a software and devops guy.

<img width="489" alt="screen shot 2018-04-26 at 8 24 23 pm" src="https://user-images.githubusercontent.com/209595/39343072-d4cf4d3c-498f-11e8-924b-22e3d0363251.png">

<img width="462" alt="screen shot 2018-04-26 at 8 22 24 pm" src="https://user-images.githubusercontent.com/209595/39343056-b908e18a-498f-11e8-93f5-1e7e38c5f60e.png">

**Comment by bitfinity** [comment]
Tried to compile latest Xcode as well but the USB header file no longer the same.

**Comment by MaddTheSane** [comment]
The changed headers is a known issue (#127). It will take a re-write of the drivers to get it building using newer Mac OS X SDKs.

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
