### ISSUE TITLE
Disable default OSX response on Xbox One Wireless (Bluetooth)

### ISSUE THREAD

**Issue by dnicecar** [360Controller/360Controller#654]
Hi, I know the bluetooth version of XBox One Wireless controller is already supported by default. Therefor driver not detecting it while connecting to bluetooth. 
But the problem is when playing games, these default behaviour that OSX react to the controller is still there and interfere with the gaming. (A button will act like left mouse button, and will make whole OSX freeze when i hold it in a game)
Is there a way to disable the reaction of OSX itself to the controller?

Thanks.
dnicecar

**Comment by FranticRain** [comment]
We can't do that with this driver. That is outside the scope of this driver. Either turn off Bluetooth on your device when using the controller, or have the operating system forget the controller, so that it doesn't automatically connect.
