### ISSUE TITLE
INJUSTICE FightStick for Xbox360

### ISSUE THREAD

**Issue by heatershield** [360Controller/360Controller#656]
I imagine it's just not supported as of yet.

![screen shot 2018-04-27 at 9 20 01 pm](https://user-images.githubusercontent.com/25674450/39390316-c821f270-4a60-11e8-826a-c60e7edab018.png)
![screen shot 2018-04-27 at 9 20 46 pm](https://user-images.githubusercontent.com/25674450/39390322-e0f5b6a6-4a60-11e8-8a19-65138bee6514.png)

**Comment by FranticRain** [comment]
This device is in the latest build.
