### ISSUE TITLE
Mac won't shown down or restart

### ISSUE THREAD

**Issue by olee0501** [360Controller/360Controller#657]
When restarting or shutting down, the screen gets black (LED backlight on) and the cursor is visible and movable, the iMac won't shut down, even after hours. Force reboot necessary.
After a long discussion with Apple support, we found, that the (Kernel) files of the 360controller are responsible for this issue. Deleting them solved the problem, but now of course I can't connect my XBox One Controller anymore.

Hardware: iMac 5K 2017 3,4 Ghz Intel Core i5, Radeon Pro 570, 8GB 2400MHz DDR4, SSD Flash Storage 256 GB.
MacOS High Sierra 10.13.4

Responsible files located in /Library/Extensions:
360Controller.kext
Wireless360Controller.kext
WirelessGamingReceiver.kext

Responsible files located in /Library/LaunchDaemons:
com.mice.360Daemon.plist

Responsible files located in System/Library/Extensions:
360Controller.kext (no file, just symlink)

[responsibleFiles.zip](https://github.com/360Controller/360Controller/files/1960327/responsibleFiles.zip)

**Comment by FranticRain** [comment]
What version of the driver were you using? 0.16.6 is supposed to fix issues like these.

**Comment by olee0501** [comment]
I'm using 0.16.6

**Comment by FranticRain** [comment]
Does this issue occur with the controller unplugged? It's likely caused by the driver refusing to free itself on a shutdown because it believes that it is still in use. You can either disable the driver in the preference pane or unplug the controller, and your computer should shut down correctly. Is that accurate?

**Comment by olee0501** [comment]
It works now, even with Controller plugged in. Maybe I didn't wait long enough on my restart-try 4 hours ago, I waited about 15 seconds. So probably I had 0.16.5 before. Thanks for your fast answering!
