### ISSUE TITLE
A 3rd Party XBOX Controller Not Supported - Product ID:0x02a0   Vendor ID:0x0e6f

### ISSUE THREAD

**Issue by pw2393** [360Controller/360Controller#661]
PDP Wired Controller for Xbox One - Midnight Blue:

  Product ID:	0x02a0
  Vendor ID:	0x0e6f
  Version:	1.0f
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
