### ISSUE TITLE
3rd party controller not supported

### ISSUE THREAD

**Issue by hroarbye** [360Controller/360Controller#662]
I have a Mayflash MAGIC-NS dongle, that can act as xinput for a nintendo switch pro controller and other controllers. I does not register input in the 360Controller though. Only got it working on windows. Hope someone can add it to the next build :)

Product ID: 0x18d3
Vendor ID: 0x0079

(Btw. Have been using a mayflash dongle for Wii U pro controller a few years, and that works great with 360Controller)

**Comment by FranticRain** [comment]
This device is in the latest build.
