### ISSUE TITLE
3rd party controller not supported

### ISSUE THREAD

**Issue by saltydeezee** [360Controller/360Controller#664]
PDP Wired Controller for Xbox One - Verdant Green:

  Product ID:	0x02a1
  Vendor ID:	0x0e6f
  Version:	1.0f
  Serial Number:	000071FF1DF3C142
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0x14100000 / 11
  Current Available (mA):	500
  Extra Operating Current (mA):	0

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.

Labeling this as a new device in case the IOUSBHost issue gets fixed, as it isn't in the Info.plist.
