### ISSUE TITLE
Hori Fighting Commander ONE Xbox version

### ISSUE THREAD

**Issue by bupp** [360Controller/360Controller#666]
The Hori Fighting Commander ONE for the Xbox is not detected by the driver. I have attached a screenshot with the controller's details.

To avoid confusion, this is a different controller than the one mentioned in issue #622.

<img width="281" alt="hori_fco_info" src="https://user-images.githubusercontent.com/6462104/39768237-b3d8ac56-52b6-11e8-9e00-d2d4cd0d5a80.png">

**Comment by FranticRain** [comment]
This device was added in 0.16.6 https://github.com/360Controller/360Controller/commit/7e52ddf134e73ef8303e6a25c903415d6192b06b
