### ISSUE TITLE
Third Party Controller Found By Mac, Does Not Appear in Preference Pane

### ISSUE THREAD

**Issue by MBartner** [360Controller/360Controller#685]
### Type of Controller
Xbox 360

### Connection Method
Wired

### Device Name and Info
>Device Name: TSZ360 Pad
<br/>Product ID: 0x0201
<br/>Vendor ID: 0x0e6f

### Response of Controller
Guide button lights up once on connection.

### Response in Preference Pane
Does not appear in preference pane.

### Detailed Explaination of Issue
I looked through the controller plist, and saw this controller product and vendor id already exist. However, I do remember when I first tried to install the driver, I accidentally clicked passed something that wanted me to give permission to something else (sorry for vagueness). When I uninstalled and reinstalled the driver, this prompt did not come back unfortunately.

**Comment by FranticRain** [comment]
[You should find some instructions on how you can get back to that permission prompt in the README here.](https://github.com/360Controller/360Controller#installation) Let me know if that fixes your issue.

**Comment by MBartner** [comment]
Did the trick. Sorry for my incompetence haha. Thank you.

**Comment by FranticRain** [comment]
No problem! Glad to hear that it is working.
