### ISSUE TITLE
Updating macOS 10.13.4 -> 10.13.5 and Xcode 9.3.1 -> 9.4 results in controller no longer being found

### ISSUE THREAD

**Issue by nathanielwasson** [360Controller/360Controller#693]
### Type of Controller
Xbox 360

### OS Version
10.13.5

### Driver Version
0.16.8

### Connection Method
Wired

### Device Name and Info
>Device Name: Xbox 360 Pro Ex
<br/>Product ID: 0x281f
<br/>Vendor ID: 0x20d6

### Response of Controller
When controller is plugged into USB port, lights 1 and 4 flash simultaneously once, then all 4 (1/2/3/4) lights come on simultaneously for a longer period (maybe 1 second) before all lights go out (simultaneously) and stay off for good.

### Response in Preference Pane
The preference pane never recognizes the controller. 'No device found'

### Detailed Explaination of Issue
Before updating from 10.13.4, my wired 360 controller (see above Device Name and Info) worked perfectly.  I played Fortnite with it several days ago.
After updating to 10.13.5 and updating Xcode to version 9.4 (from 9.3.1), my controller is no longer recognized in the Preference Pane.

**Comment by FranticRain** [comment]
See notes in pull request for comments on this issue.
