### ISSUE TITLE
Afterglow for xbox one won't work

### ISSUE THREAD

**Issue by jackboschma** [360Controller/360Controller#695]
### Type of Controller
xbox one afterglow wired controller (has headphone jack)

### OS Version
high sierra 10.13.4

### Driver Version
360 controller 0.16.8

### Connection Method
i have tried cable that come with the controller and a random micro usb

### Device Name and Info
>Device Name: Afterglow Prismatic Wired Controller for Xbox One
<br/>Product ID: 0x02b3
<br/>Vendor ID: 0x0e6f

### Response of Controller
the afterglow of the controller lights up. no other response 

### Response in Preference Pane
no response 

### Detailed Explaination of Issue
i don't know much about computers and code stuff i just want help to get this to wok so i can play a game n my mac. I have spend probably three hours trying this and using every suggestion  i can find. I have tried restarting my mac book and reinstalling the driver with the controller unplugged. However every time I open the driver it would say no device found. I would really appreciate any help you can give me.  One thing I forgot. When I go to about this mac, then system report it show us up under usb.

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.

**Comment by jackboschma** [comment]
Ok thank you.
