### ISSUE TITLE
Xbox One controller is not recognised

### ISSUE THREAD

**Issue by FroggyPower1** [360Controller/360Controller#696]
### Type of Controller
Replace this text with:  Xbox One

### OS Version
Im running High Sierra, version 10.13.4 (17E202)

### Driver Version
\<NONE PROVIDED\>

### Connection Method
\<NONE PROVIDED\>

### Device Name and Info
>Device Name: Xbox Wireless Controller
<br/>Product ID: 0x02ea
<br/>Vendor ID: 0x045e  (Microsoft Corporation)

### Response of Controller
\<NONE PROVIDED\>

### Response in Preference Pane
\<NONE PROVIDED\>

### Detailed Explaination of Issue
\<NONE PROVIDED\>

If you could, please reply as soon as possible.
Thanks,
FroggyPower1

**Comment by FranticRain** [comment]
Can you please run `sudo kextutil /Library/Extensions/360Controller.kext` in your terminal and let me know what the output is?

**Comment by FroggyPower1** [comment]
How would I open the terminal? Sorry, I'm not an expert in controller science.

**Comment by FranticRain** [comment]
Applications -> Utilities -> Terminal. Or you can use spotlight search.

**Comment by FroggyPower1** [comment]
otice: /Library/Extensions/360Controller.kext has debug properties set.
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents

**Comment by FroggyPower1** [comment]
*Notice

**Comment by FroggyPower1** [comment]
Then this, "Calvins-MacBook-Air:~ calvinchee$"

**Comment by FranticRain** [comment]
Okay, when connecting your controller now, does your controller light up properly, or does it still not light up?

**Comment by FroggyPower1** [comment]
The Xbox logo lights up when i pair it with my computer, but the driver will not recognise it.

**Comment by FranticRain** [comment]
Wait a minute, you are pairing via Bluetooth? And you neglected to mention this, even though the issue template explicitly had a section describing connection method? This driver doesn't support controllers operating via Bluetooth. The Xbox One controller follows a standard protocol for HID devices which means that it doesn't need a driver. Xbox One controllers are only supported via the driver via USB.

**Comment by FroggyPower1** [comment]
Oh, so sorry for using your time. Really, I am.

**Comment by FranticRain** [comment]
[Relevant section of the README regarding this.](https://github.com/360Controller/360Controller#xbox-one-controllers-connected-with-bluetooth) Additionally, Bluetooth controllers do not show up in the preference pane since they don't support the settings that the driver provides.

**Comment by FroggyPower1** [comment]
Sry
