### ISSUE TITLE
PDP controller (brand) - Not found / detected. Kernel error on conenction?

### ISSUE THREAD

**Issue by JoshTickles** [360Controller/360Controller#700]
### Type of Controller
Xbox One 

### OS Version
10.13.4 (didn't work)
10.13.2 (didn't work)
10.14 (didn't work) - Current installed.

### Driver Version
Version 0.16.6
Version 0.16.8 - Currently installed.

### Connection Method
Wired with stock cable.
Replacement cables tried.

### Device Name and Info
PDP Wired Controller for Xbox One - Crimson Red:

  Product ID:	0x02a2
  Vendor ID:	0x0e6f

### Response of Controller
None.

### Response in Preference Pane
None

### Detailed Explanation of Issue

Have tried with no working result:
> Other OS versions (as above)
> Other driver versions (as above)
> Different cables.
> Loading the kext manually 
```
$ sudo kextload /Library/Extensions/360Controller.kext -v 2

Requesting load of /Library/Extensions/360Controller.kext.
/Library/Extensions/360Controller.kext loaded successfully (or already loaded).
```

> Checking Kernel logs when connecting device. 
`
PDP Wired Controller for Xbox One - Crimson Red: family specific matching fails
`
All of the above was tested on different macOS machines also. 
--

Let me know if you need me to try anything further.

Cheers.

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code.
