### ISSUE TITLE
Controller shows up in System Info but not 360 Preferences

### ISSUE THREAD

**Issue by brant-moore** [360Controller/360Controller#707]
Wired Xbox 360

10.13.5

.16.8

Wired - Has trip connection as well

Mad Catz Ghost Recon FS GamePad:
Product ID:0xf021
Vendor ID:0x1bad

LEDS light up and stay on and center button light flashes when connected.

No devices found. When first clicking 360 preferences item1 shows in drop down then quickly turns into no devices found.

The controller seems to work and shows up in system info under USB, but doesnt show up in system preferences. I've restarted and uninstalled then reinstalled the driver but the same thing happens every time. This is all new so I'm really not sure what to do at this point.
Any help is appreciated.

One other thing..In system info it shows up under usb 2.0 bus, then hub, then the controller name is under it.

**Comment by FranticRain** [comment]
Here's a build with that device added to the plist. It should work correctly now.

[Install360Controller.pkg.zip](https://github.com/360Controller/360Controller/files/2143577/Install360Controller.pkg.zip)
