### ISSUE TITLE
Different Vibration intensity on Xbox One S LT/RT

### ISSUE THREAD

**Issue by wind50321** [360Controller/360Controller#712]
### Type of Controller
Xbox One S

### OS Version
Mac OS 10.11.6

### Driver Version
0.16.8

### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID:
<br/>Vendor ID:

### Response of Controller
Guide button lights up.
Different Vibration intensities on LT/RT.

### Response in Preference Pane
All buttons react.

### Detailed Explaination of Issue
Different Vibration intensities on LT/RT. Testing video:
https://youtu.be/kV5RKR5m6yw

I removed 0.16.8 and installed 0.16.7.
When I pressed LT/RT, the icons in setting panel lighted up, but the controller didn't vibrate.

If I connect the controller to my Mac via Bluetooth, it doesn't appear in the 360 controller panel.
It show no device found. Does this tool support Bluetooth connection?

**Comment by FranticRain** [comment]
There are two separate motors in Xbox controllers. One is large and one is small. What you are experiencing is intended behavior. The left trigger activates the big motor, while the right trigger activates the small motor.

As for Bluetooth support, I will refer you to the README: "Bluetooth capable Xbox One controllers (released after August 2016) are natively supported by macOS without the use of this driver. However, installing this driver will enable force feedback (which is not natively supported) and allow you to plug the controller in via USB." The force feedback thing is not entirely true. I'm not sure it was ever deemed "working."
