### ISSUE TITLE
Wireless 360 Controller not connectingon High Sierra with Driver properlly installed.

### ISSUE THREAD

**Issue by mtraps** [360Controller/360Controller#723]
### Type of Controller
Replace this text with:  Xbox 360

### OS Version
High Sierra
### Driver Version
360Controller 0.16.8

### Connection Method
Replace this text with: Wireless Adapter

### Response of Controller
The 4 lights flash but player 1 never connects. Bateries are brand new and tested

### Response in Preference Pane
No Devices found

### Detailed Explaination of Issue
I have installed the 360ControllerInstall_0.16.8.dmg allowed the user in Security and privacy. I dont know what I am missing. Thanks for the help!

**Comment by FranticRain** [comment]
The Xbox 360 wireless controller is not supported on 10.11+ thanks to a rewrite of the macOS USB kernel. Installing the wireless controller driver on a system running these versions of the OS could cause potential issues with your Mac, such as kernel panics.

**Comment by mtraps** [comment]
Thanks for getting back so quickly man. So is it best to just buy the wired Xbox 360 controller? 

Cheers,

Michael Trapani
[p] 905.252.4264

**Comment by FranticRain** [comment]
Either a wired Xbox 360 controller on a wired Xbox One controller will work.

**Comment by mtraps** [comment]
Hey Drew, I just bought a wired controller and it doesnt seem to connect still.

**Comment by mtraps** [comment]
Any tips would be much appreciated. I feel like I have tried everything.

**Comment by FranticRain** [comment]
What are your vendor and product IDs? Does your controller appear in the system report? I need you to do all of the suggested debugging steps before I can help you.

**Comment by mtraps** [comment]
Hello, I am not sure about product ID or where to find that.

This is the exact controller I purchased:
https://www.amazon.ca/gp/product/B079BH9MMV/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1 <https://www.amazon.ca/gp/product/B079BH9MMV/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1>

And yes it shows up in system report as Inno game pad.

**Comment by FranticRain** [comment]
It's literally right there in the system report. When you click on the device it gives you the product and vendor IDs at the bottom of the window.

From the README: https://github.com/360Controller/360Controller#how-do-i-find-my-vendor-id-and-product-id

**Comment by mtraps** [comment]
Oh! Please see below:

Product ID:	0x028e
  Vendor ID:	0x045e  (Microsoft Corporation)
  Version:	1.10
  Serial Number:	0000001
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Inno GamePad..
  Location ID:	0x14230000 / 37
  Current Available (mA):	500
  Extra Operating Current (mA):	0

**Comment by FranticRain** [comment]
Well. I'm sorry to say this, but this is what we refer to as a "counterfeit" Xbox 360 controller. They imitate the Xbox 360 controller but do not actually follow the same initialization and packet layout of the real thing. We don't support them since they do not support the standard layout. Please try to get a refund and do not support these counterfeit knockoffs of these controllers.

**Comment by mtraps** [comment]
Okay, thanks for being honest.

I will buy a real one then or if you have one you can recommend that would be appreciated.

I also have an Xbox 1 and 360 controller both of which are wireless.

**Comment by FranticRain** [comment]
Just get a micro USB cable and plug the Xbox One controller in! Xbox One controllers are awesome because they become wired controllers when you plug them in. That's all you have to do.

**Comment by mtraps** [comment]
WHAT, don’t tell me its that simple. I don’t need to use my wireless controller hub?

**Comment by FranticRain** [comment]
Nope! Just plug it in.

**Comment by mtraps** [comment]
Hi sorry, I’m aware I’m being a pain in the ass and maybe I’m just not meant to game on my computer but it still isn’t working. I have it plugged in via Micro USB (xbox 1 wireless controller) and it just flashes and doesnt get recognized by system report. Batterys are brand new micro, have tried 3 different Micro USB cables too.

**Comment by mtraps** [comment]
I got it! It was the security issue, although I unblocked it before I had to further allow it. Thanks so much for your help.
