### ISSUE TITLE
Unsupported third-party device 0x02b2 / 0x0e6f

### ISSUE THREAD

**Issue by windytan** [360Controller/360Controller#725]
### Type of Controller
Xbox One
(third-party USB controller)

### OS Version
macOS 10.13.6

### Driver Version
I tested:
* 0.16.8 (having first removed the /System/Library/Extensions/360Controller.kext because the OS wouldn't boot up)
* A 0.16.5 installer posted by FranticRain to another thread to fix the above bootup issue

### Connection Method
Wired

### Device Name and Info
* Device Name: AtPlay Wired Controller for Xbox One (GS-048-114)
* Product ID: 0x02b2
* Vendor ID: 0x0e6f

### Response of Controller
No buttons light up, and no vibration.

### Response in Preference Pane
In the Preference Pane, it says 'No devices found'.

### Detailed Explaination of Issue
This third-party controller is not recognized by the driver or any game. But it can be seen in System Information, under the USB 3.0 bus as "AtPlay Wired Controller for Xbox One".

**Comment by FranticRain** [comment]
Here's a build with the device added. Sorry about the zip situation, that's just a github limitation. [Install360Controller.pkg.zip](https://github.com/360Controller/360Controller/files/2251983/Install360Controller.pkg.zip)
