### ISSUE TITLE
Macbook broken after installing .dmg file

### ISSUE THREAD

**Issue by vmunv** [360Controller/360Controller#730]
After my computer restarted for the software, I can log in to my user profile but the bar simply loads all the way but never actually logs in (I waited an hour for it to do something but nothing ever happened).... I'm got high sierra so I'm pretty sure I meet the system requirements for the download....

**Comment by actionadam90** [comment]
On one of my Macs it worked any my computer was fine but on another it broke

**Comment by vmunv** [comment]
so apparently the drive became unmounted or something so i just had to remount and then everything worked fine

**Comment by bpcatsolton** [comment]
Hi !
My MacBook Pro 2018 also has the same problem for the boot after installing the drivers ;-(
How do you manage to "remount the drive", please ?
What kind of commands ?

**Comment by ahokinson** [comment]
I apologize for not seeing this earlier. I was able to safe boot and believe it or not @bpcatsolton's suggestion to reselect the boot drive actually worked... I have since completely removed the package after getting back into my system.

**Comment by FranticRain** [comment]
This should be resolved in [0.16.9](https://github.com/360Controller/360Controller/releases/tag/v0.16.9). Further discussion has been moved to #698.
