### ISSUE TITLE
GameSir G3S controllers freeze "System Preferences" and "loginwindow" app 

### ISSUE THREAD

**Issue by s-tsarenko** [360Controller/360Controller#752]
### Type of Controller
GameSir G3S (works with Windows like original Xbox 360 wired controller)

### OS Version
macOS 10.13.6 

### Driver Version
360Controller 0.16.9

### Connection Method
Wireless Adapter, but this controllers detected as Xbox 360 Wired Controller (Wired)

### Device Name and Info
Wired or wireless connection
>Device Name: Controller
<br/>Product ID: 0x028e
<br/>Vendor ID: 0x045e

Only adapter connected
>Device Name: Gamesir-G3v 1.00
<br/>Product ID: 0x033d
<br/>Vendor ID: 0x05ac

### Response in Preference Pane
One of controllers works fine, second freeze this window.

### Detailed Explaination of Issue
I have 2 gamepads, both gamepads works like original xbox360 gamepad with Windows.
This gamepads can connect with wireless adapters, let we call it "controller A" and "controller B" and "adapter 1" and "adapter 2". So when I connect "controller A" with "adapter 1" all works perfect. I can reboot with this adapter, all works fine.
If i disconnect "controller A" and try to connect "controller B" applications "System Preferences" and "loginwindow" are freezing, also Preference Pane are not responding. I have this issue if I use "controller B" and "adapter 1" and if I connect "controller B" and "adapter 2".
If connected "adapter 1" and "controller A" and Preference Pane are opened I can connect "adapter 2" and "controller B", but I have some freeze if I switch to second controller in Preference Pane.
Also if I connect adapter 2 before boot than I got black screen after boot, so looks like loginwindow freeze, but with adapter 1 i don't have this issue.
When I connect adapter 2 after login all works fine, I can lock screen and login again, but if I try to connect any controller to this adapter "System Preferences" and "loginwindow" freezing. 
Wired connection for both controllers. When connect any of this controllers with a cord I can't see this controller in Preference Pane, but led on controller show that controller connected. If I unplug and plug again I see controller in Preference Pane, but Preference Pane not responding, "System Preferences" and "loginwindow" are freezing too.

**Comment by FranticRain** [comment]
This controller is not supported by official Xbox hardware. As such, it's support is outside the scope of this driver. We cannot and will not support this driver.
