### ISSUE TITLE
MacOs Driver location for manual installation

### ISSUE THREAD

**Issue by MeatyChan** [360Controller/360Controller#754]
### Type of Controller
Xbox 360

### OS Version
High Sierra

### Driver Version
Have not installed yet

### Connection Method
wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID:
<br/>Vendor ID:

### Response of Controller
lights up once, and only once.

### Response in Preference Pane
no, have not installed drivers

### Detailed Explaination of Issue
does anyone know where the file location for the 360 drivers are on Mac? I'd like to install them manually. thanks :)

**Comment by FranticRain** [comment]
`/Library/Extensions`
https://github.com/360Controller/360Controller#developer-info
