### ISSUE TITLE
PowerA Xbox One Controller Device Not Found

### ISSUE THREAD

**Issue by farrellse18** [360Controller/360Controller#757]
I need help with this I saw that is said it was not compatible, but will it ever be. I have a PowerA controller i just bought it I did all the set ups step by step and i tried to do some of the coding that was in so feeds. Now this issue is mainly around the PowerA Xbox One controller. How can I set it up or are you working on patching it so PowerA is compatible?

**Comment by farrellse18** [comment]
Product ID: 0x581a
Vendor ID: 0x24c6

**Comment by FranticRain** [comment]
PDP and PowerA Xbox One controllers are incompatible with macOS 10.11+ thanks to a rewrite of the macOS USB kernel. We cannot resolve this issue. It is a bug in Apple's core OS code. There are currently no plans to proceed with a rewrite of the driver.

**Comment by tomlagier** [comment]
Just wanted to note that with the 1.0.0 line, the PowerA controller works.

**Comment by NilsIrl** [comment]
Has this issue been reported to Apple? Where can I find the discussion/ticket (whatever apple's public bug tracker is)?
