### ISSUE TITLE
version numbers broken

### ISSUE THREAD

**Issue by core-code** [360Controller/360Controller#759]
all version numbers of all components of the driver
360Daemon.app
360Controller.kext
Wireless360Controller.kext
WirelessGamingReceiver.kext
Pref360Control.prefPane

show the version number
1.0.0d15

(in CFBundleShortVersionString and CFBundleVersion)
while it should probably show the ACTUAL version number
0.16.9

furthermore the 
	<key>LSMinimumSystemVersion</key>
	<string>10.9</string>

key should probably be increased to 10.11 as this is the actual requirement.

**Comment by FranticRain** [comment]
Unfortunately, having the "macOS Deployment Target" set to 10.9 is crucial to having this thing build, so I opted for a custom environment variable instead. This should all be reflected in a 0.16.10 release, whenever that happens. Changes have been pushed to master.

**Comment by core-code** [comment]
thanks!
