### ISSUE TITLE
Not functioning on Mac OS Mojave (Official Release)

### ISSUE THREAD

**Issue by yamcha67** [360Controller/360Controller#760]
### Type of Controller
Xbox One

### OS Version
Mac OS Mojave 10.14 Offical Release

### Driver Version
Version 0.16.9

### Connection Method
Wired

### Device Name and Info
Controller:
Product ID: 0x02ea
Vendor ID: 0x045e  (Microsoft Corporation)

### Response of Controller
The controller vibrates when connected but doesn't function on Steam or OpenEmu. (This worked on beta versions of Mojave and earlier versions of Mac OS)

### Response in Preference Pane
The controller isn't detected in the 360Controller Preference Settings.

### Detailed Explaination of Issue
After installing the official release of Mac OS Mojave 10.14 the controller doesn't seem to be detected on the 360Controller preference settings. I've tried using the "Enable Driver" option as well but it made no difference. I've also tried re-installing but the problem still persists.

**Comment by FranticRain** [comment]
I just tested this exact controller on a late 2013 rMBP and cannot reproduce. Marking this invalid.
