### ISSUE TITLE
Analog sticks use signed not unsigned values

### ISSUE THREAD

**Issue by edmcintosh** [360Controller/360Controller#764]
### Type of Controller
Xbox One [Elite]

### OS Version
10.12.6

### Driver Version
0.16.9

### Connection Method
Wired

### Device Name and Info
>Device Name: N/A in System Report
<br/>Product ID: 045e
<br/>Vendor ID: 02e3

### Response of Controller
All buttons and triggers are fine. Analog sticks report signed values (min 80, neutral ff/00, max 7f) [using the HIDTest utility supplied with https://github.com/Maschell/HIDtoVPADNetworkClient] rather than the expected unsigned ones (min 00, neutral 80, max ff).

### Response in Preference Pane
Stick position reported correctly.

### Detailed Explanation of Issue
Each stick axis seems to affect two bytes. At the extremes they report 0080 and ff7f. The second byte is well-behaved, but is centred on ff/00 rather than 80. The first byte of each pair gives seemingly random values everywhere except fully up/down/left/right.

Is there a way of having the driver report stick positions with 80,80 being the centre? As the first byte of each pair is affected by the stick position (and takes the expected values at each end), what does it mean?

I enclose some of the log produced by HIDTest, with labels about what bytes show what, and what I pressed when.
[HIDTest-log-elite.txt](https://github.com/360Controller/360Controller/files/2451705/HIDTest-log-elite.txt)

**Comment by FranticRain** [comment]
The XINPUT standard says that they should be -32768 to 32767. That's my bible for controller layout.
