### ISSUE TITLE
英文看不懂中文说不来

### ISSUE THREAD

**Issue by njroo** [360Controller/360Controller#766]
### Type of Controller
Replace this text with: Original Xbox, Xbox 360, Xbox One, All or N/A

### OS Version
Replace this text with the version of macOS that you are running

### Driver Version
Replate this text with the version or versions of the driver that you are using or have tested

### Connection Method
Replace this text with: Wired, Wireless Adapter, Bluetooth, N/A or more specific method if applicable

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID:
<br/>Vendor ID:

### Response of Controller
Replace this text with information on how the physical controller reacts. Does the guide button light up? Does it vibrate? Etc.

### Response in Preference Pane
Replace this text with information about the controller's reaction in the preference pane. Does the controller appear in the preference pane? Do all of the buttons, joysticks, and triggers act as expected?

### Detailed Explaination of Issue
Replace this text with a detailed explaination of your issue. Simply saying "it doesn't work" is a quick way to ensure that your issue is never fixed. Without detailed information on your specific issue, we cannot fix your issue. Including as much information as possible in this section increases the likelyhood of getting your issue quickly and effectively resolved.

**Comment by neo954** [comment]
Hah, @FranticRain. You added a weird tag in this issue.

The subject of this issue can be literally translated to the following.
> I cannot read English, I cannot say it in Chinese.

BTW, I don't see there is any useful information provided in this issue.

**Comment by FranticRain** [comment]
Well, the label worked, didn't it? Haha.

If there's nothing here to work off of, I'm just going to close it down. Not really anything else we can do here.
