### ISSUE TITLE
Kernel Crash (com.apple.iokit), Repeatedly Tested

### ISSUE THREAD

**Issue by DBankston** [360Controller/360Controller#767]
### Type of Controller
Xbox 360 Wireless

### OS Version
High Sierra 10.13.6, 17G65

### Driver Version
0.16.9

### Connection Method
Wireless Adapter, Microsoft Official

### Device Name and Info
Device Name: XBox 360 Wireless Receiver for Windows
Product ID:	0x0719
Vendor ID:	0x045e  (Microsoft Corporation)

### Response of Controller
Zero issues using the controller. Functions fine across all steam games and emulators. Crash occurs on computer sleep after kext has been loaded and used. Same results after using for 5 hours or 5 seconds.

### Response in Preference Pane
All buttons/joysticks function properly, including remapping.

### Detailed Explaination of Issue
Crash report generated by computer for sending to Apple:

[Crash Report.docx](https://github.com/360Controller/360Controller/files/2454595/Crash.Report.docx)

Plugged in and loaded for the time it took me to grab the Product/Vendor IDs. Posted issue and put to sleep, instacrash. New crash report: 

[Crash Report 2.docx](https://github.com/360Controller/360Controller/files/2454603/Crash.Report.2.docx)

**Comment by FranticRain** [comment]
Short answer: You are using an unsupported configuration of 360Controller. Wireless Xbox 360 Controllers do not work with this driver ever since macOS 10.11. This is not a valid issue.

Long answer: It seems like the wireless kexts snuck back in to the latest release and need to be removed.
