### ISSUE TITLE
Please add support for Hori Classic Controller for Nintendo Switch

### ISSUE THREAD

**Issue by neo954** [360Controller/360Controller#775]
### Type of Controller
Hori Classic Controller for Nintendo Switch - The Legend of Zelda
https://www.hori.jp/products/nsw/classic_controller_zelda

### OS Version
macOS 10.13.6

### Driver Version
0.16.10

### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: `HORIPAD S`
<br/>Product ID: `0x00dc`
<br/>Vendor ID: `0x0f0d`

### Response of Controller
Nothing happened

### Response in Preference Pane
Nothing was shown

### Detailed Explanation of Issue
For now, nothing is working. If someone add the mentioned Product ID and Vendor ID into the driver, I can help to do some testing.

**Comment by FranticRain** [comment]
This controller is not supported by official Xbox hardware. As such, its support is outside the scope of this driver. We cannot and will not support this controller.

**Comment by neo954** [comment]
@FranticRain, I open this issue just because on their official website, they are the end user to install the official Xbox 360 driver for Windows support. Thus, I think there is some relationship.

Thanks for your response, anyway.

**Comment by FranticRain** [comment]
This wouldn’t be the first time that Hori has done this with a Switch controller, so I’ll add this when I get a chance and you can let me know if it works. 

My Japanese isn’t very good, so I didn’t spend much time trying to read the page for that information.

**Comment by neo954** [comment]
I do not understand Japanese either. I use Chrome browser and Google translate to read the web page.

**Comment by FranticRain** [comment]
Here's a build with the device added.

[Install360Controller.pkg.zip](https://github.com/360Controller/360Controller/files/2498255/Install360Controller.pkg.zip)

**Comment by neo954** [comment]
Hello @FranticRain,

Thanks for your patch and the attached build. With the build attached in your previous comment, the *Hori Classic Controller for Nintendo Switch* worked perfectly fine. All buttons and axes worked.

Thanks again.

**Comment by neo954** [comment]
Hello @FranticRain,

Thanks for your patch and attached build. With the build you attached in your previous comment, the *Hori Classic Controller for Nintendo Switch* worked perfectly fine. All buttons and axes worked.

Thanks again.
