### ISSUE TITLE
SHANWAN Xbox 360 Wired Controller, recognized in Preferences Pane but no input detected. macOS Mojave (10.14)

### ISSUE THREAD

**Issue by cmdr2** [360Controller/360Controller#777]
### Type of Controller
Xbox 360 Wired (Third party).

### OS Version
10.14

### Driver Version
0.16.10

### Connection Method
Wired

### Device Name and Info

>Device Name: Says "Controller" in USB section of System Report. Unity says `SHANWAN Xbox 360 Wired Controller`
<br/>Product ID: 0x028e
<br/>Vendor ID: 0x045e

### Response of Controller
Nothing happens. Works on Windows 8 (recognized as XBox 360 controller by http://html5gamepad.com using Chrome)

### Response in Preference Pane
Controller appears in Preferences Pane as "Xbox 360 Wired Controller (Wired)" but pressing the buttons don't reflect on the screen. Gamepad not recognized by other apps as well (e.g. html5gamepad.com)

### Detailed Explanation of Issue
Looking at Info.plist, an entry with the same vendor and product id is present as "Controller": https://github.com/360Controller/360Controller/blob/master/360Controller/Info.plist#L398

It looks like it gets detected by the Preferences Pane, but no input is picked up on that.

Similarly, a demo project in Unity's `Input.GetJoystickNames()` detects it as `SHANWAN Xbox 360 Wired Controller`, but no input data is received.

I know the hardware is okay because it works on Windows.

Is this the same Apple broken code problem post-10.11?

Thanks

**Comment by FranticRain** [comment]
This controller is a counterfeit device. The product and vendor IDs are that of the Xbox 360 controller. We do not support devices that do not have their own unique product and vendor IDs, as that is a violation of the USB spec, and they do not follow the controller initialization scheme that we use.
