### ISSUE TITLE
Will not recognize wireless controller

### ISSUE THREAD

**Issue by bradels12** [360Controller/360Controller#781]
### Type of Controller
Xbox 360

### OS Version
High Sierra (10.13.6)

### Driver Version
Version 0.16.10

### Connection Method
Wireless Adapter (Microsoft Wireless Receiver)

### Response of Controller
The light on the wireless received does not light up when connected (just stays off). When I click the button on the receiver to pair with the controller, it blinks. When I turn on the controller, the it blinks, when clicking the pair button the lights spin, then goes back to blinking. It does not connect to the receiver. 
Note: when I do this on a windows machine, it connects to the received right away. 

### Response in Preference Pane
Controller does not appear in the preference pane

### Detailed Explaination of Issue
It appears as the drivers is not recognizing the wireless receiver (which I know is possible due to this video (https://www.youtube.com/watch?v=3o-RgAM_GUY).  The receiver is being detected in the system report (XBOX 360 Wireless Receiver for Windows) but does not pair with the controller. 
I am trying to connect this on a new MacBook pro and am connecting the received via a USB to TypeC adaptor (since this Mac does not have any USB ports) - Not sure if that will make a difference or not.

**Comment by FranticRain** [comment]
As of macOS 10.11, Wireless controllers have been unsupported by this driver. This is thanks to a rewrite of the macOS USB kernel. This issue can only be resolved through a rewrite of the driver, which is currently unplanned. Therefore I will be closing this issue, since it is outside the realm of supported devices.
