### ISSUE TITLE
Wired Controller not recognized by driver

### ISSUE THREAD

**Issue by TobiasWaslowski** [360Controller/360Controller#791]
### Type of Controller
Replace this text with: Xbox 360

### OS Version
Mac OS Mojave 10.14

### Driver Version
0.16.10

### Connection Method
Wired

### Device Name and Info

>Device Name: Gamepad for Xbox 360
<br/>Product ID: 0x0301
<br/>Vendor ID: 0x0e6f

### Response of Controller
When connected to the PC, the center button lights up for about one second. After that, nothing happens.

### Response in Preference Pane
The preference pane shows "No Devices found". Pressing the buttons of the controller does nothing.

### Detailed Explaination of Issue
Installed the Tattiebogle driver, found that it wasn't working with my controller and offered little troubleshooting help, so I installed this one (and uninstalled Tattiebogle + rebooted). So far, I have only tested it on the 0.16.10. After checking some of the other issue threads, I tried running 
sudo kextutil /Library/Extensions/360Controller.kext
with the following output:

Notice: /Library/Extensions/360Controller.kext has debug properties set.
Kext rejected due to system policy: <OSKext 0x7fd3ca494f30 [0x7fff98da58e0]> { URL = "file:///Library/StagedExtensions/Library/Extensions/360Controller.kext/", ID = "com.mice.driver.Xbox360Controller" }
Kext rejected due to system policy: <OSKext 0x7fd3ca494f30 [0x7fff98da58e0]> { URL = "file:///Library/StagedExtensions/Library/Extensions/360Controller.kext/", ID = "com.mice.driver.Xbox360Controller" }
Diagnostics for /Library/Extensions/360Controller.kext:
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents

Thank you in advance!

**Comment by FranticRain** [comment]
Please ensure that the driver has been allowed in System Preferences -> Security and Privacy -> General. This approval UI is only present in the Security & Privacy preferences pane for 30 minutes after the alert. Until you approve the kext, future load attempts will cause the approval UI to reappear but will not trigger another user alert.

![Security and Privacy panel in the macOS System Preferences](https://user-images.githubusercontent.com/33877645/33092253-965b666e-cec7-11e7-940d-3e13b46ca500.png)

**Comment by TobiasWaslowski** [comment]
Yep, that did the job. Thanks a lot!
