### ISSUE TITLE
Controller unresponsive

### ISSUE THREAD

**Issue by akisinn** [360Controller/360Controller#801]
### Type of Controller
hori RAP.N hayabusa

### OS Version
10.14.1

### Driver Version
0.16.8

### Connection Method
Wired

### Device Name and Info
>Device Name:RAP.N4
<br/>Product ID:0x00ae
<br/>Vendor ID:0x0f0d

### Response of Controller
No response

### Response in Preference Pane
Controller doesn't appear in preferences pane

**Comment by akisinn** [comment]
Please support this controller

**Comment by FranticRain** [comment]
Here's a build with your device added: [Install360Controller.pkg.zip](https://github.com/360Controller/360Controller/files/2651553/Install360Controller.pkg.zip)
