### ISSUE TITLE
Controller not recognized by other dev tools.

### ISSUE THREAD

**Issue by kerrydh** [360Controller/360Controller#802]
### Type of Controller
Wireless controller for Xbox One, Model #1537

### OS Version
macOS 10.14 (only because it wasn't working on 10.13.latest and I wanted to see if an OS upgrade would help)

### Driver Version
0.16.10

### Connection Method
Wired

### Device Name and Info
Device Name: Controller
Product ID: 0x02d1
Vendor ID: 0x045e  (Microsoft Corporation)
Version:	1.01

### Response of Controller
Yes, the guide button will light up and it will vibrate.

### Response in Preference Pane
The controller appears in the preference pane and the preference pane responded to controller input.  Yes, all of the buttons, joysticks, and triggers act as expected.

### Detailed Explaination of Issue
In addition to the above, I see the "controller" entry in "About this Mac" / System Report / Hardware / USB.  When I run `sudo kextload /Library/Extensions/360Controller.kext` I do not receive any errors.

I am trying to develop a custom program that uses the controller for input.  I am using .Net and version 2.0.5 of the [HidSharp](https://www.zer7.com/software/hidsharp) Nuget package.  This package has a sample test application that will list all HID devices but it does't list my Xbox controller - only the Apple devices (see screenshot below).  Any advice, guidance, or suggestions would be greatly welcomed.

![image](https://user-images.githubusercontent.com/12703213/48781251-870caa00-ec90-11e8-90b6-2fc97154035b.png)

**Comment by FranticRain** [comment]
Unfortunately, this is an issue with your development tool and not fixable within the driver. The driver advertises to the OS that it is available. You can check this in HTML5 game pad testers, DDHidLib, etc. There is no means by which we can assist you with an issue like this. This is likely worth filing a bug report with Microsoft over, as it is their code that is failing to recognize a perfectly valid HID device.
