### ISSUE TITLE
Is there a way to sync buttons to keyboard keys? It's easily possible on Windows with 360 controllers.

### ISSUE THREAD

**Issue by xFahrenheightx** [360Controller/360Controller#804]
Standard early Xbox One controller

Mojave 10.14.1 (18B75

Version 0.16.10 Driver Version

Wired Connection Method

Can't seem to find the Device Name and Info

Recognized by some emulators I use aka OpenEmu and works fine there.

All the buttons are recognized when testing.

I can't seem to map the controller buttons to activate certain keyboard keys.

**Comment by FranticRain** [comment]
https://yukkurigames.com/enjoyable/

**Comment by ahyattdev** [comment]
Steam can do this.
