### ISSUE TITLE
0.16.10 + Mojave fails to boot

### ISSUE THREAD

**Issue by beaugunderson** [360Controller/360Controller#806]
### Type of Controller
Xbox One

### OS Version
10.14.1 (18B75)

### Driver Version
360Controller 0.16.10

### Connection Method
Wired

### Detailed Explaination of Issue
Computer fails to boot after installing; had to boot into safe mode and remove the kext. Tried to boot 5 times, froze every time.

**Comment by FranticRain** [comment]
If you can recreate this issue, please hold Command and V during startup in order to display debug output. We can't figure out where these kinds of issues occur unless why know where specifically that it hangs.

**Comment by beaugunderson** [comment]
will do!

---

**Comment by beaugunderson** [comment]
I reinstalled the driver, rebooted, no freeze. Controller now works... Didn't have to enable the driver in Security & Privacy settings this time, either... Does it remember the choice, even though I had manually deleted all instances of the kext?

Regardless, no issue here. Could be due to detritus from a previously installed version.

**Comment by FranticRain** [comment]
If you accept a developer's signing certificate, it's put in your keychain so you never have to approve it again.
