### ISSUE TITLE
Installed Latest version - and after reboot isn't installed ... ???

### ISSUE THREAD

**Issue by L0VEFIRE** [360Controller/360Controller#807]
### Type of Controller
Xbox One (Wireless)

### OS Version
MacOS 10.13.6

### Driver Version
360Controller 0.16.10

### Connection Method
Bluetooth & Wired 

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID:
<br/>Vendor ID:

### Response of Controller
N/A

### Response in Preference Pane
**The Pane is not installed, that is the issue.**

### Description

I will note that after installing the driver and rebooting, my Mac start acting weird, it took 10 mins to reboot I was starting at a black screen for some time, then when it reboot the login screen was all weird load very slow. then once I logged in then the pane was not even installed after all that. ??? before this my Mac was fine.

**Comment by FranticRain** [comment]
Could you run `ls /Library/Extensions` in your terminal and post the output here? If you see a `360Controller.kext` in there, please also run `sudo kextutil /Library/Extensions/360Controller.kext` and tell me what that says.

**Comment by L0VEFIRE** [comment]
I get … 

360Controller.kext		CaptoDevice.kext
ACS6x.kext			EnergyDriver.kext
ATTOCelerityFC8.kext		HighPointIOP.kext
ATTOExpressSASHBA2.kext		HighPointRR.kext
ATTOExpressSASRAID2.kext	PromiseSTEX.kext
ArcMSR.kext			SoftRAID.kext
CalDigitHDProDrv.kext

Then … 

Notice: /Library/Extensions/360Controller.kext has debug properties set.
Warnings: 
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done): 
        ChatPadKeyboardEvents

**Comment by FranticRain** [comment]
So the driver was correctly installed, but the Preference Pane in missing. You can either attempt a re-install to add it, or I can guide you through a manual uninstall if you'd prefer.

**Comment by L0VEFIRE** [comment]
Already been down the reattempt route, so let try the manual uninstall method see how that works. Thanks

**Comment by FranticRain** [comment]
Open your terminal and run:
```
curl -o delete.sh https://raw.githubusercontent.com/360Controller/360Controller/875b4ca7bcf4c83aab2a6c290a8a411ac2e136d8/Install360Controller/Scripts/upgrade.sh &&
sudo chmod u+x delete.sh &&
sudo ./delete.sh && rm delete.sh
```
And enter your password as required

**Comment by FranticRain** [comment]
This issue is being closed due to inactivity. We can't fix issues if we don't have enough information. So periodically we close down issues that can't be resolved if they seem to have been abandoned by their creators. If your issue still persists, please open a new issue after thoroughly consulting the README and providing all information as required by the README.
