### ISSUE TITLE
Thrustmaster TX GIP Racing Wheel not recognized

### ISSUE THREAD

**Issue by honzasusek** [360Controller/360Controller#810]
### Type of Controller
Thrustmaster TX GIP Racing Wheel

### OS Version
10.14.1 (18B75)

### Driver Version
Version 0.16.8

### Connection Method
wired

### Device Name and Info
Thrustmaster TX GIP Racing Wheel

  Product ID:	0xb664
  Vendor ID:	0x044f  (ThrustMaster, Inc.)
  Version:	1.01
  Serial Number:	00000A1412A074BF
  Speed:	Up to 12Mb/sec
  Manufacturer:	Thrustmaster
  Location ID:	0x14500000 / 3
  Current Available (mA):	500
  Extra Operating Current (mA):	0

### Response of Controller
Powers up upon connection, rotates left and right, powers down after a few seconds.

### Response in Preference Pane
No device found

### Detailed Explaination of Issue
Seems to be exactly the same issue as in #724 with a different version of the same device (TX instead of TMX) and a different Product ID.

**Comment by FranticRain** [comment]
Here's a build with your device added: [Install360Controller.pkg.zip](https://github.com/360Controller/360Controller/files/2651553/Install360Controller.pkg.zip)
