### ISSUE TITLE
Controller Remapping

### ISSUE THREAD

**Issue by leeaj3** [360Controller/360Controller#812]
Xbox One

MacOS 10.13.6

Everything is working fine but I don't know how to remap the controller for different keyboard inputs.

I'm trying to use the controller for a non-game application with simply having inputs for spacebar, 1, 2, 3, and 4 with LT, Y, RT, and B respectively.

Any assistance would be greatly appreciated.

**Comment by FranticRain** [comment]
The driver does not support this functionality. I recommend third party tools that were built explicitly for this purpose, such as [Enjoyable](https://yukkurigames.com/enjoyable/) and [Joystick Mapper](http://joystickmapper.com/).
