### ISSUE TITLE
No devices found - 0.16.10 - Macbook Pro 2017 Touch Bar

### ISSUE THREAD

**Issue by HrOvergaard** [360Controller/360Controller#815]
### Controller: 
Xbox 360

### OS Version: 
Macbook Pro 2017 touchbar - MacOS Mojave - 10.14.2

### 360 controller software: 
0.16.10

### 360 controller connection:
Wired Wireless controler // Apple USB to Type C adapter

### System report:
>Device Name:
<br/>Product ID: 0x028f
<br/>Vendor ID: 0x045e 

### Response of Controller
None

### Response in Preference Pane
None

### Detailed Explaination of Issue
None responsing -  Installing and uninstalling different versions of the software, but no luck
Just showing "No devices found"

<img width="757" alt="image" src="https://user-images.githubusercontent.com/46063932/50371712-a7e25b00-05c0-11e9-99b8-f0b7ef6d9e17.png">

<img width="592" alt="image" src="https://user-images.githubusercontent.com/46063932/50371714-baf52b00-05c0-11e9-8fc5-a6a1ec965544.png">

<img width="697" alt="image" src="https://user-images.githubusercontent.com/46063932/50371777-a49b9f00-05c1-11e9-9c9f-2cf18a2d06ac.png">

**Comment by RobertAtPebblebee** [comment]
seems like the real bug is that the latest driver doesn't work with the latest version of mojave.  can anyone confirm?

**Comment by midkir** [comment]
I have the same situation.
Installing the driver on older macOS version, and upgrading to Mojave works fine.
In Mojave, I did not get "System Extension Blocked" dialog in the installation process, so I cannot permit the privilege to the driver.

![screenshot](https://user-images.githubusercontent.com/29122304/50407745-a8792c80-0820-11e9-9daa-73941315ccc3.png)

**Comment by iikas** [comment]
Hello, I actually have macOs mojave and the current version 0.16.10 of the driver for xbox 360 does not recognize the command once connected, is there any way to solve this problem? Please T.T

**Comment by gerardo8a** [comment]
I'm facing the same issue, but I got asked the very first time I installed the software for the developer allow access. But after that I can't still use the controller. 
I have a Xbox One controller but the same bug.

I tried removing and reinstalling, also restarting the system but no luck.

**Comment by HrOvergaard** [comment]
I'm going to try with a hard wired usb controller for Xbox 360 and also with the microsoft wireless controll reciver (together with the 0.16.5 software of cause) If that does not work I will try the same on an old Mac with Snow Leopard.

If nothing works... I will try with... windows....

**Comment by theJeej** [comment]
This problem is persevering, as I have the latest update both for mac and for the software.

**Comment by yowzadave** [comment]
I'm experiencing the same issue, on Mojave 10.14.2.

**Comment by FranticRain** [comment]
Okay. First things first, the driver still works on macOS Mojave 10.14.2. I just tested it.

@HrOvergaard @midkir @theJeej @yowzadave 
Please ensure that the driver has been allowed in System Preferences -> Security and Privacy -> General. This approval UI is only present in the Security & Privacy preferences pane for 30 minutes after the alert. Until you approve the kext, future load attempts will cause the approval UI to reappear but will not trigger another user alert.

![Security and Privacy panel in the macOS System Preferences](https://user-images.githubusercontent.com/33877645/33092253-965b666e-cec7-11e7-940d-3e13b46ca500.png)

@iikas Make a new issue. Make sure to mention in your new issue whether or not the preference pane says "No devices found" or if a device is actually found

@gerardo8a That looks like a successful load. Very different from these issues. Please make a new issue.

@Poisonousbeef Wireless controllers are not currently supported by the driver. For further information, please reference the README.

If I didn't call you out and you still need help, make a new issue.

**Comment by RobertAtPebblebee** [comment]
I am not getting this warning in Security preferences.  Though I am running 10.14.3.  The 'driver enabled' checkbox is never checked, and every time I check the box authorize the change and leave the preference and come back to it, the check box is yet again not checked (and still no feedback in the security preference).  Not sure if it matters but I have SiP disabled.  I tried building driver myself but fails to build with missing IOKit header file.  Looks like the latest code is referencing an older version of IOKit that may no longer have the device.h or interface.h files.  I can open a fresh issue I guess.

**Comment by FranticRain** [comment]
@RobertAtPebblebee The driver enabled checkbox has nothing to do with your issue. It's just some weird behavior that is working as expected, even when the driver is working correctly. If SiP is disabled, the option won't appear, because the driver should work automatically. The reason you can't build is because the driver has to be built against Xcode 6.4. An upgrade to modern IOKit is hindered by a memory leak in macOS. Make a new issue, filling out the template, and include the result of `kexutil /Library/Extensions/360Controller.kext` in your details.

**Comment by iikas** [comment]
SOLVED
Effectively, installing the most recent version of the driver 360 in macOs Mojave version 0.16.10 did not work even though it allowed the option in the preferences / security panel, but after an exhaustive search it managed to work with the driver 360 version 0.16.5, same way accept the permission in the preferences panel and go!
😄

**Comment by iikas** [comment]
SOLVED
Effectively, installing the most recent version of the driver 360 in (macOs Mojave version 10.14) did not work even though it allowed the option in the preferences / security panel, but after an exhaustive search it managed to work with the driver 360 version 0.16.5, same way accept the permission in the preferences panel and go!
😄 I hope you also work for you

**Comment by HrOvergaard** [comment]
Just got it working with 0.16.5 together with the "PC wireless gaming receiver" and xbox 360 wireless controller. GAME ON

**Comment by FranticRain** [comment]
As mentioned in the README under the wireless 360 controller section, since it seems like you two are trying to use wireless 360 controllers: https://github.com/360Controller/360Controller#wireless-xbox-360-controllers
>As of macOS 10.11, Wireless Xbox 360 controller support causes kernel panics. This issue cannot be resolved with minor changes to the driver, and requires that the driver be re-written from scratch to resolve the issue. Due to an excess of caution, we have disabled Wireless Xbox 360 controller support as of 0.16.6. If you want to use a wireless controller, download 0.16.5 or earlier and disable the driver before the computer enters a "sleep" state in order to prevent kernel panics. Alternatively, you can revert to a macOS version before 10.11 to avoid this issue.
