### ISSUE TITLE
"Device not found" on System Preferences

### ISSUE THREAD

**Issue by MageMaster** [360Controller/360Controller#817]
### Type of Controller
Xbox360 Wireless Controller via chinese Wireless Adapter

### OS Version
10.13.6 (17G4015)

### Driver Version
0.16.10

### Connection Method
Third-party (chinese) Wireless Adapter

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: Vendor-Specific Device
<br/>Product ID: 0x045e
<br/>Vendor ID: 0x0291

### Response of Controller
Four lights blinking, even after pressing the "connect" button on receiver and controller.

### Response in Preference Pane
"No devices found"

### Detailed Explaination of Issue
I checked on the info.plist file on /Library/Extensions/360controller.kext, and couldn't find the VendorID from my adapter. The adapter works flawlessly on Windows (using Microsoft official drivers), and the controller works both on adapter and xbox360.

**Comment by FranticRain** [comment]
Wireless controllers are not supported by this driver. Please consult the README for more information.
