### ISSUE TITLE
Wiimote controller support?

### ISSUE THREAD

**Issue by ElijahZAwesome** [360Controller/360Controller#818]
### Type of Controller
Wiimote

### OS Version
10.14.1

### Driver Version
0.16.10

### Connection Method
Wireless bluetooth with no dongle

### Device Name and Info
>Device Name: Nintendo RVL-CNT-01 
<br/>Product ID: 0x0306
<br/>Vendor ID: 0x057e

### Response of Controller
Nothing because it's not connected

### Response in Preference Pane
"No Devices Found".

### Detailed Explaination of Issue
It may seem like a stupid question but I'm wondering if support could be added to map the wiimote *and classic controller/nunchuk* to 360Controller? It was done with the pro controller so maybe?

**Comment by FranticRain** [comment]
All devices either have to work with Xbox hardware, or follow the XInput spec to the letter to work with this driver. The wiimote does neither of those things.
