### ISSUE TITLE
New pdp wired controller mac 10.12 not detected

### ISSUE THREAD

**Issue by NatP29** [360Controller/360Controller#832]
### Type of Controller
XBoxOne pdp wired

### OS Version
10.12 Sierra

### Driver Version

Xbox 360 Controller Driver
Version 0.16.10

### Connection Method
Wired USB (no usb-c adapter)

### Device Name and Info
PDP Wired Controller for Xbox One - Arctic White:

  Product ID:	0x02a8
  Vendor ID:	0x0e6f
  Version:	1.0f
  Serial Number:	0000960018F7BFC2
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Performance Designed Products
  Location ID:	0x14200000 / 14
  Current Available (mA):	500
  Extra Operating Current (mA):	0

### Response of Controller
I had 2 other controllers that worked fine (exact same controller, but in black) :
  Product ID:	0x0162
  Vendor ID:	0x0e6f
  Version:	4.60

Product ID:	0x02a7
  Vendor ID:	0x0e6f
  Version:	1.0f

### Response in Preference Pane
The driver says no device found. But in the apple menu I could find the controller in the usb tab. (hence controller info above)

### Detailed Explanation of Issue
The controller isn't detected by the driver. I tried different versions of the driver, uninstalling several times. It is detected by my mac, and everytime i plug in my older controllers they are recognized instantly.

In my security preferences i don't have an option to allow from the developer.

I just unboxed the controller, never tried it on an other pc.
Hope you can help, thanks a lot
Nathan

**Comment by FranticRain** [comment]
Here is a version of the driver that contains support for this additional device.

[Install360Controller.pkg.zip](https://github.com/360Controller/360Controller/files/2848523/Install360Controller.pkg.zip)

**Comment by NatP29** [comment]
Thanks ! It works fine now !

**Comment by javiqaz** [comment]
Hi @FranticRain can add also this controller pls

**PDP Deluxe Wired Controller for Xbox One - Stealth Series | Phantom Black:**

  Product ID: 	0x02c0
  Vendor ID:	0x0e6f
  Version:	1.05
  Serial Number:	00001F7D7ADA8124
  Speed:	Hasta 12 Mb/s
  Manufacturer:	Performance Designed Products
  Location ID:	0x14100000 / 9
  Current Available (mA):	500
  Extra Operating Current (mA):	0



Thanks !! <3

**Comment by FranticRain** [comment]
@javiqaz That device is already added. If it doesn't already work, then it either isn't compatible or you have some other issue. Please continue any further discussion in a new issue.

**Comment by LordDasew** [comment]
Hello there,
I have macOS big sur 11.1 and  it doesn't recognise my PDP xbox controller, it says to contact the developer as it's not updated ...
Any help please?

**Comment by ZainGeeky** [comment]
PDP Wired Controller for Xbox One - Stealth Series | Revenant Blue:

  Product ID:	0x02a6
  Vendor ID:	0x0e6f
  Version:	2.23
  Serial Number:	0000AF09C277160F
  Speed:	Up to 12 Mb/s
  Manufacturer:	Performance Designed Products
  Location ID:	0x00140000 / 3
  Current Available (mA):	500
  Extra Operating Current (mA):	0
  
  my controller is not getting recognised
