### ISSUE TITLE
Not working on Mojave 10.14.x

### ISSUE THREAD

**Issue by viniciusjarina** [360Controller/360Controller#841]
### Type of Controller
Original Xbox, with the Xbox USB receiver 

### OS Version
macOS 10.14.3

### Driver Version
360Controller 0.16.10

### Connection Method
Wireless Adapter

### Detailed Explaination of Issue
0.16.10 seem to have a regression, after installed [0.16.9](https://github.com/360Controller/360Controller/releases/tag/v0.16.9) is working perfectly.

**Comment by FranticRain** [comment]
As noted in the readme:
>As of macOS 10.11, Wireless Xbox 360 controller support causes kernel panics. This issue cannot be resolved with minor changes to the driver, and requires that the driver be re-written from scratch to resolve the issue. Due to an excess of caution, we have disabled Wireless Xbox 360 controller support as of 0.16.6. If you want to use a wireless controller, download 0.16.5 or earlier and disable the driver before the computer enters a "sleep" state in order to prevent kernel panics. Alternatively, you can revert to a macOS version before 10.11 to avoid this issue.
This is a known and intended regression.
