### ISSUE TITLE
New Controller

### ISSUE THREAD

**Issue by jrussellsmyth** [360Controller/360Controller#844]
### Type of Controller
Xbox 360

### OS Version
Replace this text with the version of macOS that you are running

### Driver Version
Replate this text with the version or versions of the driver that you are using or have tested

### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)

  Product ID:	0x581a
  Vendor ID:	0x24c6
  Version:	1.01
  

### Response of Controller
no response

### Response in Preference Pane
not in dropdown, no response

### Detailed Explaination of Issue
not recognized at all

**Comment by FranticRain** [comment]
This device is included in the newly released 0.16.11.
