### ISSUE TITLE
Question: How to read deadzone values?

### ISSUE THREAD

**Issue by Agrrox** [360Controller/360Controller#845]
Is there way how to check a deadzone values? The Interface isn't very useful at setting a same exact deadzone values.

**Comment by FranticRain** [comment]
Look at the plist file at `~/Library/Preferences/ByHost/com.mice.driver.Xbox360Controller.devices.<GUID>.plist`. The values your are looking for are `DeadzoneLeft` and `DeadzoneRight`. They should be out of the controller's maximum 32,768.
