### ISSUE TITLE
Missing compiled installer

### ISSUE THREAD

**Issue by Nathan-Harris** [360Controller/360Controller#847]
Just a heads up that you didn't include the compiled and signed .dmg installer in the newest release!

**Comment by KernkraftX360** [comment]
Yes, just to confirm with @Nathan-Harris, that the .dmg installer is not included in the latest release of 360Controller.

**Comment by FranticRain** [comment]
Crap, my bad. I'll add it when I get home today.

**Comment by FranticRain** [comment]
Fixed.
