### ISSUE TITLE
Chinese localization not working 

### ISSUE THREAD

**Issue by L1cardo** [360Controller/360Controller#848]
### OS Version
macOS 10.14.3

### Driver Version
Version 0.16.11

### Detailed Explaination of Issue
I have install the latest version of the driver and it should contain Chinese localization, but is doesn't.
It is still English .

<img width="782" alt="2019-03-06 7 27 34" src="https://user-images.githubusercontent.com/33802186/53878094-efb44280-4045-11e9-8f16-8aa429eb1aeb.png">

**Comment by FranticRain** [comment]
Did the change work locally before the merge request? I just want to make sure that it wasn't removed somehow by the build process.

**Comment by L1cardo** [comment]
I failed building the pkg file, so I didn't test locally.
Apologize.
