### ISSUE TITLE
Fighting Commander for PlayStation 4 & 3

### ISSUE THREAD

**Issue by ipdxl** [360Controller/360Controller#855]
### Type of Controller
[Fighting Commander for PlayStation 4 & 3
](http://stores.horiusa.com/fighting-commander-for-playstation-4-3-officially-licensed-by-sony-playstation-4/)

### OS Version
10.14.3 (18D109

### Driver Version
0.16.11

### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: Fighting Commander:
<br/>Product ID: 0x0086
<br/>Vendor ID: 0x0f0d  (HORI CO., LTD.)

### Response of Controller
The controller doesn't react to anything, the turbo indicator doesn't turn on

### Response in Preference Pane
Doesn't appear in preference panel

### Detailed Explaination of Issue
it doesn't work

**Comment by FranticRain** [comment]
I have absolutely no idea if this will work or not, but here's a build with the device added.

[Install360Controller.pkg.zip](https://github.com/360Controller/360Controller/files/3015956/Install360Controller.pkg.zip)

**Comment by ipdxl** [comment]
@FranticRain Ok, I'll check.

**Comment by ipdxl** [comment]
@FranticRain mmmmm no. It doesn't work.

**Comment by FranticRain** [comment]
Then your device simply doesn't work with this driver. We only support devices that work with official Xbox consoles. If your device doesn't work with a console in that series or happen to comply with the standards of that series, then we cannot support it.
