### ISSUE TITLE
Controller is recognized, but doesn't work. 

### ISSUE THREAD

**Issue by vakhidbetrakhmadov** [360Controller/360Controller#867]
### Type of Controller
ThirdParty USB

### OS Version
10.14.4

### Driver Version
0.16.11

### Connection Method
Wired (USB)

### Device Name and Info
>Device Name: defender game racer turbo rs3
<br/>Product ID: 0x028e
<br/>Vendor ID: 0x045e

### Response of Controller
On connection guide button lights up with red light for a few seconds and then turns off.

### Response in Preference Pane
The controller appear in the preference panel, but when pressing any buttons while in 'Controller test' nothing happens. 

### Detailed Explaination of Issue
The controller is detected by all programs, but buttons do not work. 
Unfortunately I can not build it with my Xcode 10. 
Can I ask for adding my device and sending me a driver? 

Thank you.

**Comment by IRomich** [comment]
Hello
I use defender archer and have same problem. Did you solve it?
Thank you
