### ISSUE TITLE
MYGT C03 - detected but can't pair with a dongle

### ISSUE THREAD

**Issue by foxnoodles** [360Controller/360Controller#871]
### Type of Controller
Third party 

### OS Version
MacOS 10.14.4

### Driver Version
0.16.11

### Connection Method
Wireless Adapter

### Device Name and Info
MYGT C03, which has a 2.4 MHz dongle and 4 input modes (XInput, PS3, Android, IOS) that can be changed on the fly. 
>Device Name: identifies as "Controller(XBOX 360 For Windows)"
<br/>Product ID: 0x028e
<br/>Vendor ID: 0x045e

### Response of Controller
None

### Response in Preference Pane
Pref pane detects the dongle as "Xbox 360 Wired Controller (wired)" that's all

### Detailed Explanation of Issue
Ok so, the same dongle works fine on windows, the controller gets recognized as an official XBOX 360 controller and works like charm. But on Mac, the driver only detects the dongle but the controller itself won't pair to it. (this is indicated by a continuously blinking green light). 
It is worth to note that system report calls it  "Controller(XBOX 360 For Windows" no matter what. Even if the 360 driver is disabled. 

p.s. It connects to my MacBook via Bluetooth if I switch to IOS mode but is recognized as "MYGT Controller" keyboard device.

Any ideas?

**Comment by foxnoodles** [comment]
Okay I'm an idiot

"**Xbox One Controllers connected with Wireless Adapter**
Xbox One controllers connected with the Wireless Adapter are currently not supported. Please be patient as we figure out this complicated protocol."

**Comment by FranticRain** [comment]
You should be able to use this controller with macOS with Bluetooth at least. It won't work with the driver, and game support might be poor, but at least it will work.

**Comment by foxnoodles** [comment]
Yeah but it detects it as a keyboard not just a "bluetooth device"

**Comment by FranticRain** [comment]
That's kinda crappy. It might work as a wired controller because it steals the VID and PID of the Xbox One controller. But if it doesn't, it's outside our purview of support as we do not support "counterfeit" controllers such as this one that violate the USB specification by stealing another device's VID/PID.

**Comment by foxnoodles** [comment]
Yeah I figured. 
Also, I think the dongle fakes itself to be the wired Xbox controller, while the gamepad itself has a different PID. At least that's how it shows up when paired via Bluetooth.  I just don' get why it doesn't pair with an adapter.

Here's the Bluetooth device that acts like a keyboard:
 
`MYGT Controller:
  Address:	FF-0F-80-02-63-25
  Major Type:	Peripheral
  Minor Type:	Keyboard
  Services:	Bluetooth Gamepad   
  Paired:	Yes
  Configured:	Yes
  Connected:	No
  Firmware Version:	0x011B
  Vendor ID:	0x4D59
  Product ID:	0x4303
  Class of Device:	0x05 0x10 0x2540
  Host Connectable:	No
  EDR Supported:	No
  eSCO Supported:	No
  SSP Supported:	Yes`

**Comment by foxnoodles** [comment]
Okay, this is weird, I hooked up the dongle to VM on windows to let it pair. Then paused the VM. It stayed in paired state and now works on Mac

**Comment by alypasya** [comment]
Hai bro, i have problem with mygt c03, when i connect to windows the lamp blinking green and yellow, which is windows known as ps3 controller and did not recognized as x input. Any solution?

**Comment by melon-husk** [comment]
I think I have the same MYGT controller, it only works if I set it to android mode on the controller and connect through bluetooth on pop os.
