### ISSUE TITLE
PDP stealth not listed in info.plist (Verdant Green, Midnight Blue)

### ISSUE THREAD

**Issue by Wilco2998** [360Controller/360Controller#886]
### Type of Controller
PDP stealth Xbox one

### OS Version
10.14.4

### Driver Version
Replate this text with the version or versions of the driver that you are using or have tested

### Connection Method
USB

### First device Name and Info
Device Name: PDP Wired Controller for Xbox One - Verdant Green
<br/>Product ID: 0x02a1
<br/>Vendor ID: 0x0e6f

### Second device name and info
PDP Wired Controller for Xbox One - Midnight Blue:
<br/>Product ID: 0x02a0
<br/>Vendor ID: 0x0e6f

### Response of Controller
nothing

### Response in Preference Pane
does not appear

### Detailed Explaination of Issue
I saw that the PDP Stealh Violet Spectral & Phantom Black were listed in the info.plist but the controllers listed in this issue are not listed in the info.plist.

I had tried to edit the info.plist but was not able to compile the driver with `./build.sh`

**Comment by FranticRain** [comment]
We add these controllers but they don't always work, so far warning that this may not change anything. I've gone ahead and built in into a version of the alpha-3 release as that is most likely to work with these controllers. I'd appreciate knowing whether or not this actually works, so make sure to let me know how it goes. But if it doesn't work, then there isn't much I can do about it. These controller used to work before 10.11, but for some reason they don't anymore.

[360ControllerInstall.dmg.zip](https://github.com/360Controller/360Controller/files/3180558/360ControllerInstall.dmg.zip)

**Comment by Wilco2998** [comment]
The Verdant Green is being recognised by the driver and all the buttons are working.
The Midnight Blue did I not test because it's mine brothers controller, I took only the Product and vendor ID so it could be added to the info.plist

I tried also the driver with steam big picture mode, when not playing a game the controller works fine inside the menus.
But what sometimes did happen in steam big picture mode was that the controller was recognised
 multiple times (like in the picture)
<img width="564" alt="Schermafbeelding 2019-05-15 om 16 45 27" src="https://user-images.githubusercontent.com/17604138/57784912-060b0880-7731-11e9-9315-c0d40acf835a.png">
