### ISSUE TITLE
Ipega PG-9076 detected, but not working.

### ISSUE THREAD

**Issue by Knvz** [360Controller/360Controller#894]
### Type of Controller
Ipega PG-9076

### OS Version
High Sierra 10.13.6

### Driver Version
360Controller 1.0.0-alpha.3

### Connection Method
usb dongle

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID: 0x028e
<br/>Vendor ID: 0x045e  (Microsoft Corporation)

### Response of Controller
No reaction

### Response in Preference Pane
It appears, but no buttons, joysticks, and triggers act.

### Detailed Explaination of Issue
I put the controller in XInput mode. In Windows it is identified as an xbox controller, but with this driver it is detected but dont work at all.

**Comment by FranticRain** [comment]
This controller is not supported by official Xbox hardware. As such, its support is outside the scope of this driver. We cannot and will not support this controller.
