### ISSUE TITLE
New code signer wanted

### ISSUE THREAD

**Issue by FranticRain** [360Controller/360Controller#895]
Hello everyone!

I am no longer comfortable using my developer signing certificate to sign the driver. I plan to continue support of the driver through the month of June. However, no further versions of the driver will be signed by me, starting now.

I am happy to support the driver as a compatibility layer for a dark period of macOS gaming that had terrible controller support. But as I'm seeing more and more applications that continue to rely on the driver rather that building user-space controller support into their app, I realize that I am contributing to the continuation of this dark age. I am not comfortable with this idea and therefore I will stop signing the driver.

Thanks for reading, and thanks for using 360Controller!

**Comment by d235j** [comment]
Is there any reason that common frameworks e.g. SDL2, and SDKs e.g. Unity and Unreal, cannot include userspace support for the driver?

**Comment by d235j** [comment]
There is also the issue of managing the wireless controller and receiver, which I find it unlikely for apps to do user-space.

**Comment by FranticRain** [comment]
@d235j In my opinion, the way forward in wireless is with Bluetooth Xbox One and Bluetooth Dualshock 4 controllers. I'm aware that there are concerns with the number of devices that can be connected at once via Bluetooth. But as macOS ramps up on its official support of these devices via Bluetooth, my interest in supporting wireless 360 controllers wanes.

**Comment by Deco354** [comment]
I don't know anything about developing Drivers but I noticed this in Apple's WWDC announcement about driver support in user space. Maybe it's of some use.
https://developer.apple.com/documentation/driverkit

**Comment by HanSeoulOh** [comment]
Just saw this and this made me sad :(. Good luck with your next venture!

**Comment by ForkFaceJones** [comment]
Just found this and an old 360 controller and AAAAGH 

But still.

Best of luck with everything @FranticRain - thanks for all the work you put in.

**Comment by DaBlitzStein** [comment]
Nobody will sign?

**Comment by FranticRain** [comment]
@d235j Would you mind enabling the sponsor button functionality since it looks like I'm going to be around for a while longer, looks like.

https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

**Comment by j1life1chance** [comment]
I am willing to sign, although you will have to walk me through what is needed.

**Comment by FranticRain** [comment]
@j1life1chance Do you currently have a kext signing certificate? Apple no longer gives them out, to my knowledge.

**Comment by FranticRain** [comment]
Since apparently I can't even get the repository owners to do tiny little settings changes for me, I'm going to be ceasing support of 360Controller, effective immediately. It's clear that the owners of this repository have no intention of helping me support this repository, and that this is clearly a dead project that I've been "Weekend At Bernie's"-ing for a number of years.

**Comment by TyanColte** [comment]
@FranticRain it had a good run.

**Comment by maxrothman** [comment]
@FranticRain if you're having trouble getting support from the repo owners, why not fork?

**Comment by d235j** [comment]
@FranticRain I missed your message. You now have admin rights to this repo, and I enabled sponsorship. Sorry for the delay!!

**Comment by electric-monk** [comment]
@FranticRain I'd also like to apologise, I set up a filter recently as sometimes github gets a bit noisy so I didn't notice your comment, otherwise I'd have set it up too.

**Comment by FranticRain** [comment]
Closing this issue since this driver is soon to be deprecated by Apple is favor of DriverKit. I will be focusing my efforts there.
