### ISSUE TITLE
Yosemite support

### ISSUE THREAD

**Issue by RodrigoCard** [360Controller/360Controller#9]
Seems like apple broke some stuff again... it is not working in the latest yosemite beta :/

**Comment by miquel9** [comment]
not working for me Yosemite 10.10.1 xbox 360 wired original controller :(

**Comment by RodrigoCard** [comment]
@miquel9 are you sure? Did you install the latest release from here: https://github.com/d235j/360Controller/releases/ ?

**Comment by miquel9** [comment]
unfortunately I'm absolutely sure :/ and afterwards I've also trie all versions since 0.11 but no one is working for me :/ I would be glad if you could help me.

**Comment by therealbushwhack** [comment]
My Gamestop controller is FINALLY supported in this release, but I have another issue. 
As long as the controller is connected via USB, the display fails to go to sleep and I need to remember to unplug the controller so the display sleeps as expected. Is there a way to fix this so the display functions/sleeps as expected? Unplugging the controller when done with it does fix it, but where it is now attached is not the most convenient place to reach to unplug when done...

**Comment by CyberSkull** [comment]
@therealbushwhack You should really make a new ticket for that.

**Comment by jurasec** [comment]
Hi, not working for me either: Yosemite 10.10.1 Xbox 360 wireless original controller

**Comment by el-bo** [comment]
hi

just wondering if i could get some help with some issues

i have been using various iterations of the tattiebogle driver over the last 6 years with no issue. i have been slowly migrating software over to a yosemite partition, and making sure all is ok. most of the games i use are working fine with your version of the driver, but i am having issues with others

my main issue is with a game called 'metro: last light'. unfortunately the controller is greyed out on the menu despite the controller being compatible. currently involved in an ongoing support discussino with the developer, who has referred me to the tattiebogle drivers. i have yet to mention that i am using these updated drivers for yosemite. it might be a stretch to ask if anyone else has this particular game, but maybe there are known issues with certain games, for certain reasons. if i can't get it working, i might have to pursue a refund. i do really want to enjoy this game though :)

my main reason for writing, however, is to see if there is anyway of streamlining the uninstall process. i am sure everybody is familiar with conflicts between the tat drivers, and companies that write proprietary drivers e.g aspyr. searching for pref files, removing, and restarting is the advice given by aspyr, but i tend to jump from one game to another in quick succession; it is not possible to keep going through this process for a quick 10-minute session

i have to say that this coding stuff goes way over my head, and i am often quite wary of making modifications (i don't even know what i need to do with the uninstall script above), but i was wondering how simple the process can be made, and if there is any way of avoiding a restart. i did come across this the other day, but i am not sure whether it applies to this situation : 

http://onlivefans.com/news/xbox-360-controller-issues-with-onlive-on-a-mac-can-be-fixed/357/

one other solution might be to buy 'controllermate'. that way, as long as there is a current functioning driver, it would be possible to bypass the controller options, and defer to emulating mouse and keyboard bindings. this does seem to be a huge amount of work though, even as a last resort

this is my very first github post, and i am hoping this whole controller thing becomes a bit less 'fringe'. as someone who has had both wrists operated on for carpal tunnel (and can only game with a controller, in shorter bursts), i am so grateful for everything you are doing

any help would be greatly appreciated

many thanks

**Comment by MaddTheSane** [comment]
@el-bo: please open a new ticket.

**Comment by el-bo** [comment]
sorry about that :) think i have now, though i have no idea where it ended up

**Comment by badjano** [comment]
I have the original Microsoft Xbox 360 controller, on on system information my device was called: "Vendor-Specific Device" my product id was 655 and it was 654 on the MicrosoftXbox360Controller, idVendor was the same ( 1118 ), changed it on the plist but I still get "No devices found"... I reinstalled the driver a couple of times, still not working... I don't know what to do anymore, I am trying to use it wired, is it only possible to use it wireless? Almost giving up... :(

**Comment by RodrigoCard** [comment]
@badjano if you have a wireless controller you can only use that wireless, you cant plug the play and charge cable, it only charges. Also, to conect it wirelessly you will need additional hardware, google for "Wireless Gaming Receiver"
