### ISSUE TITLE
3rd Party RockCandy controller not supported.

### ISSUE THREAD

**Issue by PcatMagoo** [360Controller/360Controller#909]
Xbox One

10.15.5 OS Version

0.16.11 Driver Version

Wired Connection Method

RockCandy Aqualime
Product ID:	0x02cf
Vendor ID:	0x0e6f

Response in Preference Pane
No devices found

Detailed Explaination of Issue
Device does not show up in preference pane

**Comment by FranticRain** [comment]
I added your device to the driver. Let me know how this works for you.
[360ControllerInstall.dmg.zip](https://github.com/360Controller/360Controller/files/3340120/360ControllerInstall.dmg.zip)
