### ISSUE TITLE
3rd Party Controller Not Working (PDP Deluxe Wired Stealth)

### ISSUE THREAD

**Issue by rcarrasco88** [360Controller/360Controller#910]
### Type of Controller
XBOX One

### OS Version
Mac OS 10.14.5

### Driver Version
0.16.10

### Connection Method
Wired

### Device Name and Info
>Device Name: PDP Deluxe Wired Controller for Xbox One - Stealth Series | Phantom Black
<br/>Product ID: 0x02c0
<br/>Vendor ID: 0x0e6f

### Response of Controller
None

### Response in Preference Pane
Doesn't Show Up

### Detailed Explaination of Issue
I have tried several drivers with the one mentioned above being the latest but the device does not show up under preferences

**Comment by FranticRain** [comment]
I've added your device to the driver. Let me know how it works.
[360ControllerInstall.dmg.zip](https://github.com/360Controller/360Controller/files/3342294/360ControllerInstall.dmg.zip)
