### ISSUE TITLE
pdp xbox controller 

### ISSUE THREAD

**Issue by HanSeoulOh** [360Controller/360Controller#920]
### Type of Controller
xbox one 

### OS Version
Mojave 10.14.4
### Driver Version
1.0.0 a3
### Connection Method
Wired
### Device Name and Info

PDP Wired Controller for Xbox One - Raven Black:

  Product ID:	0x02b0
  Vendor ID:	0x0e6f
  Version:	1.0e

### Response of Controller
Nothing

### Response in Preference Pane
Nothing

### Detailed Explaination of Issue
I saw that you did a rewrite of the driver so I wanted to put this down as an issue. Let me know if there's anything I can do to help so that we can get this controller working :)

**Comment by FranticRain** [comment]
Here's a build with this controller added. Let me know if you have any issues with it. All future builds will include this controller.

[360ControllerInstall.dmg.zip](https://github.com/360Controller/360Controller/files/3834386/360ControllerInstall.dmg.zip)
