### ISSUE TITLE
Hyperkin X91 not working on android? hmmmm

### ISSUE THREAD

**Issue by Otraotaku** [360Controller/360Controller#925]
### Type of Controller
Xbox One, PC

### OS Version
ANDROID 9.0

### Connection Method
USB Wired

### Response of Controller
Android Detects it as "X91 Controller" 

### Detailed Explaination of Issue
The LED is out and will not function as a controller.

Very Strange since both the Xbox 360, and Xbox one Controllers have always been plug and play with android devices for years. I know this has been an issue for RetroPie Users in the past. Is there a similar fix in android? Thanks

**Comment by MaddTheSane** [comment]
This is specifically for the Mac driver. Android is outside the scope of this project.
