### ISSUE TITLE
Bluetooth Breaks Xbox One Controller from going back to Wired Mode

### ISSUE THREAD

**Issue by L0VEFIRE** [360Controller/360Controller#938]
### Type of Controller
Xbox One (1708)

### OS Version
macOS Mojave & macOS Catalina (Both Public Releases)

### Driver Version
currently: Alpha 3 
I have tested it with 0.16.10 as well since that is a stable version I know always works.

### Connection Method
Wired, Bluetooth

### Device Name and Info

Apple T1 Controller:

  Product ID:	0x8600
  Vendor ID:	0x05ac (Apple Inc.)
  Version:	1.01
  Manufacturer:	Apple Inc.
  Location ID:	0x14200000

Controller:

  Product ID:	0x02ea
  Vendor ID:	0x045e  (Microsoft Corporation)
  Version:	3.01
  Serial Number:	3033363030353037323632383239
  Speed:	Up to 12 Mb/s
  Manufacturer:	Microsoft
  Location ID:	0x14100000 / 1
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

### Response of Controller
Guide button blinks slowly, nothing else works.

### Response in Preference Pane
Nothing appears when opening the xbox pref pane, "no controllers detected" regardless if I toggle the driver on/off and reboot. If I uninstall the driver I get an error. "Preferences Error - There was an error in the Xbox 360 Controllers preferences" 
If I go to turn the driver on/off I get a prompt that says "Legacyloader wants to make a change"

### Detailed Explanation of Issue
So when starting out with a macOS where you have never attempted to use the xbox controller with bluetooth and only ever used it wired with and driver 0.16.10 and higher. the driver works perfectly via a wired connection. 
BUT the moment one attempts to connect the xbox Controller to macOS bluetooth it breaks the connection with the driver and you can't go back unless you reinstall a fresh copy macOS.

The question is What is stopping the controller from going back to a wired connection , after attempting to use it with bluetooth? 

the other issue is both apple and Microsoft won't take any responsibility for this and stuck on how to get this resolved. hoping that maybe the driver updated  could maybe stop the controller from being stuck in limbo mode.

**Comment by FranticRain** [comment]
The first connection takes priority, and the first connection it's going to make is Bluetooth. If you want to use the controller wired, turn off Bluetooth or forget the connection in macOS' Bluetooth settings.
