### ISSUE TITLE
Compatibility issues with Catalina

### ISSUE THREAD

**Issue by L0VEFIRE** [360Controller/360Controller#939]
### Type of Controller
Xbox One S

### OS Version
macOS Catalina 

### Driver Version
0.16.10 + (1 Alpha 3)

### Connection Method
Wired (USB-C to Micro USB Cable)

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name:
<br/>Product ID:
<br/>Vendor ID:

### Response of Controller
Guide button blinks slowly 

### Response in Preference Pane
See Attachments:

### Detailed Explanation of Issue
- when attempting to uninstall the driver on macOS Catalina it will give you 1 of 2 different errors
- when enabling/disabling the driver it will now say "legacyloader" over what it said before.

### Attachments
<img width="780" alt="Screen Shot 2019-10-09 at 6 40 58 PM" src="https://user-images.githubusercontent.com/28074348/66532956-3a67d280-eadf-11e9-86fb-7831792e8265.png">
<img width="670" alt="Screen Shot 2019-10-09 at 8 35 40 PM" src="https://user-images.githubusercontent.com/28074348/66532957-3a67d280-eadf-11e9-9cdd-1ff01a674996.png">
<img width="842" alt="Screen Shot 2019-10-09 at 6 45 06 PM" src="https://user-images.githubusercontent.com/28074348/66532958-3b006900-eadf-11e9-8d5f-6a4d2474945b.png">

**Comment by FranticRain** [comment]
Alpha 4 now works with Catalina.
