### ISSUE TITLE
Xbox 360 Controller not supported in Catalina

### ISSUE THREAD

**Issue by ImShalev** [360Controller/360Controller#942]
### Type of Controller
Xbox 360

### OS Version
macOS 10.15 Catalina

### Driver Version
Tested 1.0.0-alpha.3 , 0.16.11 , 0.16.11_Notarized

### Connection Method
Wired

### Device Name and Info
>Device Name: Wired Xbox 360 Controller
<br/>Product ID: 0x028e
<br/>Vendor ID: 0x045e (Microsoft Corporation)

### Response of Controller
Xbox button just blinks.

### Response in Preference Pane
Device just isn't recognized there. Says "No devices found".

### Detailed Explanation of Issue
Wired Xbox 360 Controller just doesn't work in Catalina, used to work in Mojave.
The controller just keeps blinking.
I've heard it's because the driver installation does not prompt any kexts authorization.
![360Controller Issue 1](https://user-images.githubusercontent.com/47086351/66702055-f574b380-ed0b-11e9-9105-b33d357dc147.png)
![360Controller Issue 2](https://user-images.githubusercontent.com/47086351/66702056-f574b380-ed0b-11e9-83d4-522fbfd36fab.png)

**Comment by raffaeleg4** [comment]
Agree totally the same I have

**Comment by hanhha** [comment]
+1 I have same issue.

**Comment by leoma95** [comment]
Same here. My XboxOne controller is also detected on USB, but 360Controller driver does not detect it in Catalina. Worked fine in Mojave before the upgrade.

**Comment by LostAccount** [comment]
> +1 I have same issue.

same here

**Comment by MaddTheSane** [comment]
Looking at the Console, I got the following error when I plugged in an Xbox One controller:

````
read - failed to start (0xe00002c2)
````

This was also with version 0.16.6.

**Comment by FranticRain** [comment]
That's a `kIOReturnBadArgument`.

**Comment by macmeister1967** [comment]
This is the reason you do not install latest new macOS on day of release

**Comment by raffaeleg4** [comment]
Indeed. But the update happened automatically without asking unlike the last years

**Comment by macmeister1967** [comment]
You mean Catalina? I have Mojave with updates disabled in Software Updates
prefpane, and I am yet to get a notification?!

**Comment by FranticRain** [comment]
Looks like Catalina no longer accepts our lazy null options for `inTaskWithOptions` and we have to specify the direction. So for example, this line: https://github.com/360Controller/360Controller/blob/34342c7ba6da60b24f9779f23182f7c58ff79fa8/360Controller/_60Controller.cpp#L550
needs to have that 0 changed to a `kIODirectionIn`.

**Comment by xshuffl3x** [comment]
Hello, 
sorry i'm noob in dev so this issue is not fixed ?

**Comment by MaddTheSane** [comment]
1. Nobody has fixed the problem code
2. The person who previously signed the kexts has said that he won't be doing it anymore, so someone else would need to sign the kexts.

**Comment by rom1gal** [comment]
Same here, LEDs are blinking since the update

**Comment by briveira** [comment]
anywhere we can get a compiled release with this patch applied? thanks

**Comment by SysDragon** [comment]
FYI it won't work either with the Xbox Elite Controller on last version of Catalina as per the current release

**Comment by DaBlitzStein** [comment]
If I knew that didn't upgrade

**Comment by youngbobby** [comment]
Ah, this is sad :(

**Comment by renantiago** [comment]
Hello guys... any help, please?

**Comment by FranticRain** [comment]
Check out [alpha 4](https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.4) and let me know if it works for you all. Looks like rumble is broken, but at least the controller is working now.

**Comment by ImShalev** [comment]
@FranticRain did you renew your developer account?

**Comment by FranticRain** [comment]
@ImShalev Yes.

**Comment by ImShalev** [comment]
@FranticRain Thank you very much!

**Comment by raffaeleg4** [comment]
Thank you so much! It's working again

**Comment by ImShalev** [comment]
Amazing, closing this issue!

**Comment by renantiago** [comment]
Thank you guys, you are the best!

**Comment by d235j** [comment]
@FranticRain I see that the post-install script still does a `touch /System/Library/Extensions`; this caused install failure for another project I've contributed to. It's supposed to be replaced with `kextcache -i /" but I'm not sure which OS version introduced this feature.

I highly recommend disabling/preventing any potential writes to /System in macOS 10.15 as the new read-only root filesystem will cause those writes to fail.

**Comment by FranticRain** [comment]
@d235j Thanks for the heads up, I'll look into it.

**Comment by leoma95** [comment]
@FranticRain and team - you guys are amazing. Thank you.

It works fine with Catalina now. I also just installed the first Catalina patch just released by Apple and the controller works fine as well. It just seems that there is a very long delay ˜1min from plugging it in to when it is recognized by the driver configuration app. 

Is there a way to donate $$$ to this team/cause?

**Comment by FranticRain** [comment]
@leoma95 I was just recently accepted into the Github sponsors program, so I'll be setting that up soon. Look for it in the coming week. As to why there is some latency between plugin and device recognition, I'm not sure. It could be Apple phoning home to check the notarization of the application before it loads.

**Comment by PythagoRascal** [comment]
> Looks like rumble is broken, but at least the controller is working now.

:(, any updates on this or an idea why it's broken?

**Comment by FranticRain** [comment]
@PythagoRascal It’s issue that has been a band-aid fix since macOS 10.11 that was made fully impossible in 10.15. At this time, there is no known (to me) solution within macOS to resolve this. Given I have a lot more actual functionality bugs to get to, rumble is very low priority. If you want it in the near future, you’ll need to downgrade macOS versions.

**Comment by cstches** [comment]
what about Catalina is now supporting xbox controllers (via bluetooth) ?

**Comment by mrorato** [comment]
> Check out [alpha 4](https://github.com/360Controller/360Controller/releases/tag/v1.0.0-alpha.4) and let me know if it works for you all. Looks like rumble is broken, but at least the controller is working now.

Work! Wireless and wired 360 in Catalina 10.15.7
