### ISSUE TITLE
Please add a new third-party controller to the list of Third Party Controllers

### ISSUE THREAD

**Issue by tabaoman** [360Controller/360Controller#943]
### Type of Controller
BETOP Asura 2

### OS Version
macOS Catalina 10.15

### Driver Version
360Controller_1.0.0-alpha.3

### Connection Method
Wired (USB)

### Device Name and Info
BETOP Asura 2
Product ID: 0xaa01
Vendor ID: 0x20bc

### Response of Controller
The 4 directional buttons are not working in games, such as Sky Force Reloaded. But they work in the full window mode of steam.
It doesn't vibrate.

### Response in Preference Pane
The device cannot be listed in the dropdown list in Preference Pane.
No response to any input from controller.

### Detailed Explaination of Issue
BETOP is a vendor making game controller. I tried to modify Info.plist and build the project with XCode 11 by myself, but failed with 16 errors. I didn't yield until seeing the error saying "unable to find sdk 'macos 10.10'".

**Comment by FranticRain** [comment]
This controller is not supported by official Xbox hardware. As such, its support is outside the scope of this driver. We cannot and will not support this controller.
