### ISSUE TITLE
not a bug! just praise! 

### ISSUE THREAD

**Issue by PyxieLeFace** [360Controller/360Controller#957]
**THANK YOU SO MUCH FOR THE UPDATE I LOVE YOU!!!!!!! YOU ARE THE BEST! **

seriously thank you! so freaking much!

**Comment by FranticRain** [comment]
Thank you for your kind words. If you’d like to support me in my efforts, you can [sponsor me through github.](https://github.com/sponsors/FranticRain) Otherwise, happy gaming.
