### ISSUE TITLE
PowerA - Xbox One controller not recognised 

### ISSUE THREAD

**Issue by tumidrain880899** [360Controller/360Controller#960]
### Type of Controller
PowerA Xbox One Controller
### OS Version
10.14 Mojave

### Driver Version
360Controller 1.0.0-alpha.4
### Connection Method
Wired

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: XB1 Classic Controller
<br/>Product ID: 0x581a
<br/>Vendor ID: 0x24c6

### Response of Controller
Does not light up

### Response in Preference Pane
Menu listed a device called XB1 Classic Controller

### Detailed Explaination of Issue
It doesn't work

**Comment by FranticRain** [comment]
Can you check the "enable driver" checkbox in the advanced settings and follow any debug steps that it provides? If it gives you an error, let me know.

**Comment by tumidrain880899** [comment]
It can be used now!!! Thank you so much
