### ISSUE TITLE
Sparkfox Wired Xbox 360 Controller Compatability 

### ISSUE THREAD

**Issue by NicNicSA** [360Controller/360Controller#972]
### Type of Controller
Sparkfox third-party Xbox 360 Wired Controller

### OS Version
10.13.6 High Sierra

### Driver Version
360Controller 1.0.0-alpha.5 ; 360Controller 1.0.0-alpha.4; 360Controller 1.0.0-alpha.3 ; 360Controller 1.0.0-alpha.2 ; 360Controller 1.0.0-alpha.1 ; 360Controller 0.16.11

### Connection Method
Wired USB

### Device Name and Info
(If you don't know this information, please refer to the README for how to find it. Enter N/A if not applicable)
>Device Name: Sparkfox W60X350
<br/>Product ID: 0x02a0
<br/>Vendor ID: 0x045e  (Microsoft Corporation)

### Response of Controller
Lights up on USB connection for couple of seconds before lights go out.

### Response in Preference Pane
Driver in System Preferences shows "No Devices Found"

### Detailed Explaination of Issue
All drivers so far have showed "No devices found". I have followed various youtube and other online instructions.

**Comment by FranticRain** [comment]
This product/vendor ID combination is already in the driver, so if this was going to work, it would have already worked. Oftentimes these Chinese product just steal the vendor and product ID combinations of real Microsoft controllers (as this one has) and just try to emulate them. However, they don't initialize properly with the driver. Supporting the amount of potential knockoffs that don't support the Xbox controller specification would be an astronomical amount of work and is outside the scope of this driver.
