### ISSUE TITLE
360Controller Preference Pane - Doesn't stay in dark mode

### ISSUE THREAD

**Issue by L0VEFIRE** [360Controller/360Controller#995]
### Type of Controller
Xbox One (1708)

### OS Version
macOS Catalina 10.15.2

### Driver Version
Version 1.0.0-alpha.5

### Connection Method
Wired (USB-C to Micro USB)

### Device Name and Info
**USB 3.1 Bus:**

  Host Controller Driver:	AppleIntelCNLUSBXHCI
  PCI Device ID:	0xa36d 
  PCI Revision ID:	0x0010 
  PCI Vendor ID:	0x8086 

**Controller:**

  Product ID:	0x02ea
  Vendor ID:	0x045e  (Microsoft Corporation)
  Version:	3.01
  Serial Number:	3033363030353037323632383239
  Speed:	Up to 12 Mb/s
  Manufacturer:	Microsoft
  Location ID:	0x14100000 / 6
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

### Response of Controller
N/A

### Response in Preference Pane
Loads in Dark mode for a second, then switches back to white background.

### Detailed Explaination of Issue
When loading the Xbox Preference Pane, in macOS Dark mode, the pane no longer remains in dark mode like it used to in previous version of the driver and now auto switches back to white after a second or two.
[Screen Recording 2019-12-28 at 10.11.27 AM.mov.zip](https://github.com/360Controller/360Controller/files/4007142/Screen.Recording.2019-12-28.at.10.11.27.AM.mov.zip)

**Comment by FranticRain** [comment]
This is a bug in macOS, and a duplicate issue. We can’t fix it.
